h2oai/datatable

c/csv/fread.cc, c/csv/reader_fread.cc, c/csv/reader_fread.h
* `meanLineLen` was not computed correctly when input had just 1 row. This caused wrong estimation of the number of chunks required
* Added diagnostic message (in verbose mode) when the number of threads is reduced due to input having too few rows.
* The amount of memory allocated per-thread is now reduced in case the number of rows is small.
Now the process only uses 464MB of memory to process the input file, which is reasonable. The data was also parsed "correctly" into a `[1 x 798355]` Frame.
Closes #874
=> Fix excessive memory usage when reading files with lots of columns and few rows

CHANGELOG.md, c/column.cc, c/column.h, c/column_fw.cc, c/column_string.cc, c/datatable_rbind.cc, tests/munging/test_dt_append.py
Note, this merely fixes the crash. It is still not possible to rbind string columns with non-string ones. In order to implement the latter, we need to implement casting from any column into string type.
Closes #880
=> Fixed a crash when rbinding string columns with non-string ones

CHANGELOG.md, c/csv/chunks.cc, c/csv/chunks.h, c/csv/fread.cc, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, tests/fread/test_fread_small.py
- Prevent type bumps when the chunk start may be invalid
- Fix bug in order_chunk logic, where an invalid chunk was resetting `lastChunkEnd` variable to 0.
- The errors about too many/too few columns will also no longer be emitted in a situation where the chunk start may be invalid.
- Fixed bug where NA strings surrounded with whitespace were not properly recognized.
Closes #878
=> Fread will no longer attempt to typebump unless it can be certain that the chunk start is valid

CHANGELOG.md, c/column.h, c/column_from_pylist.cc, c/column_pyobj.cc, c/rowindex_array.cc, c/stats.cc, c/stats.h, c/types.h, c/utils/pyobj.cc, c/utils/pyobj.h, tests/test_dt_stats.py
- Implemented `countna` function for a column of object type (previously it was seg.faulting)
- When creating an object column, we will now convert float "nan" values into NAs (represented as Py_None).
Closes #887
=> countna() on columns of object type

CHANGELOG.md, c/datatable.h, c/datatable_rbind.cc, c/datatablemodule.c, c/options.cc, c/options.h, c/py_column.h, c/py_columnset.h, c/py_datatable.cc, c/py_datatable.h, c/py_rowindex.h, c/py_utils.c, c/py_utils.h, c/utils.h, datatable/frame.py, tests/test_dt_options.py
This adds a new option `dt.options.core_logger` which can be set to a `Logger` instance, and it will be called every time we start/end a call to any core function.
=> Implement logging as an option

CHANGELOG.md, c/column.h, c/column_pyobj.cc, datatable/frame.py, tests/test_dt.py
* Fix crash which was happening when materializing a view containing obj64 columns. (And if by accident it wasn't crashing, it could have caused action-at-a-distance crashes some time later on).
* Added method `Frame.materialize()` to convert a view Frame into a regular data frame. (This replaces the need to call `Frame(frame.internal.materialize(), names=frame.names)`)
Closes #898
=> Fix crash when materializing view frames with obj columns

c/sort.cc
Major cleanup in `sort.cc`: 
* `radix_psort` and `insert_sort` are  now methods of `SortContext` instead of standalone functions
* When performing radix recursion, reuse the current `SortContext` object instead of creating a copy
* Better handle sort parameters, trying to make sure that sorting doesn't crash when those parameters are modified.
* Greatly simplify the API of SortContext, and eliminate any repeating code.
=> Sort cleanup

CHANGELOG.md, c/datatablemodule.c, c/options.cc, c/options.h, c/sort.cc, datatable/frame.py, datatable/options.py, setup.py, tests/test_dt_options.py, tests/test_dt_sort.py
```
def sort_benchmark():
import datatable as dt
import numpy as np
from time import time
a = np.random.randn(10**7)
d = dt.Frame(a)
p = d.topandas()
l = d.topython()[0]
t0 = time(); dd = d.sort(0);           print("datatable: %.3fs" % (time() - t0))
t0 = time(); a.sort();                 print("numpy:     %.3fs" % (time() - t0))
t0 = time(); pp = p.sort_values("C1"); print("pandas:    %.3fs" % (time() - t0))
t0 = time(); l.sort();                 print("python:    %.3fs" % (time() - t0))
```
gives the following results:
```
>>> sort_benchmark()
datatable: 0.614s
numpy:     0.895s
pandas:    2.863s
python:    9.356s
```
On server, speed comparison is not as beneficial to datatable though. In particular, comparing to numpy we have times 0.07695 (datatable) and 0.07630 (numpy) when sorting …
=> Improve speed of sorting float64 values

Makefile, c/csv/chunks.h, c/csv/fread.cc, c/csv/fread.h, c/csv/freadLookups.h, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/csv/reader_parsers.cc, c/csv/reader_parsers.h, c/csv/reader_utils.cc, datatable/fread.py, tests/fread/test_fread_large.py, tests/fread/test_fread_small.py
Eliminate global static arrays `parsers`, `typeSymbols`, `typeNames`, `typeSizes`, `coltype_to_stype`, and instead create a single repository of all information about the parsers: the `ParserLibrary` class, which can be accessed either statically or through an instance.
WIP for #657
WIP for #909
=> Consolidate all type information in the ParsersLibrary class

c/csv/chunks.cc, c/csv/fread.cc, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/utils.c, c/utils.h, c/utils/exceptions.cc, c/utils/exceptions.h, tests/fread/test_fread_issues.py, tests/fread/test_fread_small.py
* Created class `FreadObserver` to keep track of various timers / measures that will be reported in the end. This allows to greatly declutter the main class and many of its helper classes.
* Fixed bugs with reporting of timings in the final report.
* Better report: big numbers are humanized, correct plurals are used.
* Improve performance when reading small files by tweaking the `minChunkSize` constant
* Significantly simplified API of `FreadChunkReader` class.
* Eliminated `stopErr` logic: now an exception is raised instead.
* "[11] Read the data" message will now be displayed only once.
* Added 3 fread tests covering cases of too many / too few columns on an out-of-sample row; and also the case of type bumps in multiple columns.
WIP for #909
=> FreadObserver class

tests/fread/test_fread_random.py
The test case can be reduced to this:
```
A
"8"
""
```
Should the column be treated as string, or integer? From practical standpoint, given many rows, if they contain only digits / quoted empty strings, then it is far likelier that the column was really integer (perhaps saved to csv with always_quote=True)... 
So in this case `fread` was correct and the test wrong.
Closes #926
=> Fix treatment of "" in the fread omnibus test

c/csv/chunks.cc, c/csv/fread.cc, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/utils/exceptions.cc, c/utils/exceptions.h, tests/fread/test_fread_small.py
* "allocnrows" fault in ChunkedDataReader is now handled without switching to single-threaded context (and without discarding the data that was already read).
* progress bar for files >256MB will now appear immediately, w/o delay.
* Removed unnecessary / duplicate variables from ChunkedDataReader; renamed some of the existing variables for clarity.
* Simplified API of ChunkedDataReader
* Added descriptive comments
* Added few fread tests (unrelated to ChunkedDataReader though)
=> Clean-up of ChunkedDataReader

Jenkinsfile2
The change enables an option to trigger PPC64le build and disables default build of PPC64le.
=> [BUILD] Parameterize the build and disable PPC64le by default

Makefile, c/csv/chunks.cc, c/csv/fread.cc, c/csv/fread.h, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/csv/reader_parsers.cc, c/csv/reader_parsers.h, c/csv/reader_utils.cc, datatable/fread.py, tests/fread/test_fread_api.py, tests/fread/test_fread_issues.py, tests/fread/test_fread_large.py
* Types / headers detection split out from "freadMain" into a separate function, which was further subdivided into 3 parts.
* This is an attempt to merge in changes in R's fread in column detection logic
* All column types are now `PT` instead of `int8_t` or `uint8_t`.
* Fixed uneven spacing in trace messages
* 1 test marked as xfail (regarding footer detection) - will fix later
=> Fread column types detection logic improvements

c/csv/chunks.cc, c/csv/fread.cc, c/csv/reader.cc, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/csv/reader_utils.cc, tests/fread/test_fread_issues.py, tests/fread/test_fread_large.py, tests/fread/test_fread_small.py
* Detect presence of a comment section on top of the file and automatically skip it.
* Better reporting of line numbers in error messages.
* Removed logic to skip "inconsistent number of rows at the beginning of the file". This logic was skipping arbitrary pieces of data, with giving much of an explanation to the user... It was also interfering with proper headers detection.
* File `../h2o-3/smalldata/jira/hexdev_325.csv` can now be parsed correctly.
* File `../h2o-3/smalldata/junit/is_NA.csv` is now parsed correctly.
* File `../h2o-3/smalldata/junit/mixcat_test.csv` no longer emits a warning.
* File `../h2o-3/smalldata/parser/orc/orc2csv/nulls-at-end-snappy.csv` is now parsed correctly.
Closes #937
=> Fread skip comments section

CHANGELOG.md, c/csv/fread.cc, c/csv/reader_fread.cc, c/csv/reader_parsers.cc, tests/fread/test_fread_small.py
* `strlim()` function now escapes non-ascii and control characters when printing a line. This helps avoid display issues / encoding problems when throwing an error.
* Strings with NUL characters can now be safely read (as shown in tests)
* Fixes assertion violation when detecting sep/QR
* The example file from #947 no longer throws an assertion error -- instead it's a RuntimeError about too few fields on line 2
Closes #790 
Closes #947
=> Support strings with embedded NUL characters in fread

c/csv/fread.h, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/csv/reader_parsers.cc, c/csv/reader_parsers.h, c/csv/reader_utils.cc, datatable/fread.py, tests/fread/test_fread_detect.py, tests/fread/test_fread_small.py
* Add "Mu" (unknown) parser type, which matches only empty columns. 
* This type is used as a root of type hierarchy, which is a much better choice than Bool01
* Improve column name detection in cases when some of the columns are of Mu type.
WIP for #657
Closes #656
Closes #515
=> Fread: add Mu type to type hierarchy

CHANGELOG.md, datatable/frame.py, tests/test_dt_options.py
For example:
```
>>> import datatable as dt
>>> dt.options.frame.names_auto_prefix = "Column "
>>> dt.options.frame.names_auto_index = 1
>>> dt.Frame([[1], [2], [3]])
Column 1  Column 2  Column 3
---  --------  --------  --------
0          1         2         3
[1 row x 3 columns]
```
Closes #949
=> Added options .frame.names_auto_index and .frame.names_auto_prefix

CHANGELOG.md, Makefile, c/column_from_pylist.cc, c/column_string.cc, c/csv/fread.cc, c/csv/reader.cc, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/csv/reader_parsers.cc, c/csv/reader_parsers.h, c/csv/reader_utils.cc, c/python/list.cc, c/python/list.h, c/python/long.cc, c/python/long.h, c/python/string.cc, c/python/string.h, c/types.c, c/utils/pyobj.cc, c/utils/pyobj.h, datatable/fread.py, datatable/nff.py, tests/fread/test_fread_api.py
* API change: when `columns` parameter is a function, then up to now this function was called multiple times, once for each column in the input dataset. However from now on, the function will receive the list of all column descriptions at once, allowing the user to apply more elaborate logic in deciding which columns to keep / modify.
* Column descriptors passed to the function are named tuples containing fields `(name, type)`. In the future `format` will also be added. The `type` field here is the `stype` of the column (previously they were integer constants corresponding directly to the internal `PT` enum).
* At C++ level, parser type `PT::Drop` was removed (it is now a "requested type" `RT::RDrop`).
* Each `GReaderColumn` now has field `rtype` containing the "user-requested type" of …
=> Fread improvements to `columns` parameter

CHANGELOG.md, c/sort.cc, c/sort.h, c/sort_groups.cc, c/sort_insert.cc, tests/test_dt_sort.py
Columns of stype `str64` (aka `"s8"`) can now be sorted like all other column types.
Closes #955
=> Allow sorting str64 columns

MANIFEST.in
The problem was that `sdist` command tries to automatically include files it thinks are needed; and at the same time the option `--no-defaults` does not work.
Closes #974
=> Exclude binary files from source distribution

c/csv/fread.cc, c/csv/reader.cc, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/csv/reader_utils.cc, tests/fread/test_fread_api.py
Before now only input samples were anonymized. Now column names are anonymized too (if option `dt.options.fread.anonymize` is turned on).
=> Anonymize column names in fread's error messages as well

CHANGELOG.md, Makefile, c/column.h, c/column_fw.cc, c/column_pyobj.cc, c/column_string.cc, c/types.h, datatable/__init__.py, datatable/dt_append.py, datatable/frame.py, tests/munging/test_dt_append.py
* New module-level `dt.rbind()` function to rbind several frames without modifying any of them (this is a convenient shortcut for `dt.Frame().rbind(...)`). Similarly, `dt.cbind()` was also added.
* It is now possible to rbind columns of any types, including cross-type rbinds.
* Added type cast str32->str64
* Additional tests for rbinding
Closes #1018
=> Rbind various improvements

CHANGELOG.md, c/csv/chunks.cc, c/csv/reader.cc, c/csv/reader.h, tests/fread/test_fread_random.py
Identified 1 instance where a debug message was generated from a non-master thread. Put checks in place that such messages are delayed for the master thread. Hopefully this should resolve the GIL_Check problem (although hard to know for sure, since the problem was not reproducible).
Closes #1013
=> Ensure that fread only emits messages to Python from the master thread.

CHANGELOG.md, c/csv/reader.cc, c/csv/reader_parsers.cc, c/options.cc, c/options.h, tests/fread/test_fread_random.py, tests/fread/test_fread_small.py
Note that this change also makes it unnecessary to supply quoted the na strings
```
>>> dt.fread("c1,c2,c3\n"
"a,b,c\n"
'nan,inf,"inf"', na_strings=['inf', 'nan'])
c1  c2  c3
---  --  --  --
0   a   b   c 
1             
[2 rows x 3 columns]
```
Closes #1014
=> Fread now recognizes quoted NA strings

ci/Jenkinsfile2, ci/default.groovy
Closes #1016.
Flow of the pipeline is now following (nothing is changed for PRs):
1. Initialization
2. Build, Coverage and Test all platforms
3. If we are building `master` or `rel-*` branch then publish to `artifacts.h2o.ai`
1. ~If building `master`, publish to `h2o-release` under `nightly`~. Nightly builds are uploaded to `artifacts.h2o.ai` only.
2. If building other branch, ask for user approval, if granted, then publish to `h2o-release` under `stable` and create a GitHub release.
=> [BUILD] GitHub Release

CHANGELOG.md, Makefile, c/memrange.cc, c/mmm.cc, c/mmm.h
It appears there were multiple problems with memory-mapped objects, which all decided to manifest in this test case. How convenient. Here's the list of fixes:
- If `errno 12` was raised 3 times in a row even after we attempt to free up the resources, the code was not raising any error but instead proceeded as if memory map was done successfully. Later on an attempt to read/write to such data pointer was causing a crash.
- `MmapMRI::memunmap` was not working properly for 0-size files.
- The eviction logic in `MemoryMapManager` was accidentally removing two last entries from the list of memory maps instead of one, which means that (a) later on evictions were performed on wrong objects; (b) some of the tracked memory maps were "lost" by the MemoryMapManager and could not be properly evicted …
=> MemoryMapManager fixes

.gitignore, Makefile, c/csv/reader.cc, ci/asan-env.sh, ci/asan-pip.py, ci/asan-python.c, ci/default.groovy, datatable/__init__.py, tests/fread/test_fread_api.py, tests/munging/test_dt_append.py, tests/munging/test_dt_cbind.py, tests/test_dt_create.py, tests/test_nff.py
Running Asan on a Python extension module is challenging. In theory it should be possible, but [the documentation](https://github.com/google/sanitizers/wiki/AddressSanitizerAsDso) states "Use at your own risk". In practice, I wasn't successful at running Asan via `LD_PRELOAD` or `DYLD_INSERT_LIBRARIES` as suggested.
This PR uses a different approach: create a new executable that *embeds* Python (as described [in python docs](https://docs.python.org/3/extending/embedding.html)). This executable however will be compiled with static Asan support. Then I can use that executable as if it was "real" python, by installing it into a fresh virtual environment. 
Running `datatable` with Asan revealed a single instance of unsafe memory read, which this PR also fixes.
=> Implement proper compilation with AddressSanitizer

CHANGELOG.md, c/csv/reader.cc, c/csv/reader_fread.cc, datatable/fread.py, tests/fread/test_fread_small.py
* fread will detect feather file and issue an appropriate error message.
* when fread extracts data from archives into memory, it will now display the size of the extracted data in verbose mode.
* fread will no longer emit an error if there is an NA string in the header.
* if the input contains excessively long lines, fread will no longer waste time printing a sample of first 5 lines in verbose mode.
* fixed wrong calculation of mean / standard deviation of line length in fread if the sample contained broken lines.
-----
Note that the core of the problem is that fread is not well-suited for ill-formed input files that contain hardly any newlines. Because fread needs to scan the first several lines multiple times, it may take very long time to finish. This PR sidesteps the issue by …
=> Fread fixes

CHANGELOG.md, tests/test_groups.py
This functionality was already accidentally implemented in PR #1072. This PR merely adds a test to ensure that it won't break in the future.
Closes #1032
=> Reduction over multiple columns

CHANGELOG.md, datatable/graph/cols_node.py, tests/test_groups.py
Now when you say `DT[:, mean(f.A), f.B]`, the result will contain 2 columns: first is "B" (the groupby key), and second is the `mean(A)` value columns.
Closes #1076
=> Automatically append group columns to the select list during groupby

c/csv/reader_utils.cc
This is a problem with the core Python, submitted an issue at python mailing list: https://bugs.python.org/issue33742
Luckily, it's easy to work around, so I'm implementing a local fix too.
Closes #1085
=> Work-around for python bug with PyStructSequence_InitType

c/py_utils.c, c/py_utils.h, tests/test_dt_options.py
When using `dt.options.core_logger`, the timing for each call will now be reported. This should help profile the code and discover possible bottlenecks.
=> Add call timing in the report of dt.options.core_logger

CHANGELOG.md, c/datatable.cc, c/expr/binaryop.cc, c/expr/py_expr.cc, c/expr/reduceop.cc, c/expr/unaryop.cc, c/py_columnset.cc, c/utils/array.h, datatable/frame.py, tests/fread/test_fread_api.py
* Tweaked `sort.max_radix_bits` constant to speed up sorting
* Groupby operations are now significantly faster (especially function `first`) because columns are no longer materialized before performing the reduction.
For the same operation as in #1095, we have now the following timings:
```
>>> y = x[:, {"v1": sum(f.v1)}, f.id1]
call DataTable.rowindex
done DataTable.rowindex in 0.000 ms
call DataTable.stypes
done DataTable.stypes in 0.008 ms
call DataTable.rowindex
done DataTable.rowindex in 0.000 ms
call DataTable.sort(...)
done DataTable.sort(...) in 85.602 ms
call CLSNAME.expr_column(...)
done CLSNAME.expr_column(...) in 0.006 ms
call CLSNAME.expr_reduceop(...)
done CLSNAME.expr_reduceop(...) in 0.078 ms
call del Column
done del Column in 0.005 ms
call CLSNAME.expr_column(...)
done …
```
=> Faster groupby

CHANGELOG.md, c/memrange.cc
This addresses problem encountered in DAI (e.g. https://github.com/h2oai/h2oai/issues/3716, https://github.com/h2oai/h2oai/issues/3718, https://github.com/h2oai/h2oai/issues/3723)
=> Fix occasional memory errors caused by a lack of available mmap handles.

Makefile, c/column_pyobj.cc, c/columnset.cc, c/datatable.cc, c/datatable.h, c/datatable_cbind.cc, c/datatable_load.cc, c/datatable_rbind.cc, c/datatablemodule.cc, c/memrange.cc, c/memrange.h, c/py_buffers.cc, c/py_columnset.cc, c/py_datatable.cc, c/py_datatable_fromlist.c, c/py_types.c, c/py_utils.c, c/sort.cc, c/types.c, c/utils.c, c/utils.h, c/utils/alloc.cc, c/utils/alloc.h, c/utils/array.h, c/writebuf.cc, c/writebuf.h
* Many old macros such as `dtmalloc`, `dtrealloc`, `dtfree`, `dterrr` etc. that were used only in few places, were eliminated.
* Added utility functions `dt::malloc` and `dt::realloc` that are somewhat smarter than standard `malloc` and `free`: they will attempt to free up memory if the first attempt at allocating fails with errno=12 (ENOMEM).
* `ThreadsafeWritableBuffer` now uses `dt::shared_mutex` for read/write access control (this replaces the old mechanism which was based on atomically incrementing /decrementing a counter). Now it is no longer possible for this object to become deadlocked if `resize()` call throws an exception.
=> Memory handling code cleanup

CHANGELOG.md, Makefile, c/csv/chunks.cc, c/csv/reader.h, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/csv/reader_utils.cc, datatable/fread.py, tests/fread/test_fread_api.py, tests/fread/test_fread_small.py
* Fix bug in fread that sometimes resulted in memory corruption when reading a file and a QR bump occurred in the middle of the file.
* Eliminate some dead code in fread's LocalParseContext
* Eliminate `StrBuf`s array, replacing it with a single string buffer per `LocalParseContext` + an array of auxiliary information `dt::array<SInfo>`. This reduces the code complexity, the number of memory allocations, and the chance that `strbufs` will become desynchronized with `columns`.
* Added a test
Closes #1117
=> Fread bug (assertion error / memory error)

CHANGELOG.md, datatable/fread.py, datatable/types.py, datatable/utils/terminal.py, datatable/utils/typechecks.py, tests/test_dt.py
Import datatable time reduced from 0.580s to 0.133s (x4.4 improvement).
For comparison, importing pandas takes 0.387s, and numpy 0.106s.
This also helps with #1077, reducing the time it takes to launch a new python process with `datatable` module.
Closes #1122
=> Reduce startup time of datatable

c/column.cc, c/column.h, c/column_fw.cc, c/column_pyobj.cc, c/column_string.cc, c/datatable.h, c/datatable_load.cc, c/py_datatable.cc, datatable/nff.py
These checks are causing unnecessary delays with many-column frames.
If a frame was saved into NFF correctly, and the NFF was not manually modified by the user, these checks are not needed. However in the unlikely event that one of these assumptions fail, the system will now crash instead of throwing a graceful exception.
There seems to be no easy way of postponing the checks until the time the column(s) are actually read, which is why I had to remove the checks altogether.
We will be able to restore those checks after switching to Jay binary format (#1109).
Closes #1130
=> Remove basic integrity checks when opening mmap columns

CHANGELOG.md, c/csv/chunks.cc, c/csv/reader_fread.cc
- Fix incorrect initial estimate of the number of rows needed (this bug was introduced very recently);
- Fix incorrect usage of a shared mutex lock when resizing the output columns. Because of this bug, it was possible to get a crash (or malformed output) in rare cases.
Closes #1149
=> Fread fixes: lock and initial rows estimate

CHANGELOG.md, c/csv/writer.cc, c/csv/writer.h, tests/test_tocsv.py
Fixed bug where "view" aspect of a Frame was not taken into account when saving it into csv.
Closes #932
=> View frames can now be saved to csv properly

c/utils/omp.h
Warnings usually appear on `x86_64_centos` platform:
```
In file included from c/utils/omp.h:17:
/opt/h2oai/dai/include/omp.h:17:12: warning: macro name is a reserved identifier [-Wreserved-id-macro]
^
/opt/h2oai/dai/include/omp.h:31:16: warning: macro name is a reserved identifier [-Wreserved-id-macro]
^
/opt/h2oai/dai/include/omp.h:185:11: warning: macro name is a reserved identifier [-Wreserved-id-macro]
^
3 warnings generated.
```
=> Prevent warnings coming from omp.h include on some platforms

CHANGELOG.md, datatable/frame.py, tests/test_dt_create.py
It is now possible to construct a Frame by giving the source columns as a list of kwd args:
```
dt.Frame(col1=..., col2=..., col3=...)
```
Closes #1105
=> Enable construction of Frame from kwd args

c/csv/fread.cc, c/csv/fread.h, c/csv/reader.cc, c/csv/reader.h, c/csv/reader_fread.cc, c/read/fread/fread_parallel_reader.cc, c/read/fread/fread_parallel_reader.h, c/read/parallel_reader.cc, tests/fread/test_fread_api.py, tests/fread/test_fread_small.py
- `next_good_line_start()` method was moved into `FreadTokenizer`, so that `ColumnTypeDetectionChunkster` doesn't need to instantiate a `ParallelReader`.
- Do not attempt to reallocate output columns if the size is already correct.
- If the input is a string, do not say in verbose message "memory-mapping file"
- Use bytes object instead of string for `test_maxnrows_on_large_dataset` so that fread doesn't waste time converting it into bytes (for the case max_nrows=5 the majority of time is spent there).
Closes #1179
=> Fix minor fread issues

c/extras/aggregator.cc
Minor change, but prevents the `aggregator` from crashing.
Until we find a good way to treat categorical columns in the ND
aggregation algo, we skip those in the both cases: `ncols` <=`max_dimensions` and 
`ncols` > `max_dimensions`. 
Closes #1185
=> Properly skip categorical columns during the ND aggregation

c/csv/reader_fread.cc, c/read/parallel_reader.cc, tests/test_groups.py
* Fix `sd` calculation formula in case the lines are long (previously the formula produced wrong results for line lengths > 46340)
* Improve the algorithm for chunk size selection: if the lines are long we are better-off reducing the number of lines per chunk below 1000.
=> Tweak fread chunking strategy to better handle wide datasets

c/extras/aggregator.cc, tests/extras/test_aggregate.py
- converting group ids to exemplar ids for 1D and 2D aggregations to be
consistent with the ND case;
- adjusting 1D and 2D tests to reflect the format changes;
- some cosmetics.
Closes #1200
=> Change format of members datatable in aggregator

c/extras/aggregator.cc, c/stats.cc, c/stats.h, c/utils/exceptions.cc, c/utils/exceptions.h, tests/extras/test_aggregate.py, tests/fread/test_fread_small.py, tests/test_dt.py
Adding tests to ensure that various stats would not get corrupted if a column is modified.
Since Stats are cached, it is easy to forget to invalidate the cache when the column is modified. These tests will attempt to catch such an occurrence.
Currently, the checks for StDev, Kurtosis, and Skewness are turned off, due to algos for their calculation being numerically unstable. This needs to be addressed in the future.
Also, some aggregator tests were marked XFAILing, because they are now failing.
Closes #1143
=> Stats integrity checks

tests/test_join.py
The issue was that some float64 values were mapped into the same float32 values, which causes the values in the column to be non-unique.
Closes #1208
=> Fix rare failure in test_join_random

Makefile, ci/Dockerfile-centos7.in, ci/Jenkinsfile2, tests/fread/test_fread_small.py
This PR adds env var LD_LIBRARY_PATH for CentOS 7 docker images. The env var is required, otherwise it results in `ImportError: libc++.so.1: cannot open shared object file: No such file or directory`
=> [BUILD] Set LD_LIBRARY_PATH for CentOS 7 image.

tests/conftest.py, tests/fread/test_fread_small.py, tests/test_dt.py
Also attempt to fix `test_float_decimal0`, which is broken on PPC64.
=> Print out various platform information during testing

Makefile, ci/Jenkinsfile2, setup.py
I've added an option to pass the git revision as env var. I think it's a bit safer than stashing the `.git` folder in jenkins (there might be something host dependent in this folder I think).
If `DTBL_GIT_HASH` is `None` or empty string, then it reads the revision from git, if `.git` is not accessible it fails.
Also sdist is now built for PRs as well. The stage is matter of seconds, so I think it's reasonable to build it as a part of PRs as well, WDYT?
Closes #1212
=> [BUILD] Add option to pass git revision via variable.

Makefile, c/datatablemodule.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/py_datatable.cc, c/python/arg.h, c/python/args.cc, c/python/args.h, c/python/ext_type.h, c/utils/pyobj.cc, c/utils/pyobj.h
This is a new framework for defining Python objects from C++. It intends to supplement the existing methodology (see py_utils.h), which is largely based on an assortment of macros.
The framework is not yet complete. The following is currently possible:
* Define a new python extension type by deriving from `py::ExtType`;
* Specify constructor/destructor/repr functions by defining methods with predefined names, such as `void m__dealloc__()`;
* Define any number of getters/setters, and then declare them via `static void init_getsetters(GetSetters&)`;
* Define any number of methods, and then declare them via `static void init_methods(Methods&)`;
* All methods are automatically wrapped into exception-catching blocks;
* Methods can receive an arbitrary number of parameters and keyword …
=> Py framework

c/py_datatable.cc, c/py_datatable.h, datatable/frame.py, datatable/graph/__init__.py, datatable/graph/cols_node.py, datatable/graph/context.py, datatable/graph/dtproxy.py, tests/test_dt.py, tests/test_dt_options.py
Removed `_id`, `_ncols`, `_nrows`, `_stypes`, `_ltypes` -- all of these can be retrieved from the internal `_dt` object.
Closes #1238
=> Remove unnecessary properties from Frame

c/jay/README.md, c/jay/open_jay.cc, c/jay/save_jay.cc
* Added documentation for the internal Jay format.
* The trailing signature changed from "JAY1" into "1JAY" (however, the old signature is still accepted).
Closes #1244
=> Add documentation for Jay format

c/py_datatable.cc, tests/test_dt.py
The actual bug fix is 1 line of code -- to clear the stypes+ltypes when deleting columns.
However, this PR also adds integrity checks for internal properties `.stypes`, `.ltypes`, `.names` and `.inames`, so that this kind of errors could be caught more easily in the future.
Closes #1248
=> Fix bug with ltypes being left in incorrect state after deleting columns

CHANGELOG.md, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/py_frame_init.cc, c/py_datatable.cc, c/py_datatable.h, c/python/arg.cc, c/python/arg.h, c/python/args.cc, c/python/args.h, c/python/ext_type.h, c/python/obj.cc, c/python/obj.h, c/python/tuple.cc, c/python/tuple.h, datatable/frame.py, datatable/graph/__init__.py, datatable/graph/rows_node.py, tests/test_dt.py, tests/test_dt_create.py, tests/test_dt_options.py
* Added `varargs` and `varkwds` iterators to `PKArgs` class;
* Implement getters/setters for core `Frame` class properties `.nrows`, `.ncols` and `.shape`;
* Python `Frame` class now inherits from core `Frame` class, allowing incremental transition for #1066;
* Removed from python `Frame` properties `.nrows`, `.ncols` and `.shape` since they are now inherited;
* Small improvements to `py::obj` class;
* The `Args` class now better integrates with `py::obj`;
* Added `py::otuple` class for easier tuple creation.
=> Core Frame class improvements

c/column.h, c/column_from_pylist.cc, c/csv/reader.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/py_frame_init.cc, c/frame/py_frame_names.cc, c/py_column.cc, c/py_columnset.cc, c/py_datatable.cc, c/py_datatable_fromlist.cc, c/py_groupby.cc, c/python/arg.cc, c/python/arg.h, c/python/dict.cc, c/python/dict.h, c/python/ext_type.h, c/python/float.cc, c/python/float.h, c/python/int.cc, c/python/int.h, c/python/list.cc, c/python/list.h, c/python/obj.cc, c/python/obj.h, c/python/string.cc, c/python/string.h, c/python/tuple.cc, c/python/tuple.h, c/read/column.cc
This PR enforces consistent API among all `py::` classes.
From this point onward we should try to use the new API only, and stay away from pure-C pythonic API.
Closes #1257
=> Cleanup of py:: API

c/csv/fread.cc, c/csv/reader_fread.cc, tests/fread/test_fread_issues.py
Due to imperfect type hierarchy, this file triggers re-reads more than once. However, fread had just one re-read hardcoded before -- now there will be as many re-reads as necessary...
Closes #1233
=> Fread bug with column containing mixed NaN/int values

CHANGELOG.md, c/datatablemodule.cc, c/extras/aggregator.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/py_frame_init.cc, c/py_datatable.cc, c/py_datatable.h, c/python/arg.cc, c/python/arg.h, c/python/obj.cc, c/python/obj.h, datatable/extras/aggregate.py, datatable/frame.py, datatable/fread.py, datatable/nff.py, tests/extras/test_aggregate.py, tests/fread/test_fread_api.py, tests/test_dt.py
* Added method `frame.copy()`;
* Several modes of Frame initialization are now done in C++ instead of in Python;
* Creating a Frame from `core._DataTable` object is no longer supported (the use of these objects will be slowly phased out).
WIP for #1066
=> Frame initialization improvements

CHANGELOG.md, c/column.h, c/column_from_pylist.cc, c/frame/py_frame_init.cc, c/python/dict.cc, c/python/dict.h, c/python/list.cc, c/python/list.h, c/python/obj.cc, c/python/obj.h, c/python/oset.cc, c/python/oset.h, tests/test_dt_create.py
Add 2 new modes for Frame construction:
1) from a list of dictionaries when the column names are provided explicitly;
2) from a list of dictionaries when the column names are deduced.
Also small improvements to `py::` library:
* Added `pylist::append()` method
* Added `py::oset` class
* Added `py::rdict` class
Closes #1266
=> Make frame from a list of dicts

c/csv/py_csv.cc, c/csv/reader.cc, c/datatable.cc, c/datatable.h, c/datatable_cbind.cc, c/extras/aggregator.cc, c/frame/names.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/py_frame_init.cc, c/frame/py_frame_names.cc, c/jay/open_jay.cc, c/py_columnset.cc, c/py_datatable.cc, c/py_datatable.h, c/py_datatable_fromlist.cc, c/python/dict.cc, c/python/dict.h, c/python/tuple.cc, c/python/tuple.h, c/utils/exceptions.cc, c/utils/exceptions.h, c/ztest.cc, c/ztest.h, datatable/dt_append.py, datatable/frame.py, tests/test_dt.py
* `Frame.names` moved to `DataTable.py_names`;
* `Frame.inames` moved to `DataTable.py_inames`;
* Cleaned up integrity checks for `.names`, `.py_names` and `.py_inames` in `DataTable`;
* `DataTable` has now multiple constructors, depending on how the names of the columns should be initialized;
* Added C++ tests to ensure proper coverage of integrity checks;
* `.open_jay()` no longer takes string vector reference as a parameter -- instead it directly assign names to the DataTable returned;
* `.cbind()` now produces DataTable with correct names already set;
Closes #1270
=> (py)names properties moved to core DataTable class

Makefile, c/frame/names.cc
* `--no-external`: prevent system libraries from showing up in the coverage report;
* `--legend`: add into the generated HTML an explanation what each color means;
* `--demangle-cpp`: replace mangled c++ names with human-readable names;
* exclude 2 lines in `names.cc` which are spuriously marked as non-covered.
=> Extra options to generate better coverage report

CHANGELOG.md, c/csv/writer.cc, tests/test_tocsv.py
The crash came because of mis-estimating the line length (forgot to account for the separators).
Closes #1278
=> Fix crash when saving a Frame to CSV

CHANGELOG.md, c/csv/writer.cc, c/expr/reduceop.cc
Testing on my laptop (8 cores) with the following script:
```python
import datatable as dt
import random
import time
from datatable import sum, f
n = 10**8
col1 = [random.randint(1, 100) for _ in range(1000)] * (n // 1000)
col2 = [random.random() for _ in range(20000)] * (n // 20000)
assert len(col1) == len(col2) == n
fr = dt.Frame(A=col1, B=col2)
for _ in range(5):
t0 = time.time()
fg = fr[:, sum(f.B), f.A]
t1 = time.time()
print("Time taken: %.3fs" % (t1 - t0))
```
Before this change, timings were:
```
Time taken: 2.600s
Time taken: 2.184s
Time taken: 2.140s
Time taken: 2.196s
Time taken: 2.196s
```
After this change, timings are:
```
Time taken: 1.383s
Time taken: 1.028s
Time taken: 1.066s
Time taken: 1.040s
Time taken: 1.051s
```
Closes #1284
=> Parallelize groupby calculations

tests/random_attack.py
This is a bug in the `random_attack.py` script, not in `datatable` itself. 
Generally, we should avoid shallow copies of data columns, since in that case modifying one of the columns may affect another.
Closes #1291
=> Do not modify elements in-place in resize_rows() transformer

CHANGELOG.md, c/rowindex.h, c/rowindex_array.cc, c/rowindex_slice.cc, tests/test_dt.py
* `ArrayRowIndexImpl` will now store its `is_sorted` flag: this is useful for subsequent transforms and also min/max calculation.
* fixed bug where min/max values were not updated when the rowindex was shrunk (both for slice and array implementations).
Closes #1290
=> Fix calculation of min/max values in internal rowindex upon row resizing

CHANGELOG.md, c/datatable.cc, c/datatable.h, c/datatablemodule.cc, c/datatablemodule.h, c/frame/py_frame_init.cc, c/py_columnset.cc, c/python/ext_module.h, c/python/ext_type.h, c/str/py_str.cc, c/str/py_str.h, c/str/split_into_nhot.cc, datatable/__init__.py, datatable/str.py, tests/munging/test_str.py
This PR adds a new function `dt.split_into_nhot(frame, sep)`, which acts upon an `n x 1` Frame (of str32 or str64 type) and produces an `n x k` Frame with boolean columns. Each value in the input column is split according to the provided separator, the whitespace is trimmed, and the resulting pieces are converted into individual columns in the output frame.
For example, frame
```
| cat,dog       |
| mouse         |
| cat,mouse     |
| dog,rooster   |
| mouse,dog,cat |
```
gets converted into
```
| cat  dog  mouse rooster |
|   1    1      0       0 |
|   0    0      1       0 |
|   1    0      1       0 |
|   0    1      0       1 |
|   1    1      1       0 |
```
Closes #1298
=> Split string and nhot-encode

CHANGELOG.md, c/expr/unaryop.cc, datatable/__init__.py, datatable/expr/__init__.py, datatable/expr/abs_expr.py, datatable/expr/consts.py, datatable/expr/unary_expr.py, tests/test_dt_expr.py
This PR adds `abs()` function, exported from the `datatable` namespace, to compute the absolute value of columns in a Frame. This function can safely replace the builtin python `abs()`. Use as follows:
```python
>>> import datatable as dt
>>> from datatable import f, abs
>>> DT = dt.Frame(X=[-3, 4, 1], Y = [7, 0, 6])
>>> DT1 = DT[:, abs(f.X - f.Y)]  # absolute value of difference between columns X and Y
```
Closes #1323
=> Added abs() function

CHANGELOG.md, c/frame/py_frame_init.cc, datatable/fread.py, datatable/xls.py, tests/test_dt_create.py
* sheet name can now be used as a path component in the file name, causing only that particular sheet to be parsed;
* further, a cell range can be specified as a path component after the sheet name, forcing fread to consider only the provided cell range. For example, the following request is now valid:
``` 
dt.fread("../h2oai/tests/data/diabetes_tiny_two_sheets.xlsx/Sheet1/A10:BC30")   
```
* fread can now handle the situation when a spreadsheet has multiple separate tables in the same sheet. They will now be detected automatically and returned to the user as separate Frame objects (the name of each frame will contain the sheet name and cell range from where the data was extracted).
=> Improve handling of Excel files

CHANGELOG.md, c/frame/_repr_html_.cc, c/frame/py_frame.cc, c/frame/py_frame.h, datatable/frame.py, datatable/fread.py, datatable/utils/terminal.py
This PR adds method `Frame._repr_html_()`, which is invoked by JupyterLab to generate nice HTML view of the object.
Most styling is inherited from the Jupyter stylesheet, and only a few own styles are added. These styles are scoped by `.datatable` CSS selector: the idea is to render all HTML widgets inside `<div class=datatable />`. The styles are also emitted only once per session.
Generally, the rendered view is similar to how pandas DataFrame looks like; in particular, when there are too many rows/columns the middle ones are omitted.
Closes #68
=> Better rendering of a Frame in Jupyter notebook

c/extras/aggregator.cc, c/extras/aggregator.h, datatable/extras/aggregate.py, tests/extras/test_aggregate.py
For all 1D and 2D aggregators, if N/A is present in one of the columns, the row goes to a special N/A bin, that at the end becomes zero bin. An exemplar for this bin is just the first row that contains even one N/A value.
Tests are updated according to the above changes.
Closes #1337
=> Do proper N/A handling in 1D and 2D

c/datatablemodule.cc, c/datatablemodule.h, c/options.cc, c/options.h, datatable/__init__.py, datatable/frame.py, datatable/fread.py, datatable/options.py, tests/test_dt_options.py
Each dt.option now returns a proxy object that is derived from its base type, but also has the correct doc string. This allows the user to query the description of each option from python, for example:
```
In [1]: ?dt.options.frame.names_auto_index
Type:        int
String form: 0
File:        ~/py36/lib/python3.6/site-packages/datatable/options.py
Docstring:   When Frame needs to auto-name columns, they will be assigned names C0, C1, C2, ... by default. This option allows you to control the starting index in this sequence. For example, setting options.frame.names_auto_index=1 will cause the columns to be named C1, C2, C3, ...
```
In addition, each options namespace now displays the list of all options inside it:
```
In [2]: dt.options.frame
Out[2]: dt.options.frame.
names_auto_index = 0 …
```
=> Make sure that help on dt.options is available from Python

c/extras/aggregator.cc, c/extras/aggregator.h, datatable/extras/aggregate.py, tests/extras/test_aggregate.py
For 1D and 2D categorical aggregators we may end up with too many exemplars being returned, because binning for categoricals is essentially based on `datatable` grouping. Also, for ND aggregator, when there are no continuous columns, all rows are becoming exemplars, that may be too much for `vis-data-server` if a data set is large. 
One of the options to reduce number of returned exemplars is to do sampling and return `n_bins` random exemplars for 1D, `nx_bins * ny_bins` random exemplars for 2D and `nd_max_bins` random exemplars for ND aggregator.
Closes #1345
=> Do random sampling for categorical data sets in aggregator

CHANGELOG.md, datatable/frame.py, tests/test_dt_sort.py
All of the following now work as expected:
```
df.sort()
df.sort("A")
df.sort("A", "B")
df.sort(["A", "B"])
```
Closes #1354
=> Make Frame.sort() work when no arguments provided

c/frame/py_frame.cc, c/python/args.h, ci/setup_utils.py, tests/__init__.py, tests/fread/test_fread_small.py, tests/munging/test_dt_cols.py, tests/munging/test_dt_rows.py, tests/test_dt_expr.py
With this PR I was able to install `datatable` on a clean Mac after merely doing `brew install llvm` (i.e. no need to download Clang/Llvm manually, or set up any environment variables).
Additional changes:
* Fixed few warnings / errors emitted in Clang7;
* Tests that test the "llvm" execution engine are now optional: if llvm is not detected on a system, the tests will be skipped instead of failing;
* In addition to `LLVM4`, `LLVM5`, `LLVM6` environment variables, also check `LLVM` and `LLVM7`.
=> Make installing on a machine without Llvm/Clang easier.

c/csv/reader.cc, c/csv/reader_fread.cc, c/expr/binaryop.cc, c/jay/open_jay.cc, c/memrange.cc, c/options.cc, c/python/args.cc, c/python/args.h, c/python/ext_module.h, c/sort.cc, c/stats.cc, c/str/py_str.cc, c/str/split_into_nhot.cc, c/types.h, c/utils/parallel.h, c/utils/shared_mutex.h, ci/setup_utils.py, setup.py, tests/fread/test_fread_large.py
This PR tweaks certain compiler/linker flags, as well as fixes few compilation errors (that inexplicably are perfectly fine with Clang, not even a warning raised). 
The biggest change to code structure is that now python module-level functions are declared using a macro rather than a template. Even though this strays away from C++ ideals, the macro-based solution turns out to be cleaner and the code smaller. In addition, the function's signature is now defined together with the function itself, which makes the code more coherent.
The `setup.py` now does the work for setting up a compiler only when it detects a command that will cause an extension to be built.
With this PR I was able to build `datatable` on Ubuntu 18.04 without downloading Clang/Llvm. The build steps were the following:
1. …
=> Allow datatable to be compiled with gcc on linux

datatable/types.py
```
>>> dt.float64.min
-1.7976931348623157e+308
>>> dt.bool8.max
1
```
Non-numeric stypes return `None`
=> Add extrema properties to stypes

CHANGELOG.md, datatable/expr/base_expr.py, datatable/expr/column_expr.py, tests/test_dt_expr.py
- a `ColSelectorExpr` will now retain its original (unresolved) column selector, allowing the same selector to be applied to a different Frame the next time;
- the `ColSelectorExpr.__str__()` now reflects the selector that was used originally, rather than the resolved one. This means the `repr()` of such expression will not change after each invocation;
- the repr now looks more similar to how the expression is entered.
Closes #1366
=> Allow f-expressions to be reused without errors

c/columnset.cc, c/csv/reader.cc, c/datatable.cc, c/datatable.h, c/datatable_load.cc, c/datatable_rbind.cc, c/extras/aggregator.cc, c/frame/cbind.cc, c/frame/names.cc, c/frame/py_frame_init.cc, c/jay/open_jay.cc, c/py_columnset.cc, c/py_datatable.cc
* The `Column**` array was a relic from the old C times. At last, it is replaced with a proper container.
* Added default constructor `DataTable()` to create an empty Frame.
This currently generates a lot of warning about `int64_t` to `size_t` conversion. These warnings will be fixed in another PR.
Closes #1377
=> Replace Column** with std::vector<Column*> in DataTable

CHANGELOG.md, c/datatablemodule.cc, c/datatablemodule.h, c/expr/py_expr.h, c/expr/reduceop.cc, c/set_funcs.cc, datatable/__init__.py, datatable/expr/column_expr.py, datatable/frame.py, tests/test_sets.py
Add new set-theoretic functions:
- `union()`,
- `intersect()`,
- `setdiff()`,
- `symdiff()`.
Each function can take arbitrary number of single-column frames, e.g. `union(fr1, fr2, fr3, fr4)`. Column types can be different, in which case they will be upcasted to the smallest common supertype. 
In addition, added function `unique()`, which returns the union of all columns in a single Frame. Also, `Frame.to_list()`, `Frame.to_pandas()`, `Frame.to_numpy()` were added as synonyms for.topython(), .topandas() and .tonumpy().
Closes #1356
=> Set functions

CHANGELOG.md, c/datatable.cc, c/datatable.h, c/frame/key.cc, c/frame/names.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/py_datatable.cc, c/py_datatable.h, c/py_datawindow.cc, datatable/frame.py, tests/test_dt.py, tests/test_join.py, tests/test_keys.py, tests/test_nff.py
A Frame can now have a multi-column key, for example:
```
frame.key = ("A", "B")
```
Closes #1376
=> Added support for multi-column keys

CHANGELOG.md, c/frame/getset.cc, c/frame/names.cc, c/jay/save_jay.cc, c/utils/exceptions.cc, c/utils/exceptions.h, datatable/nff.py, tests/fread/test_fread_detect.py, tests/munging/test_assign.py, tests/munging/test_dt_cols.py, tests/munging/test_replace.py, tests/test_dt.py, tests/test_dt_create.py, tests/test_dt_sort.py, tests/test_nff.py
As outlined in #1395, syntax `DT[col]` will now be deprecated. Please use `DT[:, col]` instead.
Starting from 0.9.0, `DT[x]` will be interpreted as row-selector instead. For example, `DT[:5]` will be the first 5 rows of the Frame, and `DT["A"]` will return the row keyed by the value "A". 
Closes #1395 
Closes #1406
=> Deprecate DT[col]

CHANGELOG.md, c/datatablemodule.cc, c/datatablemodule.h, c/frame/getset.cc, c/frame/join.cc, c/rowindex_array.cc, c/ztest.cc, c/ztest.h, datatable/graph/join_node.py, tests/test_dt.py, tests/test_join.py
Implement (natural) join on multiple columns. The join frame should be keyed on multiple columns, and then the syntax for the join is exactly the same as before:
```
DT1[:, :, join(DT2)]
```
The columns being joined can have different stypes, except that the join of integers/floats to string columns is not allowed.
Additional changes:
- internal C++ tests must now be invoked explicitly, rather than running automatically at startup. This makes it easier to set up breakpoints in lldb;
- fixed typo in error message in getset.cc;
- fixed bug in rowindex_array, when the array contained only NA values.
Closes #1353
=> Multi-column join

requirements_docs.txt
Our build process requires `sphinx` of version 1.8 or higher. Adding a requirements file so that readthedocs site can be configured to use the correct version of the library.
=> Add requirements_docs.txt

c/sort.cc
The `sort` function now always returns an array rowindex, never a SliceRowindex.
Closes #1414
=> Fix crash in test_setfns_random

CHANGELOG.md, datatable/nff.py, tests/munging/test_dt_append.py, tests/munging/test_dt_rows.py, tests/test_nff.py
This change is motivated by the fact that "NFF" format is now deprecated, so it makes no sense to keep it as the default. After this change, saving frames will be as easy as
```
frame.save("out.jay")
```
Closes #1422
=> The default format in Frame.save is now 'jay'

c/frame/_repr_html_.cc, docs/_static/code.css, docs/conf.py, docs/frame.rst, docs/using-datatable.rst
- The styling of Frame display in docs is now the same as in Jupyter;
- Row numbers are now displayed comma-separated;
- Comma-separation is not applied to numbers in the range 1000-9999.
Closes #1426
=> Fix Frame rendering style in docs

CHANGELOG.md, c/frame/_repr_html_.cc, c/types.cc, c/types.h, docs/_static/code.css, docs/using-datatable.rst
In Jupyter, we now display an extra row under the column names, carrying indicators of column types. This row is designed to be unobtrusive: only 6px in height, the color of each cell corresponds to the logical type of the column (int -> green, float -> blue, string -> red, bool -> yellow, object -> black), and the number of dots in the cell shows the element size (1 dot = 8 bit, 2 dots = 16 bits, 4 dots = 32 bits, 8 dots = 64 bits).
In addition, this PR fixes display of "obj" columns (previously they were not rendering at all).
This is how it now looks like:
Closes #1428
Closes #1430
=> Add column type indicators in Jupyter

CHANGELOG.md, c/frame/py_frame.cc, c/frame/py_frame.h, c/python/arg.cc, c/python/arg.h, c/python/args.cc, c/python/orange.cc, c/python/orange.h, tests/test_dt.py
=> Add methods Frame.head() and Frame.tail()

CHANGELOG.md, c/datatable.cc, c/datatable.h, c/frame/key.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/py_frame_init.cc, c/jay/open_jay.cc, c/jay/save_jay.cc, c/memrange.cc, c/memrange.h, c/py_datatable.cc, datatable/frame.py, datatable/nff.py, tests/test_dt.py, tests/test_nff.py
- Frame now supports pickle interface;
- when copying a Frame, its key property is no longer lost;
- `Frame.save()` can now also be called without any arguments -- it will save the Frame into memory in Jay format, and return the bytes object containing the Frame's data;
- `dt.open()` can now accept a bytes argument -- same as returned from `Frame.save()`. 
Closes #1442 
Closes #1443
=> Pickling of Frames

c/jay/open_jay.cc
Make sure that when Frame is opened from a bytes object (such as during un-pickling), it would remain valid even after the bytes object disappears.
Closes #1442
=> Fix bug when pickling a Frame

c/extras/aggregator.cc
`map` was allocated but never deleted
=> Avoid memory leak in Aggregator::adjust_members

CHANGELOG.md, MANIFEST.in, ci/setup_utils.py
- File `ci/setup_utils.py` is no longer omitted from the sdist;
- Installing from sdist no longer requires generating the `__git__.py` file.
Closes #1451
=> Fixed installation from source distribution

c/datatablemodule.cc, c/expr/base_expr.cc, c/expr/base_expr.h, c/expr/binaryop.cc, c/expr/py_expr.cc, c/expr/py_expr.h, c/python/ext_type.h, datatable/expr/base_expr.py, datatable/expr/binary_expr.py, datatable/expr/column_expr.py, datatable/expr/consts.py, datatable/expr/literal_expr.py, datatable/expr/relop_expr.py, datatable/graph/dtproxy.py
This class will allow us to evaluate `DT[i, j, ...]` expressions from C++.
This is mostly work-in-progress for now, we'll need the rest of the evaluation infrastructure to make use of this new class.
=> Initial implementation of core.base_expr class

c/extras/dt_ftrl.h, c/extras/py_ftrl.cc, c/extras/py_ftrl.h, c/python/_all.h, c/python/namedtuple.cc, c/python/namedtuple.h, tests/extras/test_ftrl.py
- prefer C++ `using` instead of `typedef`;
- fixed docstring of parameter `lambda2`;
- use `std::string`s instead of `const char*` for namedtuple construction;
- rename `Params` -> `FtrlParams`;
- defer creation of `FtrlParams` named tuple type until it is actually needed;
- add another constructor for `onamedtuple`, without the docstrings;
- add copy/move constructor for `onamedtuple` and `onamedtupletype`.
=> namedtuple API adjustments

c/extras/dt_ftrl.cc, c/extras/dt_ftrl.h, c/extras/py_ftrl.cc, c/extras/py_ftrl.h, datatable/models.py, tests/extras/test_aggregate.py, tests/extras/test_ftrl.py
- make `Ftrl` class to be a part of `datatable.models`;
- add support for pickling `Ftrl` objects that contain the both parameters and the model. Since namedtuples cannot be easily pickled, we pickle parameters as a normal tuple adding internal methods to get/set a normal tuple of parameters. These getters and setters are not exposed to the user;
- add `w` weight initialization in the model setter, otherwise it would not possible to fit / predict after unpickling;
- add the corresponding tests;
- minor cleaning and refactoring.
Closes #1476
=> Add support for pickling Ftrl objects

c/expr/i_node.cc, tests/munging/test_dt_rows.py
Hold on to a reference to `py::Frame` in `frame_in` class. Otherwise, the Frame object gets destroyed too early, causing a seg.fault during the evaluation.
Closes #1487
=> Fix issue 1487

c/extras/dt_ftrl.cc, c/extras/dt_ftrl.h
Transform some of the formulas in FTRL model to avoid unnecessary branching (and thus improve performance). The C functions such as `log`, `exp`, `fabs` were replaced with their C++ equivalents:
`std::log`, `std::expr`, `std::abs`, etc.
=> Simplify formulas in Ftrl

tests/extras/test_ftrl.py
Adjust feature importance test to make importance difference more significant, so that there is less chances this test is affected by hogwild.
=> Adjust feature importance test for FTRL

c/expr/i_node.cc, c/expr/j_node.cc, c/expr/j_node.h, c/rowindex_array.cc, ci/llvm-gcov.sh, datatable/expr/mean_expr.py, datatable/expr/minmax_expr.py, datatable/expr/sd_expr.py, tests/munging/test_dt_rows.py
- Many tests in `test_dt_rows.py` used old-fashioned style `DT(rows=...)` of selecting elements from a Frame. Consequently, those tests were not running for the new-style selectors `DT[i, j]` expressions. As a result, several bugs were inadvertently introduced during the latest round of refactoring, as the tests effectively ignored the new code. This PR addresses this issue, and transforms all tests in `test_dt_rows.py` into the "new-style" selectors of the form `DT[i, j]`. Eventually the old-style calling method `DT(...)` will be deprecated and later removed.
- After the tests were enabled, few more bugs were discovered and fixed, in particular bugs involving "multislice" `i` selectors;
- Fixed coverage script `llvm-gcov.sh`;
- Handle correctly all reducer nodes, including sd, min, max …
=> Improve test coverage for i_node.cc

c/extras/dt_ftrl.cc, tests/extras/test_ftrl.py
It seems that `None` targets were automatically converted to `True`, due to the fact we never tested  if they're `None` or not. For datasets having a lot of `None` targets, this results in the model being trained on the possibly wrong data.
Fix it, so that we simply do not train our model if a target is `None`. Add a relevant test.
=> Do not train FTRL model on rows where target is None

CHANGELOG.md, c/expr/i_node.cc, c/expr/j_node.cc, c/python/dict.cc, c/python/dict.h, c/python/obj.cc, c/python/obj.h, c/types.cc, c/types.h, tests/munging/test_dt_cols.py
- Added support for selecting columns via a list of booleans (the length of the list must be the same as the number of columns in the Frame);
- refactor j_node constructor to avoid code duplication;
- implemented creating j_node from a list of slices;
- implemented creating j_node from a type / stype / ltype;
- implemented creating j_node from a dictionary;
- added methods `_obj::is_bytes()`, `_obj::is_type()`, `_obj::is_stype()`, `_obj::is_ltype()`; `_obj::get_iter()`;
- significantly improved code coverage of j selectors;
- `py::odict` object now uses a high-level iterator interface in Python3.5. This is needed so that when an `OrderedDict` is passed instead of a regular dict, the iteration would occur in proper order.
WIP for #1477
=> j-node improvement

CHANGELOG.md, c/str/split_into_nhot.cc, tests/munging/test_str.py
Function `dt.split_into_nhot(frame)` now works correctly when `frame` is a view.
Closes #1507
=> Fix split_into_nhot() when applied to a view

c/datatable.h, c/datatablemodule.cc, c/expr/by_node.cc, c/expr/by_node.h, c/expr/i_node.cc, c/expr/i_node.h, c/expr/j_node.cc, c/expr/join_node.cc, c/expr/workframe.cc, c/expr/workframe.h, c/frame/__getitem__.cc, c/frame/join.cc, c/frame/py_frame.h, c/python/obj.cc, c/python/obj.h, datatable/graph/__init__.py, datatable/graph/groupby_node.py, tests/munging/test_dt_rows.py, tests/test_dt.py, tests/test_groups.py, tests/test_join.py
- (Select) joins are now computed in C++ entirely;
- Error message from invalid joins now includes the names of the mismatched columns;
- Fix bug in joins where bool columns could not be joined to others;
- `i_node` is now constructed in C++ always, without fall-back into python;
- The `by()` function is now declared in C++, in preparation for moving this functionality away from python into the core;
- class `SimpleGroupbyNode` in python removed;
WIP for #1477
=> Joins refactor

setup.py
Llvmlite is now an optional dependency, so it shouldn't be listed as required.
This change should help resolve recent errors with PPC64le build.
=> Disable llvmlite dependency

CHANGELOG.md, ci/README.md
For comparison:
- old URL: https://github.com/h2oai/datatable/compare/HEAD...v0.7.0
- new URL: https://github.com/h2oai/datatable/compare/v0.7.0...HEAD
=> Changelog URLs

CHANGELOG.md, c/column_string.cc, c/rowindex.cc, c/rowindex.h, tests/munging/test_assign.py
This PR makes it possible to modify a string column in-place, via expression `DT[i, j] = ...`. The expression itself was implemented long time ago; but now it also works when applied to string columns.
Closes #1523
=> Implement updating values within string columns

CHANGELOG.md, c/frame/replace.cc, tests/munging/test_replace.py
=> Avoid crashing when getting less than 2 arguments in Frame.replace()

CHANGELOG.md, c/datatable.h, c/expr/by_node.cc, c/sort.cc, tests/test_groups.py
Added new internal method `DataTable::group(spec, as_view) -> pair<RowIndex, Groupby>`, as a replacement for `DataTable::sortby()`. The new method has more predictable return value: the returned rowindex either applies to the column, or to its source (for a view column), depending on the value of the parameter `as_view`.
Closes #1542
=> Fix groupby when applied to a view

CHANGELOG.md, c/expr/workframe.cc, c/py_datatable.cc, tests/munging/test_assign.py, tests/munging/test_dt_cols.py
- When 0 columns are selected from a Frame, we now return the result with same number of rows as if some columns were selected;
- During assignment to a 0 column selection, the replacement Frame can now be 0x0.
Closes #1544
=> Fix selecting and assigning to a 0-column subset

CHANGELOG.md, c/frame/join.cc, tests/test_join.py
The fix is currently partial: we materialize the left frame before join. In the future (after #1188) we could do better and work with view frame directly.
Closes #1540
=> Fix join applied to a view frame

c/extras/aggregator.cc, c/extras/aggregator.h
When exemplars are traversed in the order they appear in the `exemplars` vector, first exemplars will always have a priority over the last ones, hence, first exemplars "absorb" most of the members. In this case one can not distinguish real outliers with the exemplars (the last ones) that just had no chances to get some members.
One of the ways to fix it is to traverse exemplars in a random order, so that each exemplar gets the "same" chances to "absorb" a particular member. Here we use modular arithmetic to traverse exemplars in quasi-random order, as this approach seems to have negligible overhead, when comparing to `std::random_shuffle`, and we do not really need to be fully random, but just different enough to not inflate some particular exemplars.
=> Traverse exemplars in a quasi-random order in ND aggregator

c/extras/py_ftrl.cc, c/extras/py_ftrl.h
As `py::Ftrl` class is managed by Python, `m__dealloc` should deallocate all the resources. Implement it to prevent memory leaks.
Could help to fix https://github.com/h2oai/h2oai/issues/6633 and https://github.com/h2oai/h2oai/issues/6514
=> Implement `m__dealloc__` to delete models and labels

CHANGELOG.md, c/expr/binaryop.cc, tests/test_dt_expr.py
The issue was that the logic for correcting integer division (offsetting by -1 when dividing a negative number by a positive) was incorrectly applied for true division as well.
Closes #1562
=> Fix a bug in true division of integers

CHANGELOG.md, tests/munging/test_assign.py
When a column is set to `None`, its stype will now be preserved.
The necessary change was introduced in #1561, this PR merely adds tests.
Closes #1555
=> Add tests for setting column to NA

CHANGELOG.md, c/expr/base_expr.cc, c/expr/base_expr.h, c/expr/unaryop.cc, datatable/__init__.py, datatable/expr/__init__.py, datatable/expr/consts.py, datatable/expr/exp_expr.py, tests/test_dt_expr.py
Add functions `dt.log()` and `dt.log10()`. For example:
```
>>> import datatable as dt
>>> X = dt.Frame([1, 2, 3])
>>> X[:, dt.log(dt.f[0])]
C0
---  --------
0   0       
1   0.693147
2   1.09861 
[3 rows x 1 column]
```
Closes #1558
=> Implement the logarithms functions

CHANGELOG.md, ci/setup_utils.py, setup.py
This PR augments the existing `CCompiler` class used by `setup.py`, such that after the usual link stage a "post-link" action is executed. In this post-link step we do the following:
- Check the LOAD_DYLIB entries in the _datatable.so library, using `otool -L`;
- Verify that only standard system entries (`/usr/lib/*`) or local dynamic libraries (`@rpath/*`) are present;
- If not, the entries are fixed up using the `name_install_tool -change`;
- Verify that all referenced local dylibs (`@rpath/*`) are actually present in the `datatable/lib/` directory.
This change affects MacOS only. In principle, similar process can be applied on Linux platform as well.
Here's the output example from this process:
```
Post-link processing
Output file: …
```
=> Implement post-link fix-up of the built executable on MacOS

CHANGELOG.md, tests/munging/test_assign.py
The fix itself was introduced in #1561, this merely adds the relevant tests.
Closes #1539.
=> Fix assignment DT[i,j] = list-of-exprs

c/column.cc, c/expr/repl_node.cc, c/frame/repeat.cc, tests/munging/test_assign.py
Implement column upcasting when assigning a value which would otherwise not fit into the given stype.
This also fixes a couple of other bugs:
- `repeat(0)` was causing a crash;
- partial column assignment was creating a column of VOID stype;
Closes #1554
=> Added many tests for DT[i,j]=... assignment

CHANGELOG.md, c/expr/base_expr.cc, c/expr/base_expr.h, c/expr/workframe.cc, c/expr/workframe.h, tests/test_groups.py
The products of rowindexes were memoized incorrectly, this is now fixed.
In addition, implemented a TODO note in `expr_column` class, which now uses rowindex product memoization too.
Closes #1578
=> Fix a bug when mixing computed & regular columns (with groupby)

CHANGELOG.md, c/expr/i_node.cc, c/expr/i_node.h, c/expr/workframe.cc, c/expr/workframe.h, tests/__init__.py, tests/munging/test_dt_rows.py, tests/test_groups.py
This PR allows the syntax such as
```
DT[:5, :, by("id")]
```
to select the first 5 rows for each group when the frame is grouped by the "id" column.
Slices with positive, negative, and zero step are supported.
Closes #1585
=> slice-valued i expression, combined with a groupby

c/extras/py_ftrl.cc, tests/extras/test_ftrl.py
Due to Hogwild approach some of the FTRL tests may fail for a given thread competition scenario. Trying to adjust number of bins, feature names and values to make their importances order of magnitude different, so that tests are less prone to Hogwild.
=> Adjust FTRL feature importance tests

CHANGELOG.md, c/expr/base_expr.cc, c/expr/base_expr.h, c/expr/by_node.cc, c/expr/by_node.h, c/expr/workframe.cc, c/sort.cc, c/sort.h, c/sort_groups.cc, c/sort_insert.cc, tests/test_dt_sort.py
This PR implements sorting in reverse order. The functionality is achieved by adjusting the procedure for data extraction (i.e. conversion of source data into unsigned ints needed by the radix sort algorithm). As such, there should be no difference in run time of ascending / descending sorting.
The API is the following:
```
DT[:, :, sort(-f.A)]
```
Closes #792
=> Sort in reverse order

CHANGELOG.md, c/expr/i_node.cc, c/rowindex_array.cc, c/rowindex_impl.h, c/rowindex_slice.cc, c/set_funcs.cc, tests/munging/test_dt_rows.py, tests/random_attack.py
- Clarify calculation of min/max in `ArrayRowIndexImpl` for the case when all entries are NAs;
- Run `verify_integrity` on ArrayRowIndexImpl upon construction (but only in debug mode);
- Fixed an issue with set_funcs where they created `ArrayRowIndex`es incorrectly marked as sorted.
- Fixed "grouped slice" operation which created an `ArrayRowIndex` incorrectly marked as sorted if the step was negative.
Closes #1592
=> Fix min/max calculation in ArrayRowIndex

CHANGELOG.md, c/frame/__init__.cc, c/python/iter.cc
The latest version of pandas (0.24.0, released Jan 25) removed `__length_hint__` property from its `DataFrame.columns` iterator. Unfortunately, our code did not account for this method being missing, and was throwing an exception inside a "noexcept" function. This has now been fixed.
Closes #1600
=> Fixed crash with pandas 0.24

c/extras/py_ftrl.cc, tests/extras/test_ftrl.py
`Ftrl()` object has an empty model, feature importances and feature names fields. This is now properly checked during pickling/unpickling to prevent segfaults. Several relevant tests have also been added.
Closes #1597
=> Do not segfault when pickling an empty FTRL model

CHANGELOG.md, c/api.cc, c/datatable.cc, c/datatable.h, c/datatablemodule.cc, c/frame/cbind.cc, c/frame/join.cc, c/frame/key.cc, c/py_buffers.cc, c/py_columnset.cc, c/py_datatable.cc, c/py_datatable.h, c/py_rowindex.cc, c/py_rowindex.h, c/sort.cc, datatable/frame.py, datatable/include/datatable.h, datatable/internal.py, tests/extras/test_aggregate.py, tests/munging/test_dt_cbind.py, tests/munging/test_dt_combo.py, tests/munging/test_dt_rows.py, tests/test_dt.py
This PR is the final step in implementing #1188: to allow each Column in a Frame to have its own distinct RowIndex. This allows us to: 
- cbind frames that have different rowindices without materializing individual columns;
- perform joins without materializing the resulting frame;
- Select filtered columns alongside the computed ones in `DT[i, j, ...]` expression.
Additional changes:
- Removed deprecated C API functions `datatable_get_column_data`, `datatable_unpack_slicerowindex`, `datatable_unpack_arrayrowindex` which are no longer used;
- `DataTable::rowindex` property was removed;
- Removed obsolete function `_datatable.get_internal_function_ptrs()`;
- Added function `datatable.internal.get_rowindex(frame, i)`;
- Removed `Frame.internal.rowindex` and `Frame.internal.rowindex_type`;
- …
=> Multiple rowindexes per Frame

c/extras/aggregator.cc, c/extras/aggregator.h, docs/ftrl.rst, tests/extras/test_aggregate.py
- use `group` instead of `sortby` for sorting/grouping;
- make use of two-column grouping in `group_2d_categorical_str`;
- adjust `test_aggregate_2d_categorical_unsorted` test as we now sort by the first column first, then by the second one;
- use RowIndex `operator[]`, instead of RowIndex indices;
- minor changes to FTRL documentation.
Closes #1434
=> Refactor sorting/grouping and RowIndex usage in Aggregator

CHANGELOG.md, c/expr/reduceop.cc, datatable/expr/minmax_expr.py, tests/test_reduce.py
This PR changes the behavior of functions `max()` and `min()` when they are applied to empty or all-NA columns. Previously those functions returned `-Inf` and `+Inf` respectively (or, for integer columns, `-MAX` and `+MAX`). Now these functions will return `None`.
The reasons for the change are discussed in #1624, but in summary they are:
- in mathematics max and min of an empty set do not exist, only supremum and infimum;
- for integers returning a large integer looks like a bug, and we prefer the behavior of floats to match the behavior of integers;
- numpy returns nan for max/min of array of nans (with a warning);
- R returns NA for max/min of a vector of NAs (however, it returns ±∞ if option `na.rm=TRUE` is used).
Closes #1624
=> max/min for an empty column now returns None

c/extras/hash.cc, c/extras/hash.h, c/extras/py_ftrl.cc, c/sort_insert.cc, docs/ftrl.rst, tests/extras/test_ftrl.py
- move hashing functionality from `hash.h` to `hash.cc`;
- fix `nbins` setter bug that lead to segfault, when the model was already trained;
- add a relevant test to ensure that only untrained models allow for `nbins` change;
- update docs to explicitly say what datatypes are supported by FTRL algo. 
Closes #1631
=> Move hashing functionality from header to source file, fix `nbins` setter bug, add a test

c/frame/_repr_html_.cc
The style for `tr.coltypes` expects only `<TD>` elements, so the presence of a `<TH>` was making the row rendered incorrectly.
=> Minor fix to rendered HTML table

tests/extras/test_ftrl.py
With the hogwild approach some of the tests may become unstable, when there are many threads modifying the same model weights. Here we Increase number of rows and adjust data to have a larger spread in the feature importances.
=> Fix feature importance FTRL tests

c/api.cc, c/datatablemodule.cc, c/frame/join.cc, c/py_column.cc, c/py_column.h, c/py_rowindex.cc, c/py_rowindex.h, c/python/obj.cc, c/python/obj.h, tests/extras/test_aggregate.py, tests/test_dt.py
- `py::RowIndex` class was converted into the new format based on `ExtType`. This makes the code cleaner, and also helps to eventually remove "py_utils.h" (which is a blocker for #1369).
- Remove methods `core.rowindex_from_*()`
- Remove method `core.natural_join()`
WIP for #1066
WIP for #1369
=> Convert pyRowindex class into new-style (based on ExtType)

c/extras/aggregator.cc
Since `std::default_random_engine` may not be thread safe, and projection matrix is normally pretty small in terms of dimensions, it may have no sense to parallelize `Aggregator::generate_pmatrix`  method. Disable parallelization as it could be one of the reasons why `test_aggregate_nd_projection` test segfaults on machines with many cores.
=> Disable parallelization `Aggregator::generate_pmatrix`

CHANGELOG.md, c/column.cc, c/column.h, c/column_fw.cc, c/column_string.cc, c/datatablemodule.cc, c/datatablemodule.h, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/to_numpy.cc, c/py_buffers.cc, c/py_datatable.cc, c/py_datatable.h, c/python/obj.cc, c/python/obj.h, c/utils/exceptions.cc, c/utils/exceptions.h, datatable/frame.py, tests/test_dt.py
`Frame.to_numpy()` method now returns a `numpy.ma.masked_array` if the underlying frame had any NA values. This works for all stypes, not just boolean.
Closes #1619
=> .to_numpy() for frames with NA values

CHANGELOG.md, c/datatablemodule.cc, c/datatablemodule.h, c/extras/kfold.cc, datatable/models.py, tests/__init__.py, tests/models/test_kfold.py
Added function `dt.models.kfold(nrows, nsplits)` to prepare indices for k-fold splitting. This function will return `nsplits` pairs of row selectors such that when these selectors are applied to an `nrows` frame, that frame will be split into train and test part according to the K-fold splitting scheme.
More specifically, the documentation for method `kfold` is the following:
```
kfold(nrows, nsplits)
--
Perform k-fold split of data with `nrows` rows into `nsplits` train/test
subsets.
This function will return a list of `nsplits` tuples `(train_rows, test_rows)`,
where each component of the tuple is a rows selector that can be applied to a
frame with `nrows` rows. Some of these row selectors will be simple python
ranges, others will be single-column Frame objects.
The range `[0; nrows)` …
```
=> Kfold splitting

c/frame/py_frame.cc, c/frame/py_frame.h, c/python/arg.cc, c/python/arg.h, c/python/args.cc, c/python/args.h, c/python/ext_type.h
Adding new macro `ADD_METHOD(mm, method, args);`, which should eventually replace all the existing template functions `mm.add<...>()`. I hope that the new approach will be more robust than the current (in particular, less chances of compiler errors). In addition, it is conceptually simpler and produces smaller code footprint than the current approach. Also, the `args` variable can now be declared statically in a file, there is no need to define it in the class.
This PR only converts 2 methods `Frame.head()` and `Frame.tail()` to the new approach, as a "test-drive". A subsequent PR will take care to convert all the existing usages.
=> Create mechanism for defining python interface methods more robustly

c/extras/py_ftrl.cc, c/extras/py_ftrl.h, c/py_rowindex.cc, c/py_rowindex.h, c/python/ext_type.h
Convert all code to use new `ADD_METHOD` macro; remove old templates `Methods::add<...>`. As a consequence, the `ExtType<T>::Methods` class is now much simpler.
The purpose of this refactoring is that complicated templates are not always compiled reliably by all compilers, which causes problems such as #1369. By switching to much simpler macros, these problems should be largely alleviated.
=> Simplify ExtType<T>::Methods class

c/expr/by_node.cc, c/expr/join_node.cc, c/expr/sort_node.cc, c/extras/py_ftrl.cc, c/frame/key.cc, c/frame/names.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/py_rowindex.cc, c/python/args.h, c/python/ext_type.h
This PR changes changes the way getters / setters are declared, similar to #1657.
Now in order to declare a getter [+setter], you have to create a static `GSArgs` variable (similar to `PKArgs` for methods). This variable only carries the name of the property and its docstring. The advantage of the new approach is that now the documentation for a property can be declared right next to the property itself, which is a big plus.
In addition, the amount of generated code is now smaller, and we don't use templates as heavily. Instead, there are now 2 macros:
```
ADD_GETTER(gs, &Class::getterfn, args);
ADD_GETSET(gs, &Class::getterfn, &Class::setterfn, args);
```
=> Getters / setters revamp

c/datatablemodule.cc, c/datatablemodule.h, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/to_numpy.cc, c/py_buffers.cc, c/py_datatable.cc, c/py_datatable.h, c/python/arg.cc, c/python/arg.h, c/python/args.h, datatable/frame.py
Conversion was made slightly more efficient: now we don't need to select an individual column via `self[:, i]`, but instead the operation is controlled via a global parameter `pybuffers::single_col`. The numpy arrays returned from this are already 1D, so no need to apply `.ravel()` afterwards either.
WIP for #1066
=>  Convert Frame.to_pandas() into C++

c/models/aggregator.cc
Make `aggregate(...)` signature be consistent with the aggregator functionality.
=> Fix `aggregate(...)` signature in help

CHANGELOG.md, c/options.cc, c/options.h, c/python/bool.cc, c/python/bool.h, datatable/frame.py, datatable/utils/terminal.py, datatable/widget.py, tests/test_dt.py, tests/test_dt_options.py
- Added option `dt.options.display.interactive` to control whether Frames will be displayed in interactive mode in a console or not.
- The default value of `dt.options.display.interactive` changed to `False`.
- Added a helper class `py::obool`.
Closes #1668
=> Add option to display a Frame interactively

c/column_fw.cc, c/column_pyobj.cc, c/column_string.cc, c/datatable.h, c/frame/cbind.cc, c/py_rowindex.cc, tests/munging/test_dt_cbind.py
- When cbinding different frames, their columns will no longer be materialized (owing to the fact that now we support having multiple columns with different rowindices in the same frame).
- The columns will still be materialized though if we need to change their shape due to the `force=True` flag.
- fixed minor bug in `__repr__` of `dt.internal.RowIndex` class when displaying a slice rowindex with negative step.
Closes #1674
=> Cbind without materialization

CHANGELOG.md, datatable/frame.py, datatable/utils/terminal.py, datatable/widget.py, tests/test_dt.py, tests/test_dt_create.py
This PR fixes a bug where the key columns were not displayed quite right during scrolling in a console widget. Now they have proper appearance of "frozen" columns (similar to Excel).
In addition, `Frame._data_viewer()` method is removed; instead there is now a helper class `DatatableFrameConnector` that has the same purpose. The advantage of having it as a separate class is that we could in principle add more classes like this to implement connectors to other data frames as well.
Closes #1672
=> Properly display keyed frame in console view

datatable/csv.py, datatable/fread.py, datatable/utils/terminal.py, datatable/utils/typechecks.py, datatable/widget.py, tests/random_driver.py, tests/test_dt.py
- `MyTerminal` and `NoTerminal` are merged into the single `Terminal` class.
- Certain functions that were provided by `blessed` before are now implemented natively.
- The terminal can now cleanly switch between "colored" and "monochrome" mode.
- The terminal now has a mode to never emit special terminal code sequences (useful for testing).
- The terminal now has a mode to ignore the `wait_for_keypresses()` command
WIP for #1677
=> Refactor Terminal class

c/datatablemodule.cc, c/expr/by_node.cc, c/expr/i_node.cc, c/frame/__init__.cc, c/frame/__repr__.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/to_numpy.cc, c/models/aggregator.h, c/models/kfold.cc, c/models/py_ftrl.cc, c/python/namedtuple.cc, c/python/obj.cc, c/python/range.cc, c/python/tuple.cc, c/python/tuple.h
Added several new constructors for `py::otuple` to simplify the use of method `obj.call()`. Now you can simply say
```
callable_obj.call({arg1, arg2, arg3});
```
=> Simplify the way how otuple constructor can be used

CHANGELOG.md, c/expr/base_expr.cc, c/expr/base_expr.h, c/expr/string_expr.cc, datatable/__init__.py, datatable/expr/base_expr.py, datatable/expr/string_expr.py, tests/munging/test_str.py
Function `col.re_match(pattern)` can be applied to string columns and produce a boolean column indicating whether each string value matches the given pattern or not. The pattern must be either a string, or a compiled regular expression (however, there is no benefit in precompiling it, since we are not using python's code to match the regular expression).
This API is currently tentative, we may want to update it before the next release.
Closes #1684
=> re_match() function

CHANGELOG.md, c/column.cc, c/column.h, c/column_bool.cc, c/column_from_pylist.cc, c/column_int.cc, c/column_pyobj.cc, c/column_real.cc, c/column_string.cc, c/csv/reader.cc, c/expr/repl_node.cc, c/frame/rbind.cc, c/frame/replace.cc, c/frame/stats.cc, c/jay/open_jay.cc, c/py_buffers.cc, c/read/fread/fread_thread_context.cc, c/wstringcol.cc, c/wstringcol.h, tests/munging/test_replace.py
Direct construction of `StringColumn<T>` objects is now prohibited (except for the cases when a blank column is created). Instead, we use `new_string_column()` function which returns either `StringColumn<uint32_t>*` or `StingColumn<uint64_t>*`, whichever is more appropriate. 
This function also takes care of "fixing" the offsets array in case it overflown during the construction. This works provided that no individual string in the column exceeds 2Gb in size.
Closes #1694
=> Prevent overflow when constructing str32 columns

CHANGELOG.md, c/column.cc, c/column.h, c/datatable.cc, c/frame/__sizeof__.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/py_datatable.cc, c/py_datatable.h, c/python/obj.cc, c/python/obj.h, c/rowindex.cc, datatable/frame.py, tests/test_dt.py
- `Frame.__sizeof__()` method is now declared in C++;
- More accurately count different quantities that take up the Frame's memory.
WIP for #1066 
Closes #1697
=> More accurate __sizeof__()

CHANGELOG.md, c/py_rowindex.cc, c/python/obj.cc
This is a very weird bug. The crash occurs in
```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 2.1
frame #0: 0x0000000102b97ca0 _datatable.cpython-36m-darwin.so`py::oobj::~oobj(this=0x0000000102c5d3a0) at obj.cc:145
142 	  return import(mod, sym1).get_attr(sym2);
143 	}
144 	
-> 145 	oobj::~oobj() {
146 	  Py_XDECREF(v);
147 	}
148 	
```
where `this` object is static `py::oobj tArr64` from function `orowindex::pyobject::get_type()`. I have verified that the object has indeed been created before, and that it was in the valid state, that `v`'s ref-count is 1, and that nobody even touched that object since the point of its creation.
Still, the call to `Py_XDECREF` complains that the memory was not allocated.
Also, at the point just before the crash, the stack trace …
=> Avoid using static py::oobj objects in a function

c/column.cc, c/column.h, c/column_fw.cc, c/column_pyobj.cc, c/column_string.cc, c/datatable.cc, c/datatable.h, c/expr/binaryop.cc, c/expr/reduceop.cc, c/expr/unaryop.cc, c/frame/join.cc, c/frame/key.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/rbind.cc, c/jay/save_jay.cc, c/py_buffers.cc, c/py_datatable.cc, c/py_datatable.h, c/rowindex_array.cc, c/set_funcs.cc, c/sort.cc, datatable/frame.py, tests/test_dt.py
- Renamed internal method `.reify()` into `.materialize()`, so that the internal name of the method is consistent with its external usage;
- Added a test and documentation.
WIP for #1066
=>  Frame.materialize() method moved to C++

c/models/column_convertor.h, tests/models/test_aggregate.py
As of #1704, columns with an existing rowindex could be casted. In this PR we also fix aggregator not working properly on views, consisting of numeric columns. Categorical column views were already fixed with #1666.
Closes #1618
=> Make aggregator working on views

requirements_docs.txt
Until #952 is implemented, we cannot have a proper "latest" version of documentation on RTFD.io. What we can do, for now, is to manually update every once in a while the URL of the latest wheel in "requirements_docs.txt".
Also it appears that RTD site has switched to using Python3.7, so we need to update the wheel for that reason as well.
=> Upgrade the wheel URL in requirements_docs.txt

CHANGELOG.md, c/py_buffers.cc, tests/test_dt.py
Now a pandas column containing bools with NAs converts cleanly into a datatable `bool8` column.
Closes #1730
=> Properly convert pandas bool column into datatable

tests/test_dt.py
The issue 1728 does not reproduce on the latest datatable version, but still adding a test case to make sure that it doesn't resurface in the future.
Closes #1728
=> Added a test case for issue 1728

c/utils/parallel.cc
In tests of cast functionality, this improved functionality significantly.
=> Use static schedule in dt::run_parallel()

README.md, c/models/aggregator.cc
Improve performance of ND aggregator by switching to static schedule for the main loop.
=> Use static schedule for ND aggregation

Makefile, c/csv/reader_fread.cc, c/datatable.h, c/expr/base_expr.h, c/expr/binaryop.cc, c/expr/reduce.cc, c/expr/string_expr.cc, c/memrange.h, c/models/dt_ftrl_real.cc, c/models/murmurhash.cc, c/utils/exceptions.cc, c/utils/exceptions.h, c/utils/logger.h, c/utils/macros.h, c/utils/misc.cc, c/writebuf.h, ci/setup_utils.py, setup.py, tests/munging/test_str.py
- centos7 docker image now always uses gcc for compilation;
- `monkey_patch_compiler` is now executed on all platforms, and it attempts to remove compilation flags that are harmful;
- added `FALLTHROUGH` macro which uses either clang or gcc "fallthrough" attribute;
- some warnings ignored;
- move constructor of `Error()` does copying on gcc4.8, since it didn't support moving string streams;
- disabled tests of error messages from bad regular expressions: these messages are compiler-specific;
- setup.py now checks the python version first, to give a reasonable error message if the user accidentally tries to compile datatable under python2.7
=> Fix warnings/errors when compiling with gcc

c/datatablemodule.cc, c/frame/cast.cc, c/frame/replace.cc, c/models/dt_ftrl_real.cc, c/parallel/api.h, c/parallel/thread_pool.cc, c/rowindex.cc, c/utils/parallel.cc, c/utils/parallel.h
Also, changed the signature of `dt::run_parallel()` so that the step is not passed (since it is always 1).
WIP for #1736
=> Reimplement dt::run_parallel using the new thread pool

c/csv/reader_fread.cc, c/csv/reader_fread.h, c/models/column_hasher.cc, c/models/dt_ftrl_real.cc, c/parallel/atomic.h, c/parallel/atomic_test.cc, c/read/fread/fread_thread_context.cc, c/ztest.cc, c/ztest.h, tests/test_dt.py
`std::atomic<double>` is specialized only in C++17, not in C++11. In C++11 there is generic `std::atomic<T>`, but it lacks arithmetic operators, which are very important for our use case. Hence, we implement our own atomic class, which reuses atomic ints at bit level.
WIP for #1736
=> Implement class atomic<double> and atomic<float>

c/models/dt_ftrl.h, c/models/dt_ftrl_real.cc, c/models/dt_ftrl_real.h, c/models/py_ftrl.cc, docs/ftrl.rst, tests/models/test_ftrl.py
FTRL `fit()` method now returns a named tuple `FtrlFitOutput` consisting of `epoch`, the epoch at which training stopped, and the corresponding `loss`.  If no validation dataset is provided, this method returns `FtrlFitOutput(epoch=nepochs, loss=nan)`, where `nepochs` is a number of epochs provided to FTRL constructor.
=> Return loss, when validation dataset is provided to FTRL algo

CHANGELOG.md, c/datatablemodule.cc, c/options.cc, c/parallel/api.h, c/parallel/thread_pool.cc, c/parallel/thread_pool.h, c/parallel/thread_scheduler.cc, tests/test_dt.py
This PR introduces two changes to the thread pool:
1. The threads are now initialized lazily, that is on the first run that they are actually required. For example function `get_thread_ids()` will always cause the threads to spawn, whereas `dt::run_parallel()` may not, if the number of rows is small enough to run single-threadedly.
2. Fixed problems with datatable hanging after the process was forked by an external module such as `multiprocessing`. Now we re-initialize the thread pool in every child process, ensuring that they do not accidentally share mutexes / condition variables / threads. 
Closes #1758 
Closes #1757
=> Correct behavior of thread pool during forking

c/column_fw.cc, c/column_string.cc, c/datatablemodule.cc, c/frame/cast.cc, c/frame/replace.cc, c/models/dt_ftrl_real.cc, c/models/py_ftrl.cc, c/parallel/api.h, c/parallel/atomic_test.cc, c/parallel/thread_pool.cc, c/parallel/thread_pool.h, c/parallel/thread_scheduler.cc, c/parallel/thread_scheduler.h, c/parallel/thread_worker.cc, c/parallel/thread_worker.h, c/rowindex.cc, c/utils/parallel.cc, c/utils/parallel.h
- Renamed `dt::run_once_per_thread()` into `dt::parallel_region()`;
- Renamed `dt::run_parallel()` into `dt::parallel_for_static()`;
- Added function `dt::get_thread_num()`;
- Added `thread_pool::in_master_thread()` and `thread_pool::in_parallel_region()`;
- `dt::parallel_for_static()` can now be used inside a `dt::parallel_region()` call, allowing support for thread-local contexts;
- Parallel loop in `Ftrl::fit()` now uses parallel-for-inside-parallel-region;
- Added optional parameter `min_chunk_size` to `dt::parallel_for_static` to control chunking behavior, default value = 4096.
Closes #1762 
WIP for #1736
=> parallel_for_static nested inside parallel_region

c/parallel/atomic.h, c/parallel/atomic_test.cc, c/rowindex_array.cc
- Add functions `dt::atomic_fetch_min()` and `dt::atomic_fetch_max()`, analogous to `std::atomic_fetch_add()` and similar.
- Use these functions to implement omp min/max reduction in rowindex_array.cc.
Closes #1763 
WIP for #1736
=> Atomic min max

c/expr/reduce.cc, c/expr/string_expr.cc, c/frame/join.cc, c/parallel/parallel_for_test.cc
Replaced `#pragma omp` with `dt::parallel...` constructs in the following files:
- join.cc
- string_expr.cc
- reduce.cc
WIP for #1736
=> Clean up few more cases of `#pragma omp` uses

c/models/aggregator.cc, c/models/aggregator.h, c/models/column_convertor.h, c/models/column_hasher.cc, c/models/column_hasher.h, c/models/dt_ftrl.cc, c/models/dt_ftrl.h, c/models/dt_ftrl_real.cc, c/models/dt_ftrl_real.h, c/models/murmurhash.cc, c/models/py_ftrl.cc, c/models/py_ftrl.h, c/models/py_validator.cc, c/models/py_validator.h, c/models/utils.cc, c/models/utils.h, docs/ftrl.rst, tests/models/test_ftrl.py
Add `mantissa_nbits` parameter to FTRL algo that specifies how many mantissa bits should be used for hashing float values.
=> Add mantissa_nbits parameter to FTRL algo

c/parallel/parallel_for_ordered.cc, c/parallel/spin_mutex.h
`spin_mutex` is a simple mutex class based on an `std::atomic_flag`, which implements "busy waiting" semantics. 
It is useful for protecting small critical sections (up to a few dozen instructions perhaps?).
This PR adds `spin_mutex` for ordered_scheduler.
=> Implement a spin_mutex class

CHANGELOG.md, c/frame/__repr__.cc, c/frame/py_frame.h, c/py_rowindex.cc, c/python/ext_type.h, datatable/utils/terminal.py, datatable/widget.py, tests/test_dt.py
Before this PR, `str(DT)` returned the same expression as repr: 
```
'<Frame [4 rows x 7 columns]>'
```
After this PR, `str(DT)` returns a string containing the preview of values in the frame. This looks like this:
```
'     A   B   C     D   E   F  G    \n--  --  --  --  ----  --  --  -----\n'
' 0   2   1   1   0.1       0  1    \n 1   7   0   1   2         0  2    \n'
' 2   0   0   1  -4         0  hello\n 3   0   1   1   4.4       0  world\n\n'
'[4 rows x 7 columns]\n'
```
which when printed becomes
```
A   B   C     D   E   F  G    
--  --  --  --  ----  --  --  -----
0   2   1   1   0.1       0  1    
1   7   0   1   2         0  2    
2   0   0   1  -4         0  hello
3   0   1   1   4.4       0  world
[4 rows x 7 columns]
```
Closes #1740
=> Add Frame.__str__() method

CHANGELOG.md, c/csv/reader.cc, c/csv/reader.h, c/datatablemodule.cc, c/datatablemodule.h, c/frame/names.cc, c/frame/py_frame.h, c/options.cc, c/options.h, c/parallel/thread_pool.cc, c/parallel/thread_pool.h, c/python/arg.cc, c/python/arg.h, c/sort.cc, c/sort.h, c/utils/fuzzy_match.cc, c/utils/fuzzy_match.h, datatable/frame.py, datatable/fread.py, datatable/options.py, datatable/widget.py, tests/test_options.py
- The declaration of C++-related options moved entirely into C++;
- Added method `dt.options.describe()`, which will print the available options together with their values and descriptions.
- Added `dt.options.context(option=value)`, which can be used in a with-statement to temporarily change the value of one or more options, and then go back to their original values at the end of the with-block.
- Added options `fread.log.escape_unicode` (controls treatment of unicode characters in fread's verbose log); and `display.use_colors` (allows to turn on/off colored output in the console).
- `dt.options` now helps the user when he/she makes a typo: if an option with a certain name does not exist, the error message will suggest the correct spelling.
Closes #1792
=> Options functionality revamp

c/models/py_ftrl.cc, c/python/namedtuple.cc, tests/models/test_ftrl.py
- fix segfault in `onamedtuple` due to decrementing reference count for Python built-in type of `tuple`;
- add a corresponding test;
- minor cosmetics in FTRL algo.
=> Fix segfault in onamedtuple, add test, minor cosmetics in FTRL

c/models/dt_ftrl.cc, c/parallel/api.h, c/parallel/parallel_for_dynamic.cc, c/parallel/parallel_for_static.cc, c/parallel/thread_pool.cc
Add `nthreads` parameter to `parallel_for_static()` and `parallel_for_dynamic()`, so that when these functions are invoked not from `parallel_region()`, there is a way to adjust number of threads as needed.
Also, add a `dt::num_threads_available()` function, that returns number of threads in the pool, if called from the master thread, and number of threads in a team, otherwise.
=> Add nthreads parameter to dt::parallel_for_static and dt::parallel_for_dynamic

CHANGELOG.md, c/frame/__repr__.cc, datatable/utils/terminal.py, datatable/widget.py, tests/random_driver.py
- Frame headers are now aligned properly with their columns in IPython terminal;
- Use `bold` color instead of `bright_white` for emphasis: this works equally well on terminals with black backgrounds, and on terminals with white backgrounds (and I presume with any other backgrounds as well).
Closes #1793
=> Fixes for Ipython terminal 

CHANGELOG.md, c/column_fw.cc, c/expr/repl_node.cc, tests/munging/test_assign.py, tests/test_join.py
Function `replace_values` was not handling the case when the column where the values ought to be replaced does not exist yet, which caused crashes / unpredictable behavior.
Closes #1800
=> Fixed a bug when assigning a frame in DT[i, f.newcol]=expr

CHANGELOG.md, c/read/parallel_reader.cc, tests/__init__.py, tests/fread/test_fread_issues.py
Off-by-1 error in parallel reader: current iteration was marked as last in the ordered section when max_nrows was reached, however in such a way that the last chunk was not properly finalized.
Closes #1803
=> Fixed bad frame creation  when using parameter max_nrows

c/parallel/parallel_for_dynamic.cc, c/parallel/parallel_for_static.cc, c/parallel/ztest_parallel_for.cc, c/ztest.cc, c/ztest.h, tests/test_dt.py
- with @st-pasha's help fix `dt::parallel_for_dynamic()` that didn't account for `nthreads` being less than `num_threads_in_pool()`;
- add C++ tests for `parallel_for_static()` and `parallel_for_dynamic()` that test the above fix.
=> Fix nthreads usage in parallel_for_dynamic, add C++ tests

c/parallel/api.h, c/parallel/parallel_for_dynamic.cc, c/parallel/parallel_for_static.cc, c/parallel/thread_scheduler.h, c/parallel/thread_team.cc, c/parallel/thread_team.h, c/utils/function.h, c/utils/macros.h
An attempt to fix a rare exception that was showing up on ppc64le.
- Use `std::function` instead of `dt::function` in `parallel_for_static` and `parallel_for_dynamic`. The idea is that when these functions are used in a parallel region, then all executors are running at a different pace in different threads, and some of them will exit sooner than the others. When that happens, the compiler may decide to garbage-collect the function object while it is still being used in other threads.
- Instead of `cache_aligned<dynamic_task>` make `dynamic_task` cache-aligned naturally, to simplify debugging;
- `thread_team::shared_scheduler()` is now more careful about accessing `nested_scheduler` variable: it is now made atomic.
=> Fix attempt for parallel dynamic loop

CHANGELOG.md, c/frame/__repr__.cc, tests/test_dt.py
Fixed a UnicodeDecodeError that could be thrown when viewing a Frame with unicode characters in Jupyter notebook. The error only manifested for  strings that were longer than 50 bytes in length.
Closes #1825
=> Fixed UnicodeDecodeError when rendering Frame into html

c/progress/_options.cc, c/progress/progress_bar.cc, c/progress/progress_bar.h, tests/models/test_aggregate.py
Now the callback function accepts a single argument, `p`, which is a named tuple with 3 fields (more in the future). The fields are `p.progress`, `p.status` and `p.message`, having the same meaning as the three parameters `(progerss, status, message)` before. 
Closes #1823
=> Change the calling convention dt.options.progress.callback function

c/models/dt_ftrl.cc, c/models/dt_ftrl.h, c/models/dt_ftrl_base.h, c/models/py_ftrl.cc, docs/ftrl.rst, tests/models/test_ftrl.py
- add `validation_average_niterations` to FTRL `.fit()` method, that specifies how many iterations should be taken into account when calculating the loss. The loss is then averaged over the `validation_average_niterations`, and used to decide on whether early stopping should be done or not. The idea is that this parameter should help in situations, when loss is an oscillating function;
- add relevant tests.
=> Add loss averaging parameter to FTRL algo

CHANGELOG.md, c/frame/names.cc, tests/test_dt.py
=> Fix crash when dt.colindex() was used without arguments

CHANGELOG.md, c/utils/file.cc
Apparently we need to call `posix_fallocate` to ensure that writes to mem-mapped file will succeed. This function is available on Linux, but not on MacOS. 
On MacOS the equivalent can be achieved with `fcntl` command `F_PREALLOCATE` (see  https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fcntl.2.html).
Not adding any tests, because on Linux creating and mounting a size-restricted file system requires root privileges, and on MacOS even that is not possible. Testing can be done manually as described in the issue.
Closes #1837
=> Fixed crash on Linux when writing a Jay file and the disk is low on space

CHANGELOG.md, c/csv/reader_fread.cc, c/csv/reader_fread.h, c/read/column.cc, c/read/column.h, c/read/fread/fread_thread_context.cc, c/utils/file.cc, tests/fread/test_fread_large.py
So the problem was that the code in fread that handled conversion of `str32` -> `str64` columns was not taking into account NA values properly. This was an old code (which means the issue existed for a very long time). 
Today we have a similar code in `StringColumn` class itself, that handles the conversion correctly. Thus, simply removing the fread's code solved the problem: the conversion now happens automatically in the `StringColumn` class.
This PR also patches up a minor MacOS bug with `fcntl()` function sometimes returning `EINVAL` error even if it shouldn't. This bug was introduced yesterday, and it's unclear how it passed the unit tests. The "solution" is just to ignore this case, since the bug was fixed in the most recent version of MacOS already.
Closes …
=> Fix creation of Frame in fread for str64 columns with NAs

CHANGELOG.md, c/models/kfold.cc, datatable/models.py, tests/models/test_kfold.py
Added function `dt.models.kfold_random(nrows, nsplits)`, which is similar to `kfold(nrows, nsplits)`, except that the assignment of rows into folds is randomized, not deterministic.
The function uses efficient parallelized algorithm. Compared to sklearn's `KFold` I'm seeing 10-15 times speedup on my laptop:
```
n = 1000000, k = 3
datatable: 0.008468151092529297
sklearn:   0.08319830894470215
speedup:   9.824849372149332
n = 10000000, k = 3
datatable: 0.08074498176574707
sklearn:   0.9456908702850342
speedup:   11.712069897156221
n = 100000000, k = 3
datatable: 0.7584438323974609
sklearn:   11.31531810760498
speedup:   14.919124692249078
n = 1000000, k = 5
datatable: 0.016140222549438477
sklearn:   0.09569597244262695
speedup:   5.92903673722617
n = 10000000, k = 5
datatable: …
```
=> kfold_random() function

CHANGELOG.md, c/datatablemodule.cc, datatable/internal.py, tests/test_dt.py
The function will report the version of the compiler used to compile the datatable binary. Helpful for error diagnostics.
=> Add function dt.internal.compiler_version()

CHANGELOG.md, c/models/py_ftrl.cc, c/models/py_ftrl.h, tests/models/test_ftrl.py
If FTRL model had some hyperfeatures (i.e. it was trained with non-empty `.interactions` list), and then was pickled, it was not resuming properly on `.predict()` call. Our tests only covered the situation when after unpickling `.fit()` and `.predict()` methods were called one after another.
The bug has been fixed by properly initializing the interactions list not just in `.fit()`, but also in `.predict()`. Tests were improved in order to also cover such a use case.
=> Make FTRL model to resume properly after pickling

c/utils/file.cc, tests/test_tocsv.py
Otherwise, on Linux this could produce the error `EINVAL`.
=> Do not run fallocate() if file size is 0

CHANGELOG.md, c/datatablemodule.cc, c/expr/expr.h, c/expr/expr_unaryop.cc, c/expr/expr_unaryop.h, datatable/expr/expr.py, tests/munging/test_str.py, tests/test_dt_expr.py
- unary-op submodule is now structured in a more extensible way;
- Better error messages when an operator/function cannot be applied to a particular column;
- Added implementations for functions `ceil()`, `floor()`, `trunc()`, `isfinite()`, `isinf()`;
- Unary operators now use thread-pool for calculations.
WIP for #1845
=> Simplify structure of unaryop_expr.cc, and prepare to merge with math functionality

c/models/aggregator.cc, c/models/dt_ftrl.cc, c/str/py_str.cc, c/str/split_into_nhot.cc, tests/models/test_ftrl.py, tests/munging/test_str.py
- `split_into_nhot()` function encoded NA's into zeros, i.e. negatives. In this PR we fix it, so that NA's are encoded into NA's;
- minor change in FTRL to make it consistent with the new `split_into_nhot` output;
- fixed segfault when `split_into_nhot()` was called on `None`;
- add and adjust corresponding tests.
=> Fix split_into_nhot(), so that it encodes NA's into NA's

c/expr/expr.cc, c/expr/expr.h, c/expr/expr_binaryop.cc, c/expr/expr_binaryop.h, c/expr/expr_cast.cc, c/expr/expr_cast.h, c/expr/expr_unaryop.cc, c/expr/expr_unaryop.h, c/expr/virtual_column.cc, c/expr/virtual_column.h, c/parallel/shared_mutex.h, c/parallel/string_utils.h
This PR adds new functionality: lazy computation of expressions via virtual columns.
Consider a columnar expressions such as `f.A * exp(f.B / 2)`. An eager evaluator computes this expression roughly as follows: first, column `B` is extracted from the frame, then it is cast to `float64` type, then the `/` operator divides by 2.0 and stores into a temporary column, then we compute `exp()` of that column (creating a new column), then we extract column `A` and cast it into `float64` too, and finally compute the product of the latter 2 columns. As you can see, this whole process involves creating many intermediate columns, which affects performance and memory consumption.
The new "lazy" evaluator will instead do the following: first a virtual column for `B` is created, then we create a virtual …
=> Virtual columns

c/frame/names.cc, tests/fread/test_fread_api.py, tests/munging/test_assign.py, tests/test_dt_create.py
"Duplicate column names" warning improved:
- much better performance when there are many duplicates;
- warning now also mentions the new names for the renamed columns;
- the warning shows at most 3 duplicate columns (so that it wouldn't become too big);
- fixed a bug when detecting the stem of a name if it was mangled;
Closes #1591
=> Fix slow performance when having many duplicate column names

Makefile, c/datatablemodule.cc, c/parallel/monitor_thread.cc, c/parallel/monitor_thread.h, c/parallel/parallel_for_dynamic.cc, c/parallel/parallel_for_ordered.cc, c/parallel/parallel_for_static.cc, c/parallel/parallel_region.cc, c/parallel/thread_pool.cc, c/parallel/thread_pool.h, c/parallel/thread_worker.cc, c/parallel/thread_worker.h, ci/setup_utils.py, tests/models/test_aggregate.py, tests/models/test_kfold.py
- Worker 0 in the team no longer spawns a thread, instead it is supposed to use the master thread. Consequently, the thread_id of the master thread is now 0, and this variable can no longer be used to distinguish between running single-threaded or parallel code.
- Removed `thread_pool::get_instance()`: the singleton instance is now statically created at the start of the program and thus is always available. However, the spawning of workers is still delayed until actually needed.
- Added `monitor_thread` class, which is similar to a worker, but executes at a very low priority and only handles progress updates / log messages.
- `worker_controller` class renamed into `idle_job`.
- Added a "light sleep" phase, where the thread first busy-waits until the next scheduler may become available
=> Multiple optimizations to thread pool

tests/test_dt.py
Assign column names by doing `names =` instead of the dictionary keys to make tests compatible with Python 3.5, where dictionaries are unordered.
=> Fix test_html_repr_joined_frame failing with py35

c/parallel/semaphore.h, c/parallel/thread_worker.cc, c/parallel/thread_worker.h
Right now we're using condition variables to notify the thread workers when they need to wake up and do some job. The condition variables are standard in C++. However, this process has some problems. The standard condition-variable wait cycle looks like this:
```
// In thread workers:
std::unique_lock<std::mutex> lock(mutex);
while (!next_work) {
cond_var.wait(lock);
}
// In master thread:
{ 
std::lock_guard<std::mutex> lock(mutex);
next_work = ...;
}
cond_var.notify_all();
```
The semantic of the condition variable is that it takes a reference to a `lock` variable; then the `.wait()` call temporarily unlocks it while waiting, but then must **reacquire** the lock after it stops waiting. This means that after `.notify_all()` all worker threads will be scheduled by the OS for execution …
=> Use semaphores to handle thread sleep cycle

c/progress/manager.cc, c/progress/manager.h, c/utils/exceptions.cc
In some cases `progress_manager` tries to access progress bar that is already deleted by `progress_manager::finish_work()` method, and this results in a segfault. In particular, some of the aggregator tests, that also tested progress reporting, segfaulted on Linux and PPC.
To fix it, we use `std::mutex` to protect progress bar access.
=> Fix segfault in progress reporting

setup.py
On rare occasions `python setup.py` may be invoked with additional flags, for example see #1875:
```
python setup.py --no-user-cfg build
```
In this case we should still detect the command as `build`, not as `--no-user-cfg`.
Closes #1875
=> Skip extra flags when determining setup.py command

docs/ftrl.rst
Add basic model_type info to FTRL docs. At some point we may need to add more detailed info, including the one on online learning, labels and `.model_type_trained` property.
=> Add model_type info to FTRL docs

Makefile, ci/make_fast.py, ci/setup_utils.py
Command `make fast` now compiles datatable with `-O3` flag, i.e. with optimizations turned on. New command `make dfast` will compile datatable in debug mode, i.e. how "make fast" behaved up to now.
=> Add fast compilation mode with full optimizations

c/lib/parallel_hashmap/meminfo.h, c/lib/parallel_hashmap/phmap.h, c/lib/parallel_hashmap/phmap_base.h, c/lib/parallel_hashmap/phmap_bits.h, c/lib/parallel_hashmap/phmap_config.h, c/lib/parallel_hashmap/phmap_fwd_decl.h, c/lib/parallel_hashmap/phmap_utils.h, c/models/label_encode.h, c/models/murmurhash.cc, c/stats.cc, c/stats.h
Use parallel hash map to count the number of unique values in a column.
This PR adds external library `parallel_hash_map` (https://github.com/greg7mdp/parallel-hashmap, Apache-licensed), which appears to be somewhat faster than the std::unordered_map. The number of unique strings in a column is then computed via this hash-map using a single-pass parallel algorithm.
The performance is now comparable to pandas (even slightly faster), for example:
```
Cardinality=100, nrows=1e6
pandas:    0.062283
datatable: 0.048999 
Cardinality=1000, nrows=5e6
pandas:    0.359443
datatable: 0.257053 
Cardinality=10000, nrows=5e6
pandas:    0.459869
datatable: 0.266971 
Cardinality=10000, nrows=50e6
pandas:    4.79225
datatable: 2.70017 
```
<details><summary>Benchmarking code</summary>
```python
import …
```
=> Faster .nunique() for strings

CHANGELOG.md, c/models/label_encode.h
For binomial problem number of labels should be less or equal to two. This check should only be performed when a new label is encountered in the target column. When running label encoding in parallel, we now do the check making sure the label was not added from another thread.
Closes #1891
=> Do binomial check in label_encode functions only when adding new labels

c/parallel/parallel_for_dynamic.cc, c/parallel/parallel_for_static.cc, c/sort_insert.cc
- In a static/dynamic parallel loop, do not wake up the team if the number of iterations is 1;
- For string sorting, replace insertion sort with binary insertion sort. The idea is that for strings comparisons are relatively expensive, so their number should be kept to a minimum. This gives only a modest improvement in this particular test, but the benefit could be more significant for strings that have long common prefixes.
For n = 10M rows, the benchmark timings are as follows:
```
== Old == 
Sort int time     :  0.15964913368225098
Group int time    :  0.1817028522491455
Sort float time   :  3.507260799407959
Group float time  :  4.043126106262207
Sort string time  :  5.56641697883606
Group string time :  6.105027914047241
== New ==
Sort int time     :  0.13961219787597656
Group int …
```
=> Improve efficiency of sorting

c/parallel/monitor_thread.cc, c/parallel/thread_pool.cc, c/progress/manager.cc, c/progress/manager.h, c/progress/work.cc, c/utils/exceptions.cc
`progress_manager` static instance contains a mutex, which might create a problem when the process is forked. In order to avoid this issue we re-create the static `progress_manager` singleton in the "at_fork" handler.
=> Re-initialize progress manager instance during a fork

c/parallel/semaphore.h, c/sort.cc
- Main loop in sort.cc now uses static parallel schedule;
- Tweaked some other internal sorting parameters;
- Use asm instruction to perform thread pause (borrowed from OMP).
With these changes, sort times for 10M rows are (min/avg/max):
```
Ints:    0.0575 | 0.0809 | 0.5252
Floats:  0.3808 | 0.5535 | 0.7597
Strings: 1.351  | 1.612  | 1.920
```
For comparison, same benchmarks ran on the old "omp" version:
```
Ints:    0.05407 | 0.05901 | 0.09206
Floats:  0.5953  | 0.6148  | 0.6641
Strings: 1.322   | 1.531   | 1.844
```
Closes #1813
=> Improvements to sort

CHANGELOG.md, c/frame/__getitem__.cc, c/models/aggregator.cc, datatable/frame.py, tests/test_dt.py
- Parameter `progress_fn` in function `dt.models.aggregate()` is removed.
In its place you can set the global option `dt.options.progress.callback`.
- Removed deprecated Frame methods `.topython()`, `.topandas()`, `.tonumpy()`,
and `Frame.__call__()`.
Closes #1909
=> Remove deprecated APIs

CHANGELOG.md, c/csv/py_csv.cc, c/datatable.cc, c/datatable.h, c/datatable_load.cc, c/expr/workframe.cc, c/frame/__getitem__.cc, c/frame/__init__.cc, c/frame/__iter__.cc, c/frame/__repr__.cc, c/frame/names.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/frame/repeat.cc, c/frame/stats.cc, c/frame/to_numpy.cc, c/jay/open_jay.cc, c/models/aggregator.cc, c/models/kfold.cc, c/models/py_ftrl.cc, c/py_buffers.cc, c/python/xobject.h, c/set_funcs.cc, c/str/py_str.cc, tests/munging/test_assign.py, tests/munging/test_delete.py, tests/test_dt.py, tests/test_dt_create.py
The expression `DT[a]` is now valid when `a` is either an integer or a string, and it is interpreted as a column selector from `DT`. This is not a breaking API change, however previously expression `DT[a]` produced an error message saying that it will eventually be interpreted as row-selection.
Few other changes:
- added C++ method `Frame::oframe(DataTable*)->oobj` to simplify creation of Frame objects;
- A single-column Frame can now be used as a source for constructing a frame, e.g.: `dt.Frame(A=DT)` where DT is single-column;
- Added "hidden" Frame method `.keys()`, which returns just the tuple of column names. This method is needed to satisfy the requirements of python mapping interface;
- `**DT` can now be used -- expands into a sequence of columnname=column named arguments. For …
=> Single-column selector DT[col]

CHANGELOG.md, c/frame/to_csv.cc, c/write/column_builder.cc, c/write/column_builder.h, c/write/csv_writer.cc, c/write/output_options.h, c/write/value_writer.cc, c/write/write_manager.cc, c/write/write_manager.h, tests/test_tocsv.py
Added `quoting=` parameter to the .to_csv() method of Frame.
The meaning of the parameter is the same as in the standard `csv` module. Four quoting modes are supported: `csv.QUOTE_MINIMAL`, `csv.QUOTE_ALL`, `csv.QUOTE_NONNUMERIC` and `csv.QUOTE_NONE`.
Closes #1925
=> `quoting` parameter in to_csv()

c/models/column_hasher.cc, c/models/dt_ftrl.cc, c/models/murmurhash.cc, c/models/murmurhash.h, c/stats.cc
For the datatable purposes we don't need to vary `seed` parameter in Murmur hash functions. So to be safer and slightly faster, in this PR we remove this parameter and replace it with a zero seed.
=> Use zero seed in Murmur hash functions

c/models/column_convertor.h, c/progress/progress_bar.cc
As we had a performance issue calculating stats on integer columns, some time ago Aggregator was switched to cast all data to float columns and calculate stats on the casted columns only. Though this approach made Aggregator faster, it obviously introduced a significant memory overhead (~x2).
As of #1894 most of the performance issues connected to stats are solved, so now we can do casting on-the-fly in Aggregator. With this PR we decrease memory usage by about factor of two, as well as slightly improve overall Aggregator performance.
Thanks to @st-pasha, in this PR we fix minor glitch with progress bar rendering too. Testing progress bar capabilities further revealed problem #1937, that should also be fixed at some point.
=> Cast to floats on-the-fly in Aggregator

c/column.cc, c/column.h, c/column_bool.cc, c/column_from_pylist.cc, c/column_fw.cc, c/column_int.cc, c/column_pyobj.cc, c/column_real.cc, c/column_string.cc, c/expr/expr_binaryop.cc, c/expr/expr_column.cc, c/expr/expr_literal.cc, c/expr/expr_reduce.cc, c/expr/expr_str.cc, c/expr/i_node.cc, c/expr/j_node.cc, c/expr/repl_node.cc, c/expr/virtual_column.cc, c/frame/__init__.cc, c/frame/cast.cc, c/frame/rbind.cc, c/frame/repeat.cc, c/frame/replace.cc, c/models/dt_ftrl.cc, c/parallel/string_utils.cc, c/parallel/string_utils.h, c/py_buffers.cc, c/rowindex_array.cc, c/set_funcs.cc, c/sort.cc
- Column::stype() was converted from a virtual method into a property;
- Several new methods now return OColumns or take OColumns as arguments;
- OColumn::release() was removed -- the class no longer relinquishes ownership of the underlying Column pointer.
WIP for #1396
=> Further OColumn refactoring

CHANGELOG.md, c/column.h, c/column_from_pylist.cc, c/frame/__init__.cc, tests/test_dt_create.py
The length of range object was incorrectly interpreted when `start-step < stop <= start`. This was due to C division rules for negative numbers different from Python rules.
In addition, `Column::make_range()` was moved to `OColumn` class.
Closes #1942
=> Fix Frame creation from a degenerate range

c/column.cc, c/column.h, c/column_bool.cc, c/column_from_pylist.cc, c/column_fw.cc, c/column_int.cc, c/column_pyobj.cc, c/column_string.cc, c/expr/expr_cast.cc, c/expr/expr_unaryop.cc, c/frame/cast.cc, c/frame/rbind.cc, c/frame/stats.cc, c/jay/open_jay.cc, c/jay/save_jay.cc, c/models/dt_ftrl.cc, c/rowindex_array.cc, c/rowindex_impl.h, c/stats.cc, c/stats.h
- Stats calculations now use OColumn::get_element(...) API;
- Reduced number of Stats classes;
- Column::cast() method moved to OColumn class;
- In Ftrl, create_p() method now uses get_element() API;
- Two methods in ArrayRowIndexImpl has been switched to OColumns.
WIP for #1396
=> Further transitioning towards OColumn class

c/datatable.cc, c/lib/zlib/zconf.h, c/lib/zlib/zlib.h, c/utils/assert.h, c/write/zlib_writer.h, ci/setup_utils.py
This PR adds files `zlib.h` and `zconf.h` into the source code, because we have trouble consistently pinpointing its location on build machines. 
Also, few warnings fixed.
=> zlib.h header file included into c/lib/ folder

c/api.cc, c/column.cc, c/column.h, c/frame/rbind.cc, c/jay/open_jay.cc, c/jay/save_jay.cc, c/python/obj.cc, c/python/obj.h, tests/munging/test_rbind.py
The `.get()` method was used to provide access to the underlying implementation.
With this method removed, the implementation part is now properly encapsulated, which is a major step forward towards #1396.
WIP for #1396
=> Remove OColumn.get() method

c/models/dt_ftrl.cc, c/models/dt_ftrl.h, c/models/py_ftrl.cc, c/types.cc, c/types.h, c/utils/exceptions.cc, c/utils/exceptions.h, tests/models/test_ftrl.py
- allow training and validation target columns to have different `stype`s, their `ltype`s must be identical though. Addresses https://github.com/h2oai/h2oai/issues/10593#issuecomment-522372576
- minor improvement of `LType`'s handling.
=> Replace stype with ltype check for validation target column

c/frame/py_frame.cc, datatable/__init__.py, datatable/frame.py, tests/test_dt_create.py, tests/test_groups.py
These methods were scheduled for removal in v0.10.0
=> Remove deprecated Frame methods scalar(), append() and save()

c/writebuf.cc, c/writebuf.h
- Call `msync()` (http://man7.org/linux/man-pages/man2/msync.2.html) before unmapping. It is unclear from the docs whether this is required or not, but just in case.
- If an error occurs during `finalize()`, do not ignore it and throw an exception. This way if the file is not written properly, the user would be notified (assuming the OS reports error code correctly).
This may help with issues such as https://github.com/h2oai/h2oai/issues/10683
=> Sync when writing using mmap strategy

Makefile, c/datatable.cc, c/datatable.h, c/expr/workframe.cc, c/frame/names.cc, tests/test_dt_expr.py
Expression `DT[i,j]` now suppresses warnings about duplicate column names.
Closes #2003
=> No warnings about duplicate names in DT[i,j]

c/frame/names.cc, c/jay/save_jay.cc, c/utils/exceptions.cc, c/utils/exceptions.h, datatable/utils/typechecks.py, tests/test_dt.py
Python can be configured to treat warnings as errors. In that case datatable's warnings should behave properly and also throw exceptions.
Closes #2005
=> Properly treat the case when warnings are emitted as errors

c/models/dt_ftrl.cc, c/models/dt_ftrl.h
Pushing this as a separate PR because it also fixes a bug in Ftrl which could (rarely) cause a crash.
Replaces PR #2013
WIP for #2011
=> FTRL: do not use rowindex in fit()

ci/setup_utils.py
This helps in debugging when the locate command fails.
=> Add library name in locate command failure

c/utils/macros.h
Add macro definitions to enable building on Linux+aarch64.  Tested
with a `make test_install` and `make` and tests run clean.
=> Enable building for aarch64

c/datatable.cc, c/frame/py_frame.cc, docs/changelog/v-0-10-0.rst, tests/test_keys.py
In a keyed frame, the values in key columns must be unique. On the other hand, increasing the number of rows in a frame adds new rows filled with NAs, which is not legal for a keyed frame (because the values in the key column will stop being unique).
Closes #2021
=> Forbid increasing the number of rows on a keyed Frame

ci/setup_utils.py
Adding /usr/include into the include path confuses gcc and breaks its
include_next mechanism.
=> Don't explicitly add system includes

c/frame/py_frame.cc, c/frame/py_frame.h, docs/changelog/v-0-10-0.rst, tests/test_dt.py
The new property is convenient in situations when you either have a single-column Frame, or when you know that all columns in your Frame have the same stype.
Closes #2020
=> Added Frame property .stype

c/column.cc, c/frame/rbind.cc, tests/munging/test_rbind.py
After a column was resized, its `mbuf.size()` may be bigger than the amount of data actually used. This was causing problems with rbind, which used incorrect definition of column's size when copying the data.
The bug was introduced in yesterday's commit, so not a critical issue.
Closes #2026
=> Fix rbinding of resized frames

tests/models/test_aggregate.py
Fix aggregator tests broken due to the Python rowindex removal in #2018.
Closes #2019
=> Fix broken aggregator tests

c/buffer.cc, c/column.cc, c/column.h, c/column/latent.cc, c/column/latent.h, c/column/repeated.cc, c/column/repeated.h, c/column/sentinel.cc, c/column/sentinel_fw.h, c/column/sentinel_str.h, c/column/virtual.cc, c/column/virtual.h, c/column_fw.cc, c/column_impl.cc, c/column_impl.h, c/column_int.cc, c/column_string.cc, c/frame/__sizeof__.cc, c/frame/integrity_check.cc, c/sort.cc, c/stats.cc, c/utils/exceptions.cc, c/utils/exceptions.h
- `ColumnImpl::mbuf` field moved into `FwColumn` / `StringColumn` classes;
- cleaned up API of `ColumnImpl` class.
Closes #2052
=> ColumnImpl::Mbuf relocated

c/column/npmasked.cc, c/column/rbound.cc, c/column/repeated.cc, c/column/strvec.h, tests/munging/test_dt_rows.py
Certain virtual ColumnImpl classes were not propagating the `nrows_` property correctly during cloning after being resized.  `NpMasked_ColumnImpl` was one of such classes.
Closes #2055
=> Fixed incorrect cloning of resized virtual columns

c/column.cc, c/column.h, c/column/column_impl.cc, c/column/column_impl.h, c/datatable.cc, c/frame/integrity_check.cc, c/frame/rbind.cc, c/stats.cc, c/stats.h
- fix constructors `Column::new_data_column()` etc. (they were creating an unnecessary copy);
- `Column::pcol` renamed into `impl_`;
- methods `_acquire_impl` and `_release_impl` moved into the `Column` class;
Closes #2010
=> Column class now uses ref-count semantics for its impl

c/models/dt_ftrl.cc, c/models/dt_ftrl.h
Improve performance of `predict_row()` method by taking helper parameters out.
=> Minor dt::Ftrl refactoring

c/datatable.cc, c/datatable.h, c/datatablemodule.cc, tests/test_dt.py
The error was introduced in the latest PR: when DataTable uses default copy-construction, the `TRACK()` macro isn't called. The easiest solution is not to call these macros for `DataTable` at all.
Closes #2062
=> Fix 'removing untracked pointer' error

c/column/range.cc, c/column/range.h, c/column_from_pylist.cc, c/expr/head_literal_sliceint.cc, tests/random_attack.py
- `Range_ColumnImpl` no longer allows BOOL stype;
- Simplified `get_element()` functions;
- Added specialized `materialize()` method;
- Also added `fill_np_mask()` and `apply_rowindex()`;
- Added range column to the suite of random attack tests.
=> Range column improvements

datatable/fread.py, docs/conf.py, tests/fread/test_fread_large.py, tests/random_attack.py, tests/test_dt_sort.py, tests/test_tocsv.py
Occasionally python emits ResourceWarnings in our test suit, such as
```
Exception ignored in: <_io.FileIO name='/tmp/tmp21vyfziy' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp21vyfziy'>
```
These, however, are not regular warnings, and can neither be detected nor captured by `pytest`. They do not reproduce reliably, and we can't write any test to check for their presence/absence.
After a bit of googling, it appears that these warnings are caused by file handlers that are not closed explicitly. Thus, in this PR I'm fixing several instances where we used to have un-closed file handles, in hope that the warnings will go away.
=> Close all files opened with open() in python

ci/setup_utils.py
Library `shutil` was used in "setup_utils.py" (on a rare path) but never imported.
Closes #2070
=> Fix missing import in setup_utils.py

datatable/__init__.py, docs/changelog/v-0-10-0.rst, tests/test-import-all.py
The following symbols will no longer be exported from datatable by default:
- `open`
- `sum`
- `min`
- `max`
- `abs`
- `TypeError`
- `ValueError`
This change affects only importing via `from datatable import *`. The following still works:
```
import datatable as dt
DT = dt.open(...)
DT[:, dt.min(...)]
```
=> Do not overwrite builtins with 'from datatable import *'

c/column.cc, c/frame/__repr__.cc, c/models/column_hasher.cc, c/models/column_hasher.h, c/models/dt_ftrl.cc, tests/random_driver.py, tests/test_dt.py
- to avoid confusions and to increase compatibility with DAI, FTRL hashers will hash `NA`'s to  `NA_S8`, that is `uint64_t(1) << 63`, for all the supported column types; 
- minor adjustment to frame rendering and tests.
=> Adjust NA handling in FTRL

datatable/__init__.py, docs/changelog/v-0-10-0.rst, tests/test-import-all.py
Symbol `dt` (which is the `datatable` module itself) is now exported from `datatable` module.
Closes #2080
=> Import dt from datatable

c/column.cc, tests/random_attack.py, tests/random_driver.py, tests/test_dt.py
- set key columns in a random attacker;
- fix numpy python output;
- invalidate stats when mutable column implementation is requested;
- minor cleaning.
Closes #2075.
=> Add a function to set key columns to random attacker

c/column.cc, tests/random_attack.py, tests/random_driver.py, tests/test_dt.py
- add delete column operation to random attacker;
- don't delete boolean column in `select_rows_with_boolean_column()`;
- minor other adjustments to the unit tests.
Helped to reveal #2083.
=> Add delete columns operation to random attacker

c/frame/rbind.cc, tests/munging/test_rbind.py, tests/random_attack.py, tests/test_dt.py
- add join-frame-with-itself operation to random attacker;
- add key check to make sure number of keys is the same between python and datatable;
- restore frame sorting operation that was accidentally deleted in one of the previous PRs;
- drop keys after `rbind()` operation.
Adding key checks revealed a problem that we don't preserve key columns in many cases when we could: row slicing, join, etc. 
Closes #2090
=> Add join operation to random attacker

c/datatable.cc, c/datatable.h, c/python/dict.cc, c/python/dict.h, docs/changelog/v-0-10-0.rst, tests/test_dt.py
The issue was that when the frame was copied, the `py_inames` dictionary was copied using python's default copy-by-reference semantics. Subsequently, changes to that dictionary in one frame were affecting the other frame too, causing them to become inconsistent.  Now we explicitly deep-copy the `py_inames` dictionary.
Closes #2095
=> Fix setting a key on a copied frame

tests/random_attack.py
This is in response to #2095, that we missed due to the absence of copy operations in the random attacker. Testing it on a commit before PR #2097 was pushed, revealed the problem right away. With the latest master 10K seeds passed — no failures.
=> Add shallow copy operation to random attacker

tests/frame/test-repr-html.py, tests/frame/test-repr-text.py, tests/frame/test-repr.py, tests/test_dt.py
Trying to improve tests organization.
Looking forward, I think the tests should follow these general guidelines:
- file names should be all lowercase and use dashes instead of underscores (`test-repr.py`, not `test_repr.py`), because a dash is easier to type, and we tend to type the test names a lot;
- try to divide tests into as many files as possible -- this makes it easier to select only a particular subset of tests, and also creates pressure to write many more tests than we currently have.
=> Move tests related to Frame repr into a separate file

c/frame/repr/repr_options.cc, c/frame/repr/repr_options.h, c/frame/repr/sstring.h, c/frame/repr/terminal_widget.cc, c/frame/repr/terminal_widget.h, c/frame/repr/text_column.cc, c/frame/repr/text_column.h, c/frame/repr/widget.cc, c/frame/repr/widget.h, c/types.h, c/utils/terminal.cc, docs/changelog/v-0-10-0.rst, tests/frame/test-repr-text.py, tests/test_options.py, tests/test_parallel.py
-  Added option `display.max_column_width` which controls the maximum size of a cell after which its content gets truncated;
- If a Frame has too many columns, only the first + the last will now be rendered, adjusting automatically to the width of the terminal;
- Strings containing unicode characters will be hex-escaped if option `display.allow_unicode` is false;
- lots of tests
Closes #2106 
Closes #2107 
Closes #2116 
Closes #2117 
Closes #2118
=> Improve many columns & unicode handling when rendering Frame in terminal

c/buffer.cc, c/buffer.h, c/column/sentinel_fw.cc, c/frame/names.cc, c/py_buffers.cc, c/python/pybuffer.cc, c/python/pybuffer.h, docs/changelog/v-0-10-0.rst
- Created  a new class `py::buffer` that encapsulates a `Py_buffer` object. This will ensure that the buffer is always properly released when it is no longer needed in datatable;
- Fixed small leak in `test_coverage()`;
- Fixed a leak in `Latent_ColumnImpl::vivify()`, which is used during any reduce operation.
Closes #2123
Closes #2125
=> Fixed leak when converting a string numpy array into a Frame

c/frame/repr/repr_options.cc, c/progress/progress_bar.cc, c/utils/terminal.cc, c/utils/terminal.h, tests/frame/test-repr-text.py, tests/test_parallel.py
We will now detect the encoding of `sys.stdout` at datatable startup, and set the option `display.allow_unicode` only if that encoding is UTF-8. The user still has the possibility to change the option.
In addition, the option `display.allow_unicode` will no longer affect the behavior of `str(DT)`: when stringifying we allow unicode always.
=> Auto-detect terminal's encoding

c/datatablemodule.cc, c/datatablemodule.h, c/frame/__repr__.cc, c/frame/repr/html_styles.cc, c/frame/repr/html_widget.h, datatable/__init__.py, docs/changelog/v-0-10-0.rst
- Added method `datatable.init_styles()` which injects datatable's stylesheets into a Jupyter notebook;
- This method is also run automatically when datatable is imported.
Note that this PR does not solve the problem of disappearing stylesheet entirely: if have a cell `import datatable as dt`, then the stylesheet will be automatically added when the cell is executed, but then will disappear if the user runs the same cell again. In a situation like this the user would have to manually call `dt.init_styles()` to restore the stylesheet. This is far from ideal, because a normal user would probably not even know about the existence of this function...
I've experimented with different approaches to this problem, but neither worked:
- Overriding Python import hooks, forcing python to re-import …
=> Improve stylesheet injection into a Jupyter notebook

c/frame/to_csv.cc, c/utils/file.cc, c/utils/file.h, c/write/csv_writer.cc, c/write/write_manager.cc, c/write/write_manager.h, c/writebuf.cc, c/writebuf.h, docs/changelog/v-0-10-0.rst, tests/conftest.py, tests/test_tocsv.py
Method `Frame.to_csv()` gains two new boolean parameters: `header=` and `append=`. The `header=` parameter controls whether or not to write into the output the header row with column names. The `append=` parameter allows the CSV content to be appended to an existing file instead of overwriting it:
```python
DT.to_csv("out.log", append=True)
```
By default, `append=False`. The default value of `header=` parameter is inferred: it is equal to `True` in all cases except when both `append=True`, and the file given as the argument already exists.
Closes #2130
=> Added parameters append= and header= to .to_csv()

c/expr/head_func_binary.cc, c/expr/workframe.cc, c/expr/workframe.h, tests/test_dt_expr.py
The bug manifested for any binary operation where one side of the op contains multiple columns, while the other side only a single column. Now this case works properly.
Closes #2142
=> Fix binary-op applied to a columnset vs a single column

c/models/dt_ftrl.cc, c/models/dt_ftrl.h, c/models/dt_ftrl_base.h, c/models/label_encode.cc, c/models/label_encode.h, tests/models/test_ftrl.py
- restore a support for the `negative_class` FTRL parameter;
- minor cleaning;
- test adjustment.
Closes #2136
=> Restore a support for the negative_class FTRL parameter

c/datatablemodule.cc, c/expr/eval_context.cc, c/expr/expr.h, c/expr/py_update.cc, c/expr/py_update.h, c/frame/__init__.cc, c/python/args.cc, c/python/args.h, c/python/obj.cc, c/python/obj.h, datatable/__init__.py, docs/changelog/v-0-10-0.rst, tests/ijby/test-update.py
The `update()` function can be used inside `DT[i, j]` in the j-th place. This function allows updating/creating multiple columns at once. For example:
```
DT[:, update(A = np.random.randn(100),
B = dt.Frame(range(100)),
C = dt.str32(f.ZipCode))]
```
In general, `update(**kwds)` takes an arbitrary keyword arguments, and then performs the assignment
```
DT[:, kwds.names()] = kwds.values()
```
Closes #1700
=> update() function

c/column.cc, c/column.h, c/column/const.cc, c/expr/eval_context.cc, c/expr/eval_context.h, c/expr/head_frame.cc, c/expr/workframe.cc, c/groupby.h, tests/ijby/test-assign-expr.py, tests/ijby/test-assign-scalar.py, tests/ijby/test-assign.py, tests/ijby/test-update.py
- It is now possible to combine reduce expressions (such as `dt.sum(f.A)`) with map expressions (such as `f.A`) within `DT[i,j]` call. Thus, the following expression is now possible: `f.A / sum(f.A)`, both with and without a groupby;
- We now also allow assigning to a whole column a scalar expression that has different type than the original column;
- Several tests added, some tests that were previously xfailing now succeed;
Closes #2155 
Closes #2146
=> Allow mixing grouped and non-grouped expressions in DT[i,j]

c/py_buffers.cc, c/python/pybuffer.cc, c/python/pybuffer.h, docs/changelog/v-0-10-0.rst, tests/test_dt_create.py
When a stride is negative, the calculation of buffer size as `nrows * stride * elemsize` was producing incorrect results, and creating a buffer object from this was failing internal consistency checks. Now the case of negative stride is handled properly: we use `|stride|` to compute the buffer's size, but then change the `start` from 0 to the end of the buffer when applying a SliceView to that buffer.
The case `nrows == 0` is now also handled correctly (cannot have a non-null pointer to a memory region of size 0).
Closes #2163
=> Fix creating a Frame from a numpy array with negative stride

c/column/npmasked.cc, c/column/npmasked.h, tests/test_dt_create.py
The issue was that even after the materialization, the class of `NpMasked_ColumnImpl` column remained the same (i.e. "virtual"), and thus the column was not considered properly materialized.
Closes #2173
=> Fixed "invalid data access" error when saving a masked nparray column 

c/expr/head_literal_int.cc, docs/changelog/v-0-10-0.rst, tests/test-groups.py
Similar to pandas `Groupby.nth()`, we now have the ability to extract just a single row per group:
```
DT[1, :, by(f.A)]
```
Both positive and negative group index is supported.
If the index is out-of-bounds for some groups, those groups will be discarded from the output without raising an error.
Closes #1584
=> Added ability to select a specific row in each group

c/expr/head_literal_range.cc, docs/changelog/v-0-10-0.rst, tests/ijby/test-assign-scalar.py
Now a `range()` object can be used instead of a single-column Frame. This includes: in an assignment expression, in computed columns, etc.
```
DT["A"] = range(100)
DT[:, {"R": f.A + range(DT.nrows)}]
```
Closes #2157
=> Expand use of range objects in DT[i,j]

c/models/py_ftrl.cc
Adjust help for `.model_type` and `.model_type_trained` FTRL properties. At some point we may also need to rename `.model_type` to `.model_type_requested` or something like this to make the difference more clear.
=> Make the difference between .model_type and .model_type_trained more clear on FTRL docs

c/expr/declarations.h, c/expr/eval_context.cc, c/expr/expr.cc, c/expr/expr.h, c/expr/head.h, c/expr/head_frame.cc, c/expr/head_frame.h, c/expr/head_func.cc, c/expr/head_func.h, c/expr/head_list.cc, c/expr/head_list.h, c/expr/head_literal.cc, c/expr/head_literal.h, c/expr/head_literal_bool.cc, c/expr/head_literal_float.cc, c/expr/head_literal_int.cc, c/expr/head_literal_none.cc, c/expr/head_literal_string.cc, c/expr/head_literal_type.cc, c/frame/__getitem__.cc, docs/changelog/v-0-10-0.rst, tests/ijby/test-assign-scalar.py
Now a column's type can be changed via a simple assignment:
```
DT["A"] = int            # Column A in frame DT will become integer
DT[:, int] = dt.float64  # All integer columns will be converted to float64
```
Closes #2158
=> Assign type in DT[i,j]

c/column.cc, c/column.h, c/column/sentinel_str.cc, c/datatable.cc, c/datatable.h, c/frame/integrity_check.cc, c/frame/py_frame.cc, c/frame/py_frame.h, c/jay/open_jay.cc, c/jay/save_jay.cc, c/stats.cc, c/stats.h, datatable/__init__.py, docs/changelog/v-0-10-0.rst, tests/random_attack.py, tests/test_dt.py
Now a Frame can be deep-copied using 2 different methods:
```
DT_deep_copy1 = DT.copy(deep=True)
import copy
DT_deep_copy2 = copy.deepcopy(DT)
```
In addition, frame materialization will no longer drop Stats objects, which should improve performance.
Closes #2179 
Closes #2089
=> Implement deep-copy functionality

c/frame/py_frame.cc, c/frame/py_frame.h, docs/changelog/v-0-10-0.rst, docs/f-expressions.rst, tests/test_dt.py
Before, `export_names()` injected column-exprs into the global namespace.
Now, `export_names()` returns a tuple of column-exprs to the user.
The new semantics is much safer (no messing around with global variables), more transparent to the reader (there is no question of where those variables appear from), and allow renaming the columns on the fly (i.e. if the column's name is "User Id" in the frame, then the user can assign it to a variable named simply `id`).
Also, there is now no possibility to accidentally overwrite global variables, or to create variables with invalid names.
Closes #2184
=> export_names() now returns column exprs

c/expr/eval_context.cc, c/expr/head_func.cc, c/expr/head_reduce.h, c/expr/head_reduce_binary.cc, c/expr/op.h, datatable/__init__.py, datatable/expr/__init__.py, datatable/expr/expr.py, datatable/expr/reduce.py, docs/changelog/v-0-10-0.rst, tests/test_reduce.py
Added 2 new reducer functions `cov()` and `corr()`.
- `cov(A, B)` computes the covariance between 2 columns,
- `corr(A, B)` computes Pearson's correlation coefficient between 2 columns.
Also fixed a bug where a reducer could not be applied if DT[i,j] expression contained `i` filter but not `by`.
Closes #1543
=> Implement functions cov() and corr()

Makefile
Based on internal discussion, it seems like original ibm image `ibmcom/centos-ppc64le` disappeared. 
This is experimental fix to replace it by official centos7 image for PPC64le.
=> [CI] Update PPC64 build image

c/expr/expr_unaryop.cc, docs/changelog/v-0-10-0.rst, tests/ijby/test-func-unary.py
Note that this does have an effect on performance. Unfortunately, there is no other way to make this function return correct result.
In the future we may keep a stat indicating whether the column is ASCII or not. And in case it is ascii, use the old simpler function for computing string length.
Closes #2160
=> Function .len() now returns the number of codepoints in a string

c/frame/join.cc, c/models/aggregator.cc, c/models/dt_ftrl.cc, c/parallel/api.h, c/parallel/parallel_for_static.h, c/parallel/parallel_region.cc, c/progress/ztest_progress.cc, c/sort.cc, c/str/split_into_nhot.cc
Make use of `NThreads` class in `dt::parallel_region` to be consistent with all the other `dt::parallel_*` functions.
=> Make use of NThreads class in parallel_region

datatable/fread.py
`proc.stdout.read()` was not closing the stdout/stderr parts of the Popen object, causing the warnings.
=> Prevent fread emitting message about BufferedIO file not closed

.travis.yml, tests/frame/test-repr-text.py
The test fails on Travis because their terminal width is 80 instead of 120.
This PR fixes the problem.
=> Fix test_horizontal_elision on Travis

c/frame/repr/text_column.cc, c/models/dt_ftrl.cc, c/progress/progress_bar.cc, c/python/args.cc, c/writebuf.cc
Standard header includes are slightly different on Windows, so in some files where we use `std::min` or `std::max` we need to explicitly include `<algorithm>`, otherwise compilation fails.
WIP for #1369
=> Add <algorithm> includes

Makefile, c/column/sentinel_fw.cc, setup.py
For some reason `setuptools.Extension` in `setup.py` was using `datatable/lib/_datatable` as the module name, as a consequence, this name was not compatible with the `PyInit__datatable` function name following by the msvc linker error. In this PR we fix it and also suppress several "unused variable" warnings.
WIP for #1369
=> Make module name be compatible with PyInit__datatable

c/python/args.cc, c/python/args.h, c/ztest.cc, c/ztest.h, tests/test_parallel.py
Even though we do not expect users to call internal `datatable.lib.core` C++ tests, they should not segfault when called with missing arguments. In this PR we add a `PKArgs::check_required_args()` method that checks if the required arguments are missing and improve`test_parallel.py` to make sure C++ tests do not segfault.
=> Fix segfault when C++ tests were called with missing arguments

c/column/func_unary.h, c/models/dt_ftrl.cc, c/models/utils.h, c/stats.cc
- add and use portable implementation of `std::isfinite` in FTRL. ND: on Windows `std::isfinite` and `std::isnan` are only supported for `float` and `double` types;
- replace `+=` with `|=` for boolean variables in `stats.cc` that were causing warnings on WIndows.
WIP for #1369
=> Use portable implementation of std::isfinite in FTRL

c/parallel/monitor_thread.cc, c/parallel/parallel_for_static.h, c/parallel/thread_pool.cc, c/parallel/thread_pool.h, c/parallel/thread_worker.cc, c/parallel/thread_worker.h
Creating monitor thread on the datatable import causes a deadlock on Windows, see this [discussion](https://stackoverflow.com/questions/32252143/stdthread-cause-deadlock-in-dllmain) for more details. In fact, we don't really need the monitor thread being available right after the `import datatable`, so its creation can be easily postponed. 
In this PR we 
- move the monitor handler from `idle_job` to `thread_pool` class, and create the monitor thread only when it is needed by datatable;
- disable fork related code on Windows, because there is no fork mechanism there.
WIP for #1369
=> Move monitor thread from idle_job to thread_pool

c/column/shift.h, c/datatablemodule.cc, c/datatablemodule.h, c/expr/head_func.cc, c/expr/head_func.h, c/expr/head_func_shift.cc, c/expr/op.h, c/expr/workframe.cc, c/expr/workframe.h, datatable/__init__.py, datatable/expr/expr.py, datatable/math.py, docs/changelog/v-0-10-0.rst, tests/ijby/test-shift.py
This PR implements the new function `shift(col, n=1)` to generate leads/lags of a column.
Closes #1513
=> New function: shift()

c/csv/reader_fread.cc, c/python/obj.cc
Designated struct initializers are not a part of the C++11 standard, so in this PR we redefine the CPython `_Py_static_string_init` macro and adjust datatable code to use other means for struct initialization.
WIP for #1369
=> Do not use designated struct initializers

c/buffer.cc, c/buffer.h, c/column.cc, c/column.h, c/column/column_impl.cc, c/column/column_impl.h, c/column/const.h, c/column/const_na.cc, c/column/latent.cc, c/column/latent.h, c/column/npmasked.cc, c/column/npmasked.h, c/column/range.cc, c/column/range.h, c/column/sentinel.h, c/column/sentinel_fw.cc, c/column/sentinel_fw.h, c/column/sentinel_str.cc, c/column/sentinel_str.h, c/datatable.cc, c/datatable.h, c/frame/key.cc, c/frame/py_frame.cc, c/jay/save_jay.cc, docs/changelog/v-0-10-0.rst, tests/test_dt.py
This parameter will force any memory-mapped columns to become resident in RAM. The same applies to any columns that use external memory obtained via PyBuffer interface.
Closes #1467
=> New parameter `Frame.materialize(to_memory=True)` to load data into memory

c/expr/fbinary/bimaker.cc, c/expr/funary/umaker.cc
Assigning to a map element the result of a function invocation is unsafe if the function may throw an exception: in this case on older compilers there could be an empty element stored into the map.
This was causing a crash on PPC64le (presumably because we are using an old GCC4.8 compiler there).
=> Fix an internal bug in umaker/bimaker

c/frame/__repr__.cc, c/frame/repr/html_styles.cc, c/frame/repr/html_widget.h
In this PR we 
- respect the `interactive` option in a terminal, and always turn the interactive mode off in Jupyter;
- move `HTMLWidget` code from `__repr__.cc` to `html_widget.h`, this seems to be a more natural place for the widget;
- add a `HTMLWidget::write_to_jupyter()` method to write HTML code to Jupyter;
- use the above method to render HTML when something like `DT.view()` is called in Jupyter. Also, make the `emit_stylesheet()` to use the new method;
- leave the behavior of `str(DT)` intact in Jupyter, because even if we return HTML here the `print(DT)` command will have no clue about it and will print the HTML source code. The only benefit of returning HTML in `str()` could be that one may later do something like `HTML(str(DT))` — but it is unlikely to happen and printing a …
=> Improve frame rendering in Jupyter and fix the interactive mode

c/models/dt_ftrl.cc, c/models/py_ftrl.cc, tests/models/test_ftrl.py
It seems that feature importance normalization got broken at the time when we converted the FTRL code to use `is_valid` parameter in the `get_element()` functions. In this PR we fix it and improve the tests.
=> Fix feature importance normalization

README.md
Right now the links to install datatable on Linux, that are included in `README.md`, are broken for all the python versions. This brings a lot of confusion, because this information is also shown on the main github page for datatable. In this PR we replace installation from these links with a single `pip install datatable` command, that will install datatable v0.10 on Linux and Mac. When custom links are fixed, we can include them under the detailed installation instructions in the docs.
=> Replace custom wheel URLs with pip install datatable in README

tests/fread/test_fread_random.py
`tests/fread/test_fread_random.py::test_fread_omnibus` is failing for some seeds due to the fact that `generate_str_column()` generates a column filled with only numeric values, for example for the seed of `1795109353` the column data is `['7E1', '']`. When `dt.fread()` receives such a data it converts it to a float column, while in the test the type was assumed to be `ltype.str`. 
In this PR we add a check to `generate_str_column()` function to make sure it never generates fully numeric data.
=> Fix test_fread_omnibus

Makefile, c/datatablemodule.cc, ci/xbuild/__init__.py, ci/xbuild/compiler.py, ci/xbuild/extension.py, ci/xbuild/logger.py, datatable/lib/__init__.py, ext.py
This module offers an alternative way for building the `_datatable` extension, instead of `setuptools`. It has several advantages over the traditional way:
- There is no automatic adding of compile/link flags: the consumer of the module is in full control over how the compilation is done;
- The build process is performed in parallel, reducing the compile time by a factor of 10 or so (similar to make);
- Only files that need to be recompiled are recompiled (like make);
- The implementation is pure-python (unlike make), which makes it easy to modify the code, and to reuse it from other python processes;
- Allow the code to be automatically recompiled during python import;
- Better log of the build process (and fully customizable);
- Support fast recompiling in different modes (without …
=> New Xbuild module

datatable/types.py, docs/changelog/v-0-11-0.rst, tests/test_types.py
(We may want to include this into 0.10.1 release as well)
Closes #2231
=> Fix min/max properties of bool8 stype

c/writebuf.cc
The POSIX `write()` function is [deprecated](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-write?view=vs-2019) on Windows, so we use the ISO C++ conformant `_write()` instead. This also requires to use OS-specific includes.
WIP for #1369
=> Add a workaround for a POSIX write() function on Windows

c/frame/repr/terminal_widget.cc, c/utils/terminal/terminal.cc, c/utils/terminal/terminal.h
- add a code to detect terminal size on Windows;
- there is no simple way to catch the terminal re-size event on Windows, because there is no `SIGWINCH` signal there. For such a reason, on WIndows we just re-check the terminal size everytime the `Terminal::get_width()` and `Terminal::get_height()` are called.
WIP for #1369
=> Add a code to detect terminal size on Windows

ci/xbuild/__init__.py, ci/xbuild/logger.py, ci/xbuild/wheel.py, ext.py, pyproject.toml
In this PR we add the ability for `ext.py` to build wheel files, conforming to PEP-517 specification for build-backends.
The `pyproject.toml` file still refers to the legacy setup.py/setuptools; the new functionality has to be invoked manually.
=> Add Wheel-building functionality to xbuild

Makefile, c/column/pysources.cc, c/column/pysources.h, c/column_from_pylist.cc, c/column_from_python.cc, c/models/dt_ftrl.cc, c/models/label_encode.cc, c/python/dict.cc, c/python/dict.h, c/python/obj.cc, c/python/obj.h, docs/changelog/v-0-11-0.rst, tests/models/test_aggregate.py, tests/models/test_ftrl.py, tests/munging/test_cbind.py, tests/munging/test_delete.py, tests/munging/test_dt_cols.py, tests/munging/test_dt_rows.py, tests/test_dt.py, tests/test_dt_create.py
- Reorganize code in "column_from-python.cc" so that it no longer relies on exceptions for type-bumping.
- Lists containing integers 0 and 1 will now produce columns of type `int8` (instead of `bool8`)
- Make code more robust in what types are accepted: all stypes should be able to accept values for lower stypes. For example, `bool` is considered lower than `int8`, and therefore an `int8` list will now accept `bool`s mixed with `int8` values.
Closes #2250 
Closes #2251
=> Frame from list

c/models/dt_ftrl.cc, c/models/dt_ftrl.h, c/models/dt_ftrl_base.h, c/models/label_encode.cc, c/models/label_encode.h, c/models/py_ftrl.cc, docs/changelog/v-0-11-0.rst, tests/models/test_ftrl.py
- use `SType::INT32` for `id` column in `.labels` for all the model types as this makes the code more consistent and much cleaner. Since for numeric and binomial regressions we only have one or two labels this change has a negligible effect on the memory usage;
- improve tests.
=> Improve handling of .labels in FTRL

Makefile, c/buffer.cc, c/lib/mman/mman.cc, c/lib/mman/mman.h, c/read/constants.cc, c/read/constants.h, c/writebuf.cc
- add Windows implementation of `mmap` functions. The code can be compiled and linked on Windows, though it is not functional yet;
- fix a problem when `make coverage` failed on files that had no function definitions.
WIP for #1369
=> Add Windows implementation of mmap functions

c/python/iter.cc, docs/changelog/v-0-11-0.rst
- Try `.__len__()` before going for `.__length_hint__()`;
- Test for existence of `.__len__` and `.__length_hint__` before attempting to call them -- this avoids throwing an exception unless in exceptional circumstances.
Closes #2272
=> Improve py::oiter::size()

c/parallel/api.h, c/parallel/monitor_thread.cc, c/parallel/monitor_thread.h, c/parallel/thread_pool.cc, c/parallel/thread_pool.h, c/progress/progress_manager.cc, c/progress/progress_manager.h, docs/changelog/v0.11.0.rst
- The signal handler is now declared as an `extern "C"` function, as recommended by the spec;
- The handler only accesses `volatile sig_atomic_t` variables, as required by pre-C++11 standard;
- Check whether `sigint_handler_prev` is NULL before trying to call it (can it possibly be null?).
Closes #2282
=> Improve the interrupt signal handler 

ext.py
The approach with `sys.implementation._multiarch` doesn't work on Python3.5, so we can use `platform.machine()` instead ([platform](https://docs.python.org/3/library/platform.html) is a standard library).
=> Another PPC build fix

datatable/sphinxext/ref_context.py, docs/changelog/v0.10.1.rst, docs/conf.py
This new directive makes it easy to link to functions / methods from datatable doc pages. In particular, the following functionality is enabled:
```
.. ref-context:: datatable.Frame
* :meth:`.to_dict()`
* :meth:`Frame.to_tuples`
* :meth:`.to_csv(filename, **kwargs)`
```
these will all be linked to their proper targets: `datatable.Frame.to_dict`, `datatable.Frame.to_tuples` and `datatable.Frame.to_csv` respectively. At the same time, the links will retain their text as written, allowing us to tailor the text to the context where it appears. 
For example:
```
*  Added function :func:`repeat(frame, n)` that creates a new
Frame by row-binding ``n`` copies of the ``frame``.
```
Here it makes sense to write the function with its list of parameters, so that we could also describe those …
=> Added Sphinx directive ..ref-context

c/models/aggregator.cc
`DataTable` object stored in `dt_counts` unique_ptr was never deleted.
=> Fix a leak in aggregate_exemplars()

c/frame/cbind.cc, datatable/sphinxext/xfunction.py, docs/_static/code.css, docs/_static/xfunction.css, docs/api/frame.rst, docs/conf.py, docs/index.rst, docs/manual/name_mangling.rst, docs/using-datatable.rst, requirements_docs.txt
- The documentation of `cbind()` greatly expanded;
- Added new documentation page "Name mangling" which describes the handling of column names;
- Make sure the HTML title of the page corresponding to each function contains the short function name only, instead of the full name;
- Added new special parameter "except" to the Parameter list, this tag will be highlighted in red;
- Minor style tweaks;
=> Improve documentation of cbind()

c/datatablemodule.cc, c/frame/cbind.cc, c/utils/exceptions.cc, c/utils/exceptions.h, datatable/__init__.py, datatable/utils/typechecks.py, docs/changelog/v0.11.0.rst, tests/munging/test_cbind.py
In this PR the new class is used in `cbind()` method only. Over time we can convert more methods to use this new exception class as seem appropriate.
=> Add exception class InvalidOperationError

c/frame/py_frame.cc, docs/api/frame.rst, docs/api/frame/copy.rst, tests/frame/test-copy.py, tests/test_dt.py
- expanded documentation of `Frame.copy()` and converted into new xfunction format;
- tests for this function moved into a separate file.
=> Improve documentation for copy()

c/parallel/monitor_thread.cc, c/progress/_options.cc, c/progress/_options.h, tests/test_options.py
Add the `dt.options.progress.allow_interruption` option that will control if datatable is allowed to set a `SIGINT` handler or not. This option is `True` by default. If this option is set to `False`, then it won't be possible to interrupt any long-running datatable tasks with `Control+C`.
WIP for https://github.com/h2oai/h2oai/issues/13469
=> Add dt.options.progress.allow_interruption option

datatable/sphinxext/dtframe_directive.py, datatable/sphinxext/xfunction.py, datatable/utils/typechecks.py, docs/_static/code.css, docs/api/math.rst, docs/using-datatable.rst
Improve rendering of Examples section in the documentation of functions.
Now the code is properly converted into input/output blocks.
In addition, the textual output of a frame is converted to `..dtframe` directive (although types are not handled properly yet).
=> Xfunction Examples section

c/datatablemodule.cc, c/utils/exceptions.cc, c/utils/exceptions.h, datatable/exceptions.py, datatable/utils/typechecks.py, tests/frame/test-colindex.py
- Added new `exceptions.py` script where we can store all datatable exceptions (currently they live in `dt.utils.typechecks`, which is not a proper place for them);
- Do not subclass builtin `KeyError` exception -- instead give it a "fake" string object, which reprs into a regular string, circumventing python's bug with KeyError;
- Added a test.
=> Ensure KeyError is properly picklable

ci/xbuild/compiler.py
- fix a bug when the environment variable `DT_MSVC_PATH` was ignored;
- adjust MSVC default path to correspond to AppVeyor path for build tools.
=> AppVeyor integration

CHANGELOG.md, docs/release-history.rst, docs/releases/v0.4.0.rst, docs/releases/v0.5.0.rst, docs/releases/v0.6.0.rst
Convert changelogs from the `.md` format to the `.rst`; minimal cleanup.
WIP for #2304
=> Converted changelogs 0.6.0, 0.5.0, 0.4.0

docs/_static/changelog.css, docs/releases/v0.10.0.rst, docs/releases/v0.10.1.rst, docs/releases/v0.3.0.rst, docs/releases/v0.3.1.rst, docs/releases/v0.3.2.rst, docs/releases/v0.4.0.rst, docs/releases/v0.5.0.rst, docs/releases/v0.6.0.rst, docs/releases/v0.7.0.rst, docs/releases/v0.8.0.rst, docs/releases/v0.9.0.rst, src/datatable/sphinxext/dt_changelog.py, src/datatable/sphinxext/dtframe_directive.py, src/datatable/sphinxext/xfunction.py, src/datatable/sphinxext/xnodes.py
- Added ability to list wheel file links in infoboxes on the changelog pages;
- Added wheel links for all past versions;
- Refactored the use of custom sphinx nodes: now they are declared in a separate shared extension.
WIP for #2304
=> Wheel links in the changelog

ci/xbuild/__init__.py, ci/xbuild/logger.py, src/core/column/const.cc, src/core/column/sentinel_str.cc, src/core/expr/fnary/rowmean.cc, src/core/expr/fnary/rowminmax.cc, src/core/expr/fnary/rowsd.cc, src/core/expr/fnary/rowsum.cc, src/core/expr/head_func.cc, src/core/models/aggregator.cc
- add a conservative Sublime friendly `Logger2` to xbuild; 
- fix all the compilation warnings produced by `clang` on Mac.
=> Add Logger2 to xbuild

ci/gh.py, docs/_static/changelog.css, docs/conf.py, docs/releases/v0.10.0.rst, docs/releases/v0.10.1.rst, docs/releases/v0.11.0.rst, src/datatable/sphinxext/xcontributors.py
- Created Sphinx extension that provides the `.. contributors` directive. This directive is used on "changelog" pages to list the users who contributed to a particular release.
- Added helper script `ci/gh.py` for retrieving contributor lists from GitHub;
- Recorded contributors for versions 0.10.x and 0.11.0. These may still change, especially for 0.11.0 as we create new PRs/issues; but also for 0.10.x if we ever find mis-categorized old issues/PRs.
WIP for #2304
=> Sphinx extension Xcontributors

ci/ext.py
`-fdebug-macro` option is clang specific, so other compilers may fail with messages like 
```
gcc: error: unrecognized command line option ‘-fdebug-macro’; did you mean ‘-fdebug-cpp’?
```
=> Use -fdebug-macro option for clang only

ci/ext.py, src/core/python/int.cc, src/core/python/list.cc, src/core/python/obj.cc, src/core/utils/macros.h
- add `DT_TYPE_LONG64` variable to facilitate handling of 32 and 64 bit longs;
- fix `to_int64()` and `to_int64_strict()` to take into account size of long on a system;
- make use of `DT_TYPE_LONG64` in some other places.
WIP for #2301
=> Fix to_int64() functions to take into account size of long

src/core/frame/repr/repr_options.cc, src/core/utils/terminal/terminal.cc, src/core/utils/terminal/terminal.h, tests/frame/test-repr-text.py
- fix the way terminal size is detected on Windows;
- since internally `dt.options.display.max_column_width` couldn't be less than `2`, to be consistent, also adjust the setter for this option.
WIP for #2301
=> Fix frame to string conversion on Windows

src/datatable/fread.py, src/datatable/utils/terminal.py, tests/fread/test_fread_issues.py
- `Popen.wait()` is [known](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait) to cause deadlocks when used in conjunction with pipes. Due to this fact some tests, like `test_fread_from_cmd2`, were constantly hanging on Windows. In this PR we adjust `fread()` not to call `Popen.wait()`.
- minor fix in the `terminal.py` to prevent it from hanging when used in the multiprocessing pool. Python terminal class is going to be fully replaced by the corresponding C++ code anyways.
WIP for #2301
=> Do not use Popen.wait() in fread

docs/releases/v0.11.0.rst, src/core/column_from_python.cc, src/datatable/xls.py, tests/fread/test_xls.py, tests/models/test_ftrl.py, tests/test_dt_create.py, tests/test_dt_stats.py
- When creating a frame from list of mixed types containing bools/ints/floats and also strings, the resulting column will now have string type instead of object type. This is consistent with how fread reads CSV files, and also with the semantics of rowbinding.
- When reading an Excel file we now parse datetime and boolean values correctly.
Closes #1701
=> Read Excel date values

src/datatable/utils/terminal.py
Check if `sys.__stdin__` and `sys.__stdout__` are open, before querying them. This seems to fix terminal hangs in a multiprocessing pool.
=> Fix terminal hangs in a multiprocessing pool

ci/xbuild/compiler.py, tests/test_parallel.py
Using `with` statement, when working with the multiprocessing pool in `test_parallel.py::test_multiprocessing_threadpool`, seems to fix hangs in Python 3.8, as it properly closes the pool at exit.
=> Use `with` when working with the multiprocessing pool

src/core/column.cc, src/core/column.h, src/core/datatablemodule.cc, src/core/datatablemodule.h, src/core/expr/eval_context.cc, src/core/sort.cc, src/core/sort.h, src/core/sort_groups.cc, tests/test_dt_sort.py
- Column materialization is adjusted so that a non-virtual column which has refcount>1 wouldn't get copied needlessly. This should improve the performance of sorting: currently we materialize all columns before using them for sorting/grouping, and during this process we currently accidentally create a copy of the data.
- Fixed the use of `DTDEBUG` macro: this macro is always defined, and equal either 0 or 1. However, using it as `#ifdef DTDEBUG` is incorrect, it should be `#if DTDEBUG` instead. Because of this misunderstanding, we were including some code that was meant for debug builds only into production, specifically code for tracking/untracking all memory allocation. After this fix we expect the performance to improve, especially the sort function which allocates many memory ranges …
=> Fix sort-related issues

src/core/column/column_impl.cc, src/core/column/column_impl.h, src/core/expr/head_reduce_binary.cc, src/core/expr/head_reduce_unary.cc
Groupby operator is relatively expensive; when materializing such column we should assign each thread per row (row=group) and use dynamic scheduling.
Instead we were using standard "static batched" schedule, which essentially was causing single-threaded evaluation if the number of group wasn't very big.
This PR fixes the problem.
Closes #2325
=> Improve performance of groupby operation

docs/f-expressions.rst, docs/using-datatable.rst
This PR adds small fixes to naming conventions in the online documentation, namely:
* examples using the variable `df` to represent a datatable were renamed to `DT`, in order to remain consistent with the examples on the [getting started page](https://datatable.readthedocs.io/en/latest/quick-start.html), and avoid being confused with the convention used for pandas dataframes;
* the variable `filter` in the [f-expressions page](https://datatable.readthedocs.io/en/latest/f-expressions.html) was renamed to `filter_price`, in order to avoid overshadowing of Python's built-in `filter` function.
=> Improve naming consistency in online documentation

ci/ext.py, docs/releases/v0.11.0.rst, tests/test_dt.py
Added 2 new fields into the `dt.build_info` struct: 
- `.git_date` is the UTC timestamp of the git revision from which that version of datatable was built. This field is useful to be able to quickly understand how old a particular version of datatable is. The `.build_date` is insufficient because it is possible to have a recent build of an old commit. 
- `.git_diff` contains short diff of the working directory compared to its HEAD revision. Normally this field will be empty. This field is useful to identify whether the the datatable was built on top of the `.git_revision` commit, or whether it was based on a modified source (and if so, which files were modified).
=> Added .git_date and .git_diff to dt.build_version

docs/releases/v0.11.0.rst, src/core/frame/py_frame.cc, src/core/frame/py_frame.h, src/core/python/xobject.cc, src/core/python/xobject.h, src/datatable/fread.py, tests/test_dt.py
The "length" of a Frame is its number of columns, consistent with how the frame expands under `[*DT]` or `{**DT}`. The implementation of `__len__()` will allow the Frame to interoperate easier with python libraries.
=> Allow `len(DT)` syntax to work

src/core/expr/head_reduce_unary.cc
- When groupby contains many very small groups, prefer computing using static instead of dynamic scheduler.
Closes #2362
=> Adjust complexity calculation for groupby

src/core/datatablemodule.cc, src/core/lib/mman/mman.cc, src/core/lib/mman/mman.h, src/core/utils/terminal/terminal.cc, src/core/utils/terminal/terminal.h
Take into account the `MAP_PRIVATE` flag in the page and file protection routines of mman. This fixes memory mapping functionality when working with the `.jay` files on Windows.
Also fix color rendering in Windows terminal that was broken since #2361.
WIP for #2301
=> Fix memory mapping on WIndows

docs/releases/v0.11.0.rst, src/core/column/column_impl.cc, src/core/column/column_impl.h, src/core/column/sentinel_fw.h, src/core/column/sentinel_str.h, src/core/frame/rbind.cc, src/core/parallel/string_utils.cc, tests/munging/test_rbind.py
When multiple str32 columns are rbinded, the combined character data buffers may exceed 2GB in size. In this case the resulting str32 column must be converted into str64.
Closes #2367
=> Rbind many str32 columns may create a str64 column

src/core/sort.cc, src/core/sort/common.h, src/core/sort/grouper.h, src/core/sort/insert-sort.h, src/core/sort/newsort.cc, src/core/sort/radix-sort.h, src/core/sort/sorter.cc, src/core/sort/sorter.h, src/core/sort/sorter_bool.h, src/core/sort/sorter_int.h, src/core/sort/sorter_multi.h, src/core/sort/sorter_raw.h, src/core/utils/function.h, tests/ijby/test-sort.py, tests/test-groups.py, tests/test_options.py
This is an update to new sorting functionality.
Currently works for boolean columns only; however supports both virtual and material boolean columns directly.
Added an option `dt.options.sort.new = False`, which controls whether the new algo is used or not (default). 
Preliminary tests show that for a 100M-rows boolean column the sorting time goes down from ≈0.4s to ≈0.3s, owing to the fact that the initial "data preparation" step is skipped.
=> Update to new-sort

docs/releases/v0.11.0.rst, src/core/frame/__init__.cc, src/datatable/types.py, tests/frame/test-create.py
When creating a Frame from a python list, it is now possible to explicitly specify the stype of the resulting column by "dividing" the list by the type you need:
```
dt.Frame(A=[1, 5, 10] / dt.int64,
B=[0, 0, 0] / dt.float64)
```
=> Allow dividing a python list by an stype

docs/releases/v0.11.0.rst, src/core/frame/to_csv.cc, src/core/python/args.cc, src/core/utils/file.cc, src/core/utils/file.h, src/core/write/csv_writer.cc, src/core/write/output_options.h, src/core/write/write_manager.cc, src/core/write/write_manager.h, tests/test_tocsv.py
Added argument `bom=False` to the `Frame.to_csv()` method. This argument controls whether or not to write BOM (Byte-Order Mark) into the output csv file.
Closes #2379
=> Implement the BOM mark for .to_csv()

docs/releases/v0.11.0.rst, src/core/write/csv_writer.cc, tests/test_tocsv.py
The error was due to not properly accounting for space needed to write the quote  marks.
Closes #2382
=> Fix crash in .to_csv(quoting=all)

src/core/frame/rbind.cc, tests/munging/test_rbind.py
Strings in Python are iterable and each string character is a string again, hence, iterable. This caused an infinite recursion when processing arguments in `rbind()`. In this PR we fix this issue and add some relevant tests. 
Closes #2384
=> Fix rbind crashing on Python strings

docs/releases/v0.11.0.rst, src/core/frame/rbind.cc, src/core/python/iter.cc, src/core/python/iter.h, src/core/set_funcs.cc, tests/munging/test_rbind.py, tests/test_sets.py
The issue of `dt.rbind("string")` was fixed in #2385; but there are other kinds of arguments that could still cause infinite recursion. This PR addresses that.
Closes #2386
=> Fix possible infinite recursion in dt.rbind()/dt.union()

src/core/csv/py_csv.cc, src/core/csv/reader.cc, src/core/csv/reader.h, src/core/frame/to_csv.cc, src/core/python/arg.h, src/core/python/tuple.cc, src/core/read/py_read.cc, src/datatable/__init__.py, src/datatable/fread.py, src/datatable/utils/fread.py, tests/fread/test_fread_api.py, tests/test_utils_misc.py
Previously we had `fread()` function in fread.py creating an object of class `GenericReader`, which in turn called C++ `core.gread()` function which did the actual reading.
Now the first 2 steps are removed, and `core.gread()` became the new `fread` function. The file "fread.py" moved to "utils/fread.py" after heavy editing -- it is no longer useful for any external purpose, and eventually will be removed once we replace the remaining code with C++ equivalents.
WIP for #1832
=> Reduce too many levels of indirection in fread

docs/api/frame.rst, docs/api/frame/source.rst, docs/releases/v0.11.0.rst, src/core/csv/reader.cc, src/core/csv/reader.h, src/core/frame/__getitem__.cc, src/core/frame/__init__.cc, src/core/frame/py_frame.cc, src/core/frame/py_frame.h, src/core/frame/replace.cc, src/core/jay/open_jay.cc, src/core/python/obj.cc, src/core/python/obj.h, src/core/read/multisource.cc, src/core/read/source.h, src/datatable/utils/fread.py, src/datatable/xls.py, tests/frame/test-copy.py, tests/fread/test_fread_api.py, tests/fread/test_fread_issues.py, tests/fread/test_xls.py, tests/ijby/test-assign.py, tests/munging/test_replace.py, tests/test_jay.py
Added new frame property: `Frame.source`. This contains the name of the file where the frame was loaded from. In some other cases it may contain a generic descriptor: `"<file>"`, `"<text>"`, `"<pickle>"` if the source cannot be identified more precisely.
The property is read-only. It will clear if the frame is modified after being loaded.
=> Frame.source

src/datatable/utils/fread.py, tests/conftest.py, tests/fread/test_fread_api.py, tests/models/test_aggregate.py, tests/test_jay.py, tests/test_tocsv.py
Fix misc tests on Windows by
- using `os.path.join()` as much as possible in `fread` function and the relevant tests;
- using `pathlib` when creating local URL's;
- using `newline="\n"` when opening files in python;
- using a context manager when working with the zip files;
- deleting memory-mapped files only after the corresponding frames have been deleted.
Also, on Windows temporarily disable `test_fread_from_fileobj` test, that kills the entire pytest session when launched.
WIP for #2301
=> Fix misc tests on Windows 

appveyor.yml, ci/Jenkinsfile.groovy, tests/__init__.py, tests/conftest.py, tests/fread/test_fread_issues.py, tests/fread/test_fread_small.py, tests/test_tocsv.py
Not all the platforms have a proper long double type that is used by fread to convert double literals into double numbers. In this PR we make use of platform specific tolerances for Windows and PowerPC64 that allow certain fread tests to not fail. 
Also, set up AppVeyor config file to launch tests for every Windows build.
WIP for #2301
=> Use platform specific tolerance in certain fread tests

src/core/csv/reader.cc, src/datatable/utils/fread.py, tests/fread/test_fread_api.py
Right now to read data from a file object, datatable needs a file descriptor to be used on the C++ side. Since file descriptors are not native to all the platforms, this functionality doesn't work on Windows. Some workarounds are possible, however, since this feature is not so widely used, in this PR we temporarily disable it on Windows and throw `NotImplementedError` instead.
Closes #2301
=> Disable freading from file-like objects on Windows

tests_random/attacker.py, tests_random/metaframe.py, tests_random/utils.py
Remove python code generation from random attacker; replaced with more detailed logging.
The reason for this change is that the effort required to maintain this functionality far outweighs its benefits.
=> No pycode in random attacker

ci/ext.py
This seems to provide some benefits to multithreaded libraries, according to https://stackoverflow.com/questions/2127797
=> Add -pthread compile/link flag

ci/Jenkinsfile.groovy
The `--prefer-binary` pip flag (available from pip-18.0) will prevent pip from using newer source distributions when slightly older binaries are  available. This will prevent Jenkins from trying to rebuild pandas/numpy from source every time those packages release new versions.
=> On PPC64 builds prefer installing from wheels

docs/releases/v0.11.0.rst, src/core/frame/__init__.cc, src/core/python/obj.cc, src/core/python/obj.h, tests/frame/test-create.py
`dt.Frame(df)` no longer throws an error if pandas DataFrame `df` contains Categorical columns. Those columns will be converted to string columns instead.
Closes #2407
=> Create Frame from pandas Categorical

appveyor.yml, ci/xbuild/logger.py, ci/xbuild/wheel.py
- improve `ABI` detection in xbuild to allow building wheels on Windows;
- build/test wheels for all the Python versions on AppVeyor.
Closes #2432
=> Support building wheels on Windows

src/core/_dt.h, src/core/csv/fread.cc, src/core/csv/reader_fread.cc, src/core/csv/reader_fread.h, src/core/csv/reader_parsers.cc, src/core/csv/reader_parsers.h, src/core/jay/save_jay.cc, src/core/read/fread/fread_parallel_reader.cc, src/core/read/fread/fread_parallel_reader.h, src/core/read/fread/fread_thread_context.cc, src/core/read/fread/fread_thread_context.h, src/core/read/fread/fread_tokenizer.cc, src/core/read/parse_context.cc, src/core/read/parse_context.h, src/core/read/thread_context.cc, src/core/read/thread_context.h, src/core/write/write_manager.cc, src/core/writebuf.cc, src/core/writebuf.h, src/core/wstringcol.cc, tests/fread/test_fread_issues.py, tests/fread/test_fread_small.py
- Moved non-fread-specific functions from FreadThreadContext into the parent class;
- `FreadTokenizer` class renamed into `ParseContext` (so that it can be reused in places other than fread);
- Refactor string parsing code into separate parsers for each QR;
- Code style changes in "writebuf.*"
=> csv-reading refactoring

requirements_docs.txt
The latest sphinx `3.0.3` seems to be [incompatible](https://readthedocs.org/projects/datatable/builds/11101225/) with our docs. While we are researching this issue, temporarily downgrade sphinx on readthedocs. Any version prior to `3.0` will work just fine.
=> Temporarily downgrade sphinx  on readthedocs

docs/install.rst, src/core/csv/fread.cc, src/core/csv/reader_fread.cc, src/core/read/fread/fread_parallel_reader.cc, src/core/read/fread/fread_thread_context.cc, src/core/read/fread/fread_thread_context.h, src/core/read/parse_context.cc, src/core/read/parse_context.h, src/core/read/parsers/parse_string.cc, src/core/read/thread_context.cc, src/core/writebuf.cc, src/core/writebuf.h, tests/fread/test_fread_issues.py
The issue was that the mutex in `MemoryWritableBuffer` was acquired too often, causing major slowdown as multiple threads were trying to access it at the same time. The solution was to create a helper `Writer` class that acquires the mutex for the duration of multiple writes (note: this doesn't cause unnecessary contention, since the lock is acquired in "read-only" mode, and multiple threads can do that at the same time).
In addition, `ParseContext` now uses simple `Buffer` instead of `MemoryWritableBuffer` for its string content. That buffer is cleared when we start reading a chunk.
Also: `ParseContext.anchor` was removed, since it is no longer needed.
Closes #2458
=> Fix slow reading of string columns by fread

docs/releases/v0.11.0.rst, src/core/csv/reader_parsers.cc, src/core/csv/reader_parsers.h, src/core/frame/cast.cc, tests/munging/test_cast.py
Implemented conversion of string columns into `bool`, `int8`, `int16`, `int32`, `int64`, `float32` and `float64`. If invalid values are encountered, they become NAs. When converting integer strings that are larger than can be fit in the target stype, the behavior is undefined: some values may be wrap-around, even larger ones may be turned into NAs. This may change in the future.
Closes #1313
=> Str->numeric converters

docs/releases/v0.11.0.rst, src/core/expr/head_literal_sliceall.cc, tests/test-groups.py
Within a groupby, symbol `f[:]` will now exclude any group columns.
Closes #2460
=> f[:] within a groupby

docs/releases/v0.11.0.rst, src/core/frame/to_csv.cc, src/core/jay/save_jay.cc, src/core/python/arg.cc, src/core/python/arg.h, src/core/python/args.cc, src/core/python/args.h, tests/test_tocsv.py
- Created ability to specify argument synonyms in `py::PKArgs`;
- Arguments `_strategy=` in `.to_csv()` and `.to_jay()` are renamed into `method=`;
+ The idea here is that (1) an argument's name really shouldn't start with an underscore. And the only reason why it did up to now is because this was intended as a "hidden" argument, not visible to users. But seems like this is not how it ended up... Secondly, the name "method" seems to be more appropriate here, because there is hardly anything strategic in the underlying algorithm. 
+ Previous argument name is still accepted, and means the same as `method=` (thus, this is not a breaking API change).
- Argument `header=` in `.to_csv()` now accepts the value `"auto"`, which is the default. 
Previously, the default value was `...` (Ellipsis). …
=> Adjustments to docs/api of Frame.to_csv()

src/core/frame/names.cc
For some reason the docs are saying `nrows` when really it is `ncols`.
=> Fix documentation of Frame.colindex()

src/core/buffer.cc, src/core/datatablemodule.cc, src/core/datatablemodule.h, src/core/py_buffers.cc, src/core/sort.cc, src/core/utils/alloc.cc, src/core/wstringcol.cc
The macros are no longer in use. Instead we use AddressSanitizer to detect leaks.
=> Remove macros TRACK/UNTRACK

docs/api/api-index.rst, docs/api/dt/fread.rst, docs/api/dt/iread.rst, docs/index.rst, docs/releases/v0.11.0.rst, src/core/csv/reader_fread.cc, src/core/read/output_column.cc, src/core/read/py_fread.cc, src/datatable/sphinxext/xfunction.py, src/datatable/utils/fread.py, tests/fread/test_fread_api.py, tests/fread/test_fread_large.py, tests/fread/test_fread_small.py
- Fixed few minor bugs related to streaming reading in fread;
- The "streaming read" functionality is now officially released, as announced in the release notes;
- The "large fread tests" now run under the memory limit of 2Gb in order to test the functionality of `memory_limit` parameter;
- Added documentation for fread() and iread();
- `save_to=` parameter in fread removed. This parameter was declared but not used, so no reason to keep it;
Closes #75
Closes #1750
=> Finish fread-to-file functionality; added documentation

src/core/column/sentinel_fw.cc, src/core/frame/replace.cc, src/core/parallel/monitor_thread.cc, src/core/parallel/monitor_thread.h, src/core/parallel/semaphore.h, src/core/python/xobject.h, src/core/utils/assert.h, src/core/utils/macros.h, src/core/utils/misc.cc, src/core/utils/misc.h, src/core/writebuf.cc
- Defined macros `DISABLE_CLANG_WARNING(N)`, `DISABLE_GCC_WARNING(N)`, `DISABLE_MSVC_WARNING(N)` and corresponding `RESTORE_*` macros, to reduce the amount of boilerplate needed to switch off a warning for a portion of code;
- Renamed `DT_OS_DARWIN` -> `DT_OS_MACOS`;
- Rename member variables in class `monitor_thread`;
=> Macros for compiler warnings handling

src/core/python/args.cc, src/core/stype.h, src/core/utils/assert.h
Removes warnings such as
```
In file included from src/core/expr/fnary/rowcount.cc:26:
src/core/column/func_nary.h:81:22: warning: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Wextra-semi-stmt]
XAssert(evaluator_);
```
as well as tries to address
```
src/core/stype.h:243:29: warning: no previous extern declaration for non-static variable '_sfr<bool>' [-Wmissing-variable-declarations]
template <> constexpr SType _sfr<bool> = SType::BOOL;
```
=> Fix some compiler warnings produced by Clang-10

.travis.yml, ci/xbuild/compiler.py
- configure Travis to make builds with Clang7 and Clang10 on Linux;
- fix a linker bug when `CC` or `CXX` environment variables are present.
=> Add Clang Travis builds

src/core/expr/eval_context.cc, tests/test_parallel.py, tests_random/metaframe.py
=> Properly escape column name in an error message

docs/releases/v0.11.0.rst, src/core/parallel/thread_pool.cc, src/core/parallel/thread_worker.cc, tests/test_parallel.py
The fork handler was changed so that now all threads are stopped and joined before the fork.
Closes #2438
=> Shut down threads during forking

docs/develop/documentation.rst, docs/releases/v0.10.0.rst, docs/releases/v0.11.0.rst, docs/releases/v0.2.1.rst, docs/releases/v0.2.2.rst, docs/releases/v0.3.1.rst, docs/releases/v0.4.0.rst, docs/releases/v0.6.0.rst, docs/start/quick-start.rst, docs/start/using-datatable.rst
A minor consistency change: do not use spaces around slashes, if a particular slash separates two words.
=> Minor adjustment to the docs format

src/core/parallel/api.h, src/core/parallel/monitor_thread.cc, src/core/parallel/monitor_thread.h, src/core/parallel/parallel_for_ordered.cc, src/core/parallel/parallel_for_static.h, src/core/parallel/thread_pool.cc, src/core/parallel/thread_pool.h, src/core/parallel/thread_worker.cc, src/core/progress/progress_bar.cc, src/core/progress/progress_manager.cc, src/core/progress/progress_manager.h, src/core/utils/logger.cc, src/core/utils/temporary_file.cc
- `monitor_thread` is disabled for now, in order to check whether it has any effect on datatable's stability;
- without the monitor thread, the race condition in #2510 should no longer occur;
- `python_mutex` is converted into an `std::recursive_mutex`, in order to avoid potential deadlocks on the main thread;
If extensive testing shows this approach to be more viable than the previous ones, we'll remove the monitor thread's code entirely. For now it is merely commented out.
Closes #2510
=> Temporarily disable monitor thread

src/core/py_buffers.cc, tests/frame/test-create.py
It is perfectly valid for the last `offset` to be equal to the size of `strbuf`.
Closes #2517
=> Fix faulty assert in py_buffers

src/core/models/dt_ftrl.cc, src/core/parallel/parallel_for_static.h
- fix predict progress in FTRL;
- add interrupts check to the `nested_for_static` (follow-up for #2516).
Closes #2519
=> Fix predict progress in FTRL, adjust nested_for_static

src/core/parallel/thread_team.cc, src/core/parallel/thread_worker.cc, src/core/progress/progress_manager.cc
The problem may happen if some of the threads arrive at a barrier, while some other thread throws an exception. In such a case the threads at a barrier will be left waiting forever...
This fixes test `tests/test_parallel.py::test_progress_interrupt[nested-6]`.
=> Fix deadlock in barrier when an exception occurs

docs/releases/v0.11.0.rst, src/core/datatablemodule.cc, src/core/options.cc, src/core/utils/exceptions.cc, src/core/utils/exceptions.h, src/datatable/__init__.py, src/datatable/options.py
Previously, we had function `init()` in exceptions.cc trying to initialize exception objects when they were first needed (i.e. when an exception was first thrown). However, because this was not done in thread-safe manner, it was possible to get a situation when multiple threads are trying to initialize those exception objects at the same time, resulting in undefined behavior, up to and including a segfault.
In order to avoid this, now we initialize all exception objects upon module import (in the special "after-import" stage), when no threads are in play, and consequently there is no possibility for any race conditions.
In addition, initialization of python `options` object moved to `__init__.py` in order to make the initialization sequence more well-defined.
Closes #2526
=> Exception initialization is now done at datatable import

ci/headers.py, src/core/_dt.h, src/core/csv/reader_parsers.h, src/core/frame/__repr__.cc, src/core/lib/flatbuffers/stl_emulation.h, src/core/lib/parallel_hashmap/phmap.h, src/core/lib/parallel_hashmap/phmap_base.h, src/core/lib/parallel_hashmap/phmap_utils.h, src/core/models/py_ftrl.cc, src/core/parallel/semaphore.h, src/core/python/args.h, src/core/python/dict.h, src/core/python/iter.h, src/core/rowindex.h, src/core/stats.h, src/core/utils/assert.h, src/core/utils/function.h, src/core/utils/logger.cc, src/core/utils/logger.h, src/core/utils/misc.cc, src/core/utils/wcwidth.cc
Created a script that can scan all source files for the presence of `std::` symbols, and then check whether the corresponding standard library headers were included.
This can be used to detect the situation where a certain symbol from the standard library is used without the header, and it isn't detected by the compiler because that symbol is transitively included from some other standard library. However, when trying to compile with a different compiler that uses different standard library version or implementation that symbol may end up no longer transitively included, resulting in a compilation error. 
Previously we hit this problem multiple times, and so this script is intended to prevent it from happening.
The script needs to be run manually. It contains the list of "known" standard …
=> Script for checking standard library headers

src/core/writebuf.cc
The bug was introduced in one of the recent commits. The issue was that `data_` was read outside of the protection of a mutex, which means it could have been modified from another thread. 
Closes #2532
=> Fix issue 2532

docs/_static/xcode.css, docs/conf.py, docs/develop/contrib.rst, docs/develop/documentation.rst, docs/start/install.rst, docs/start/quick-start.rst, requirements_docs.txt, src/datatable/sphinxext/xcode.py
The new directive should be used for all code blocks with shell commands, e.g:
```rst
.. xcode:: shell
$ pip install datatable
```
Unlike the traditional `.. code-block::` we have full control over lexing / styling the final output. In particular, with this patch the shell prompt is distinct from the rest of the command line; and it is also marked with `user-select: none` in CSS, meaning it won't get in the way when a user tries to copy the commands.
Most importantly, we will extend the `.. xcode::` directive in the future to python languages, in particular allowing for automatic detection of datatable frames in the output.
=> Created ..xcode::shell Sphinx directive

ci/Jenkinsfile.groovy
When publishing artifacts to S3, we will now generate links to those artifacts and put those links into https://h2o-release.s3.amazonaws.com/datatable/index.html. This file acts as a simple python repository, allowing one to install one of the latest dev wheels. 
Closes #952
=> Auto-generate links to artifacts published on S3

src/core/column.cc, src/core/column/column_impl.h, src/core/column/rbound.h, src/core/column/sentinel.h, src/core/column/virtual.h, src/core/jay/save_jay.cc, tests/test_jay.py
When an rbound string column was saved to Jay, the offsets were not properly concatenated, creating a corrupted column.
Closes #2543
=> Fix saving an Rbound string column to Jay

docs/releases/v0.11.0.rst, src/core/buffer.cc, src/core/buffer.h, src/core/read/source.cc, tests/test_jay.py
Before, when fread was given a string/bytes object, we were creating a `Buffer::external` view on that object, and then read that data. This worked fine when reading CSVs, but if the file in fact is a Jay file, then we end up creating columns that are direct views on that data. These columns are then put together in a Frame and returned to the user. The problem is that `Buffer::external` is not designed for long-term data storage: it does not own its memory region. So, when the original bytes object is gc'd, we end up with a Frame that contains dangling pointers. 
Now, I've created a new type of `Buffer`: `PyBytes_BufferImpl`, which keeps the source py object inside it, ensuring that the memory region wouldn't get deallocated prematurely.
The impact of this bug is uncler: on one hand, …
=> Fix loading a Frame from a temporary bytes Jay object

docs/api/frame.rst, docs/conf.py, requirements_docs.txt, src/datatable/sphinxext/xfunction.py
Use `PythonDomain.note_object()` instead of manipulating domain's data explicitly.
As a side-effect, this change is incompatible with Sphinx prior to version 3.0 (there was no `node_id=` back then). So, whoever works on documentation will need to upgrade their Sphinx installation.
=> Make ..xfunction compatible with Sphinx 3

requirements_docs.txt, src/datatable/sphinxext/xcode.py
By default readthedocs installs old versions of pygments and sphinx_rtd_theme plugins, which causes inconsistencies in documentation style.
=> Upgrade pygments and sphinx_rtd_theme versions

docs/releases/v0.11.0.rst, src/core/python/dict.cc, src/core/python/dict.h, src/core/read/source.cc, src/datatable/utils/fread.py
If the user passes a URL with unsafe characters (such as spaces) to fread, then such URLs will now be read correctly. For example:
```
import datatable as dt
dt.fread("https://github.com/OpportunityInsights/EconomicTracker/raw/main/data/Google Mobility - County - Daily.csv")
```
=> Encode unsafe characters in URLs passed to fread

ci/ext.py, src/core/column/qcut.h, src/core/column/rbound.cc, src/core/column_from_python.cc, src/core/csv/reader_fread.cc, src/core/expr/fnary/rowmean.cc, src/core/expr/fnary/rowsd.cc, src/core/expr/head_reduce_binary.cc, src/core/expr/head_reduce_unary.cc, src/core/lib/zlib/adler32.cc, src/core/lib/zlib/deflate.cc, src/core/lib/zlib/deflate.h, src/core/lib/zlib/trees.cc, src/core/lib/zlib/zutil.h, src/core/models/aggregator.cc, src/core/models/dt_ftrl.cc, src/core/models/dt_ftrl.h, src/core/models/utils.h, src/core/py_buffers.cc, src/core/read/parallel_reader.cc, src/core/read/preframe.cc, src/core/stats.cc, src/core/utils/misc.cc, src/core/write/write_manager.cc
After switching to the recent version of Clang compiler, there were over 1000 warnings, mostly from the `-Wimplicit-int-float-conversion` category. These warning are now fixed and the source compiles cleanly with the recent Clang.
=> Fix warnings produced by Clang 10

docs/api/dt/qcut.rst, requirements_docs.txt
- Due to a bug in Sphinx, version 3.2.0 cannot be used to build our documentation, so we exclude it in the requirements file;
- Added missing file `qcut.rst`.
Closes #2568
=> Do not use Sphinx 3.2.0 for doc builds

src/core/tests/test_atomic.cc
The error appears when the number of threads is large, and therefore repeated division may accumulate error beyond 4 ulps.
=> Attempt to fix an error in test_atomic

src/core/buffer.cc, src/core/parallel/semaphore.h, src/core/utils/macros.h, src/core/utils/misc.h
These minor changes allow successful compilation on FreeBSD. "gmake test" only fails `test_save_double2`, which doesn't look serious:
`E           AssertionError: assert ['1.0e-307', ....0e-302', ...] == ['1.0e-307', ....0e-302', ...]`
`E             At index 4 diff: '1.0000000000000001e-303' != '1.0e-303'`
`E             Use -v to get the full diff`
=> Add checks to allow compilation on FreeBSD

src/core/models/aggregator.cc, src/core/models/aggregator.h, tests/models/test_aggregate.py
Right now for ND aggregation we automatically adjust radius, so that we gather not more than `nd_max_bins` exemplars. In some data experiments a fixed radius aggregation could also be useful. In this PR we expose the aggregation radius as an additional parameter of the `aggregate()` function.
=> Allow ND aggregations with a fixed radius

docs/develop/create-fexpr.rst, src/core/_dt.h, src/core/call_logger.cc, src/core/call_logger.h, src/core/datatablemodule.cc, src/core/datatablemodule.h, src/core/expr/fexpr_cut.cc, src/core/expr/fexpr_ifelse.cc, src/core/expr/fexpr_qcut.cc, src/core/python/arg.cc, src/core/python/arg.h, src/core/python/args.cc, src/core/python/args.h, src/core/python/dict.h, src/core/python/xargs.cc, src/core/python/xargs.h, tests/expr/test-cut.py, tests/expr/test-ifelse.py, tests/expr/test-qcut.py
Added new class `py::XArgs`, as a replacement for current `py::PKArgs`.
This new class is used together with the `DECLARE_PYFN` macro like this:
```
DECLARE_PYFN(&py_gcd)
->name("gcd")
->docs(doc_gcd)
->arg_names({"a", "b"})
->n_positional_args(2)
->n_required_args(2);
```
Compared to our current approach with `PKArgs`, this has several advantages:
- the arguments are named explicitly, making it easy to understand what each means;
- the arguments that you don't need don't have to be specified;
- this system is more extensible: new arguments can be added without having to change every existing `PKArgs` variable;
- **it is more automatic**: there is no need to declare anything in the `DatatableModule` module -- the declared function will be attached to the module automatically.
- **new …
=> py::XArgs class

docs/api/math.rst, docs/api/math/round.rst, docs/releases/v0.11.0.rst, src/core/expr/fexpr_func_unary.cc, src/core/expr/fexpr_func_unary.h, src/core/expr/fexpr_round.cc, src/datatable/math.py, tests/expr/math/test-round.py
The function is equivalent to standard python's `round()`. It allows rounding to the specified number of decimal digits (see the included documentation for details). 
Closes #2285
=> Implement function round()

tests/expr/fbinary/test-add.py, tests/expr/fbinary/test-floordiv.py, tests/expr/fbinary/test-mod.py, tests/expr/fbinary/test-mul.py, tests/expr/fbinary/test-pow.py, tests/expr/fbinary/test-sub.py, tests/expr/fbinary/test-truediv.py
This set of tests covers the basic binary operations on columns and scalars, it is not fully comprehensive though.
=> Expand tests for binary operations

docs/api/models/Ftrl/__init__.rst, docs/api/models/Ftrl/alpha.rst, docs/api/models/Ftrl/beta.rst, docs/api/models/Ftrl/colname_hashes.rst, docs/api/models/Ftrl/colnames.rst, docs/api/models/Ftrl/double_precision.rst, docs/api/models/Ftrl/feature_importances.rst, docs/api/models/Ftrl/fit.rst, docs/api/models/Ftrl/interactions.rst, docs/api/models/Ftrl/labels.rst, docs/api/models/Ftrl/lambda1.rst, docs/api/models/Ftrl/lambda2.rst, docs/api/models/Ftrl/mantissa_nbits.rst, docs/api/models/Ftrl/model.rst, docs/api/models/Ftrl/model_type.rst, docs/api/models/Ftrl/model_type_trained.rst, docs/api/models/Ftrl/nbins.rst, docs/api/models/Ftrl/negative_class.rst, docs/api/models/Ftrl/nepochs.rst, docs/api/models/Ftrl/params.rst, docs/api/models/Ftrl/predict.rst, docs/api/models/Ftrl/reset.rst, docs/api/models/ftrl.rst, src/core/models/py_ftrl.cc, tests/expr/fbinary/test-pow.py, tests/models/test-ftrl.py
- create FTRL reference under the API section;
- overall improvement of FTRL docs, though it may still lack some info on exceptions.
Also, with the new system I'm not sure what is the best way to document the named tuples `FtrlParams` and `FtrlFitOutput`, that we use in `Ftrl` class.
WIP for #2586
=> Convert FTRL docs to xfunction/xclass format

src/core/frame/to_numpy.cc
When creating a numpy array, numpy provides a variety of parameter options, including Specify the memory layout of the array.Because the datatable frame is based on column storage, I found that if specified as fortran order, the performance will be improved.
The performance of `np.asfortranarray`  relative to `np.array` can be improved by about 40%, especially on large frames.
Generated a simple frame test, the overall performance of to_numpy on my machine can be improved by 20%.
`letters = "abcdefghijklmn"`
`n = 10000000`
`col0 = [random.choice([True, False]) for _ in range(n)]`
`col1 = [random.randint(-100, 100) for _ in range(n)]`
`col2 = [random.choice(letters) for _ in range(n)]`
`col3 = [random.random() for _ in range(n)]`
`DT0 = dt.Frame([col0, col1, col2, col3,`
` …
=> Change np.array to np.asfortranarray in to_numpy for performance

docs/_static/xfunction.css, src/datatable/sphinxext/xfunction.py, src/datatable/sphinxext/xnodes.py
This PR allows to declare multiple parameters at once in the "parameters" section of documentation, e.g.
```
Parameters
----------
x, y, z: float
(description of parameters)
```
WIP for #2605
=> Handle multi-params in function 'Parameters' section

docs/_static/xfunction.css, src/datatable/sphinxext/xfunction.py
This is a follow up for https://github.com/h2oai/datatable/pull/2620#issuecomment-692892056
=> Fix style of multi-params in documentation

docs/api/dt/build_info.rst, docs/api/index-api.rst, docs/api/ltype.rst, docs/api/ltype/__new__.rst, docs/api/ltype/stypes.rst, docs/api/stype.rst, docs/api/stype/__call__.rst, docs/api/stype/__new__.rst, docs/api/stype/ctype.rst, docs/api/stype/dtype.rst, docs/api/stype/ltype.rst, docs/api/stype/max.rst, docs/api/stype/min.rst, docs/api/stype/struct.rst, src/datatable/sphinxext/xfunction.py, src/datatable/types.py, tests/test-docs.py
- Added documentation for classes `stype` and `ltype`;
- Implemented extracting docstrings from python code;
- Allow possibility to have a method/function without the source (this allows the docs for `.build_info` to build properly).
WIP for #2586
Closes #2628
Closes #2633
=> Documentation for stype/ltype

docs/api/index-api.rst, docs/api/internal.rst, docs/api/internal/compiler_version.rst, docs/api/internal/frame_column_data_r.rst, docs/api/internal/frame_columns_virtual.rst, docs/api/internal/frame_integrity_check.rst, docs/api/internal/get_thread_ids.rst, docs/api/internal/in_debug_mode.rst, docs/api/internal/regex_supported.rst, docs/conf.py, src/core/datatablemodule.cc, tests/munging/test-cbind.py, tests/munging/test-dt-combo.py, tests/test-dt.py
- Create documentation for the function in the `datatable.internal.` module;
- Adjusted permalink URLs so that they would be based off the HEAD commit instead of master. This means that in order for the links to work one would need to commit and push the local changes to GitHub first.
WIP for #2586
=> Documentation for internal. submodule

src/core/csv/reader.cc, src/core/csv/reader.h, src/core/read/multisource.cc, src/core/read/multisource.h, src/core/read/py_fread.cc, src/core/read/py_read_iterator.cc, src/core/read/py_read_iterator.h
Class `MultiSource` simplified:
- removed several unused constructors;
- the `reader` is now owned by MultiSource instead of passing it as a parameter every time;
- `ReadIterator` no longer needs to own the `reader`;
- renamed `iteration_index` -> `iteration_index_`.
=> Code cleanup in fread

tests/test-docs.py
When we do `make sdist` we do not include the `docs/api` folder, but we do include all the tests meaning that the `test-docs.py` is also included. Since we don't want this test to fail for no reason, in this PR we disable it, as it will otherwise fail when no `docs/api` folder is present on the system.
=> Do not test API docs if API path doesn't exist

docs/manual/comparison_with_rdatatable.rst, docs/releases/v1.0.0.rst, src/core/column/ifelsen.cc, src/core/column/ifelsen.h, src/core/expr/fexpr_ifelse.cc, src/core/expr/workframe.cc, src/core/expr/workframe.h, src/core/python/xargs.cc, src/core/python/xargs.h, src/datatable/sphinxext/xfunction.py, tests/expr/test-ifelse.py
New ifelse() function allows chained evaluation of several conditions, making it the equivalent of SQL's CASE WHEN.
- The evaluation is "lazy": only the smallest amount of expressions needed to get the result is computed for each row;
- Both `condition_i` and `value_i` can have unequal but compatible shapes: some of them can be full-sized, others grouped, yet others simple scalars;
- The value columns will be upcasted into the smallest common stype as necessary.
Closes #2656
=> Expanded ifelse() function to allow multiple conditions

ci/Jenkinsfile.groovy
If for whatever reason the directory was deleted, then we should recreate it before starting the job.
=> Create directory /tmp/cores on macOS before running tests

docs/manual/comparison_with_rdatatable.rst
This is in response to a comment on #2611  [link](https://github.com/h2oai/datatable/pull/2611#issuecomment-705817227). 
It shows the difference in row selections between `data.table` and `datable`, when selecting all columns
=> [DOC] update to docs highlighting difference in row selection

docs/releases/v1.0.0.rst, src/core/expr/eval_context.cc, tests/ijby/test-update.py
When a whole column is updated within a `DT[i, j, by()]` call, the stype/ltype of that column us now allowed to change. This is consistent with the same behavior in the absense of `by()`.
Closes #2685
=> Update with by

src/core/models/aggregate.cc
Improve `aggregate()` documentation and get rid of the link to the source code for ND-algo, as that link could easily become a dead link when the aggregator source code changes.
=> Improve aggregator docs

docs/api/frame/__getitem__.rst, src/core/frame/names.cc, src/core/models/aggregate.cc, src/core/models/py_ftrl.cc, src/core/set_funcs.cc, src/core/str/py_str.cc
Use a single exception section on the documentation pages, so that a link to the`#except` anchor would properly reference the whole section.
=> Improve exception sections in the docs

Makefile, docs/releases/v1.0.0.rst, src/core/python/args.cc, src/core/python/xobject.h
It took a long time to figure out, but apparently we were not calling the "free" function of the base type object during the destruction: https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_dealloc
Closes  #2701
=> Fix a memory leak

docs/releases/v1.0.0.rst, src/core/read/input_column.cc, src/core/read/thread_context.cc, tests/fread/test-fread-api.py
I made it so str64 falls back into str32, because implementing a new stype for fread seems excessive at this moment.
Closes #2704
=> Allow str64 in a call to fread

docs/releases/v1.0.0.rst, src/core/expr/fexpr_list.cc, src/core/rowindex_array.cc, tests/munging/test-delete.py
Closes #805 
The rows to be deleted can be an unsorted array.
The array can contain duplicate values. 
Size of the array to be deleted can be larger than the size of the frame as long as the index to be deleted does not exceed the number of rows on the frame.
=> Delete rows from an unsorted array

docs/_static/wren.css
=> Nested menu indicators in the documentation

ci/Jenkinsfile.groovy
New machines, that caused build errors on ppc, are temporarily disabled by @abal5, so in this PR we just revert some docker related changes and make minor improvements to `Jenkinsfile.groovy`.
=> Adjust ppc builds

.travis.yml, docs/api/frame.rst, tests/test-docs.py
This PR creates a test that would  build the documentation with Sphinx and  check that there are no warnings/errors. Since  this test is time-consuming, it needs to be enabled via an environment variable `DT_BUILD_DOCS`. At the moment I've enabled this test on Travis for python 3.6 (it appears that sphinx is much slower under python 3.8).
Closes #2744
=> Automatically build documentation on Travis

docs/_static/code.css, docs/_static/wren.css, docs/_static/xfunction.css, docs/api/frame.rst, docs/api/index-api.rst, docs/develop/index-develop.rst, docs/develop/test.rst
Added a "test page"  for documentation, which collects all kinds of RST markup, so that it can be checked for any rendering inconsistencies whenever we need to change the CSS. The page itself is not actually complete: we need to add  more elements to it in the future.
In this PR we also significantly improve rendering  of various lists (see the examples on the test page).
=> Documentation test page

docs/releases/v1.0.0.rst, src/core/cstring.cc, src/core/cstring.h, src/core/frame/repr/terminal_widget.cc, src/core/frame/repr/terminal_widget.h, src/core/frame/repr/text_column.cc, src/core/frame/repr/text_column.h, tests/frame/test-repr-text.py
Each column's type is displayed under that column's name. In jupyter output the type of each column is already displayed.
For example:
```
|  year  month    day  dep_delay  arr_delay  carrier  origin  dest   air_time  distance   hour
| int32  int32  int32      int32      int32  str32    str32   str32     int32     int32  int32
------ + -----  -----  -----  ---------  ---------  -------  ------  -----  --------  --------  -----
0 |  2014      1      1         14         13  AA       JFK     LAX         359      2475      9
1 |  2014      1      1         -3         13  AA       JFK     LAX         363      2475     11
2 |  2014      1      1          2          9  AA       JFK     LAX         351      2475     19
3 |  2014      1      1         -8        -26  AA       LGA     PBI …
```
=> Show types for a frame in  python console

src/core/utils/misc.cc
The code in that function was really old, left over from C times. With `chrono` library it should now be perfectly inter-operable across different systems. In theory it could even be more reliable, since `std::chrono::steady_clock` is  guaranteed to not be affected by system time changes.
Closes #2769
=> wallclock() function now uses c++ <chrono> library

docs/_ext/xfunction.py, docs/_static/xfunction.css, docs/_static/xversion.css, docs/api/dt/build_info.rst, docs/api/fexpr/len.rst, docs/develop/documentation.rst, docs/develop/test.rst, docs/manual/f-expressions.rst, src/core/datatablemodule.cc, src/core/expr/fexpr.cc, src/core/expr/fexpr_astype.cc, src/core/expr/fexpr_cut.cc, src/core/expr/fexpr_ifelse.cc, src/core/expr/fexpr_qcut.cc, src/core/expr/fexpr_round.cc, src/core/frame/py_frame.cc, src/core/read/py_fread.cc, src/datatable/__init__.py
The primary difference from Sphinx standard `..versionchanged` and `..deprecated` directives is that the version number is a link and leads to the corresponding Release Notes page.
=> Directives x-version-changed and x-version-deprecated

src/core/column/cut.h, src/core/expr/fexpr_cut.cc, tests/expr/test-cut.py
Fix a bug introduced in #2820 that didn't allow using the same `cut()` `FExpr` more than once.
=> Allow reusing cut FExpr's

src/core/models/dt_ftrl.cc, src/core/models/dt_ftrl.h
For multinomial classification problems FTRL does `softmax` normalization of the computed predictions. Since it involves computation of exponential functions, it may occasionally overflow on some data. In this PR we fix this issue by trying to avoid calculations of exponential function on large arguments.
WIP for https://github.com/h2oai/h2oai/issues/20286
=> Prevent overflow in FTRL predictions

src/core/rowindex_array.cc
Under these circumstances:
`df[condition, :]` that condition is a frame
If the condition frame contains a more complex virtual column, because the function `ArrayRowIndexImpl::init_from_boolean_column` does not have the parallelized `get_element` function, serialization is slower. **Call the parallelized `materialize` function in advance to optimize performance**.**On the other hand, `materialize` function in advance can also use data locality to improve performance**
Take the data of kaggle competition as an example，can be accelerated **3x** times in my machine.
https://www.kaggle.com/benhamner/sf-bay-area-bike-share/data
Machine hardware：
_Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz
20 cores_
=> Optimize i-selector of frame type

docs/api/namespace/__getitem__.rst, docs/releases/v1.0.0.rst, src/core/expr/fexpr_list.cc, src/core/expr/namespace.cc, tests/munging/test-dt-cols.py, tests/test-dt-expr.py, tests/test-f.py
- resolves #2797 
- Allows lists/tuples of f-expression in the `j` selector
=> [ENH] f-expression with list/tuple accepted in `j` selector

requirements_extra.txt
Changed the required version of `xlrd` package to "<=1.2.0", due to the fact that the latest version 2.0.0 removed support for xlsx files. Note that we are only changing the "extra" requirements: these are not forced on the user, rather they are what our package recommends to have.
It might be desirable at this point to either switch to `openpyxl` library for reading xlsx files, or to implement the necessary logic from scratch -- but both of these options require considerable time. 
This change, on the other hand, can be done quickly, and it solves the immediate problem that some of our tests that use xlsx files are now failing.
Closes #2823
=> Change required version of xlrd package

docs/api/type.rst, docs/api/type/date32.rst, docs/api/type/max.rst, docs/api/type/min.rst, src/core/types/py_type.cc, src/core/types/py_type.h, src/core/types/type.cc, src/core/types/type.h, src/core/types/type_bool.h, src/core/types/type_date.h, src/core/types/type_float.h, src/core/types/type_impl.cc, src/core/types/type_impl.h, src/core/types/type_int.h, src/core/types/type_string.h, tests/test-types.py, tests/types/test-date32.py
These are the same as stype's .min / .max.
For date32 column the returned value is a frame instead of datetime.date object (which is rather unfortunate), but that's because python has very limited range for their date object -- only years 1..9999.
=> Create properties min/max for Type

src/core/column/date_from_months.cc, src/core/column/date_from_months.h, src/core/column/date_from_weeks.cc, src/core/column/date_from_weeks.h, src/core/column/date_from_years.cc, src/core/column/date_from_years.h, src/core/py_buffers.cc, tests/types/test-date32.py
This supports arrays with dtypes `datetime64[D]`, `datetime64[W]`, `datetime64[M]`, `datetime64[Y]`.
WIP for  #2858
=> Implement creating a date32 column from a numpy datetime64 array

docs/develop/create-fexpr.rst, src/core/column.cc, src/core/column.h, src/core/column/cast_to_bool.cc, src/core/column/date_from_months.cc, src/core/column/date_from_weeks.cc, src/core/column/date_from_years.cc, src/core/column/func_binary.h, src/core/column/isclose.h, src/core/column/isna.h, src/core/column/npmasked.cc, src/core/expr/fbinary/fexpr__truediv__.cc, src/core/expr/fbinary/math.cc, src/core/expr/fexpr_round.cc, src/core/frame/join.cc, src/core/models/dt_ftrl.cc, src/core/models/dt_ftrl.h, src/core/models/label_encode.cc, src/core/models/label_encode.h, src/core/models/py_ftrl.cc, src/core/models/py_ftrl.h, src/core/py_buffers.cc, src/core/sort/sorter_float.h, src/core/sort/sorter_int.h, src/core/stats.cc, src/core/utils/macros.h, tests/models/test-ftrl.py
Extract FTRL related changes from https://github.com/h2oai/datatable/pull/2871:
- move label encoding functionality to `label_encode.*`;
- clean-up interactions handling;
- minor improvements and refactoring.
Also, fix `make debug`, so that it doesn't fail due to `error: use 'template' keyword to treat '...' as a dependent template name`.
=> FTRL refactoring, fix debug builds

src/core/column_from_arrow.cc, src/core/frame/to_arrow.cc, tests/types/test-date32.py
Our `date32` column can now be converted into pyarrow's `date32` type;
likewise pyarrow's `date32` and `date64` columns can be converted into our `date32`.
WIP for #2858
=> date32 to/from pyarrow

ci/ext.py, src/core/models/dt_ftrl.cc, tests/__init__.py, tests/models/test-ftrl.py
- fix Ftrl predictions when trained on one binomial class;
- add `rel_tol` and `abs_tol` parameters to `assert_equals()`;
- disable `Wpoison-system-directories` warning issued by Clang 12.
Closes #2894
=> Fix Ftrl segfault when trained on one binomial class only

docs/api/index-api.rst, docs/api/time.rst, docs/api/time/ymd.rst, docs/releases/v1.0.0.rst, src/core/expr/eval_context.cc, src/core/expr/time/fexpr_ymd.cc, src/datatable/__init__.py, src/datatable/time.py, tests/expr/time/test-ymd.py
Function `dt.time.ymd()` can be  used to create `date32` columns out of year/month/day components.
I've decided that all date/time functions will leave in the `datatable.time` namespace, so that they can be easily discovered  and run less chance of clashing with some other functionality.
WIP for #2858
=> New function time.ymd()

src/core/column/column_impl.cc, src/core/column/const.cc, src/core/column/const_na.cc, src/core/column/latent.cc, src/core/column/npmasked.cc, src/core/expr/fexpr_literal_type.cc, src/core/expr/head_reduce_unary.cc, src/core/frame/join.cc, src/core/frame/repr/html_styles.cc, src/core/frame/repr/html_widget.h, src/core/frame/repr/text_column.cc, src/core/models/aggregate.cc, src/core/models/label_encode.cc, src/core/python/date.cc, src/core/python/date.h, src/datatable/include/datatable.h, tests/types/test-date32.py
Allow the following functions to work with date32 columns:
- `materialize()`
- `repeat()`
- `join()`
- assign `None`
- reduce functions `min()`, `max()`, `first()`, `last()`
- `aggregate()`
- display in Jupyter Lab
- fix display of negative dates in text console
WIP for #2858
=> Various date32-related functionality

docs/releases/v1.0.0.rst, src/core/column/const.h, src/core/column/const_na.cc, src/core/frame/rbind.cc, tests/munging/test-rbind.py, tests/test-sets.py
- `rbind()`'s behavior now adheres to the general rules of type promotion: numeric columns are compatible with each other, but not with date / string columns.
- rbinding void columns now produces a void column (instead of a boolean).
Closes #2790
=> Rbind() no longer auto-promote among incompatible types

src/core/models/aggregate.cc, src/core/models/dt_linearmodel.cc, src/core/models/dt_linearmodel.h, src/core/models/dt_linearmodel_types.h, src/core/models/py_linearmodel.cc, src/core/models/py_linearmodel.h, src/core/models/utils.cc, src/core/models/utils.h, tests/models/test-linearmodel.py
In general, it is recommended to shuffle training data when fitting the model with SGD. The same is suggested in the [paper](http://martin.zinkevich.org/publications/nips2010.pdf) that we base our parallel implementation on. 
In this PR we implement quasi-random data shuffling for the training data, similar to what we currently do in Aggregator. The shuffling could be disabled by setting the seed to zero.
WIP for #2358
=> Do data shuffling when fitting a linear model

docs/releases/v1.0.0.rst, src/core/frame/repr/terminal_widget.cc, src/core/frame/repr/text_column.cc, src/core/frame/repr/text_column.h, src/core/frame/repr/widget.cc, src/core/frame/repr/widget.h, tests/frame/test-repr-text.py
- Fix bug caused by having special characters in a string column (the string was not properly truncated);
- Additionally, fixed a bug where if the string was truncated at last character, it was not displaying ellipsis;
- Several refactorings in the `Widget` class: properties  `startcol_`, `startrow_` removed and replaced with `is_split_view`  boolean tag;
- Created `RowIndex_TextColumn` class
Closes #2844
=> Fix frame's terminal display when data contains special characters 

src/core/models/dt_linearmodel.cc, src/core/models/dt_linearmodel.h, src/core/models/dt_linearmodel_types.h, src/core/models/py_linearmodel.cc, src/core/models/py_linearmodel.h, tests/models/test-linearmodel.py
Implement constant, time-based, step-based and exponential learning rate schedules for linear model.
Closes https://github.com/h2oai/datatable/issues/2920
=> Implement learning rate schedules for linear model

docs/_ext/xcomparisontable.py, docs/_static/x-comparison-table.css, docs/conf.py, docs/develop/documentation.rst, docs/manual/comparison_with_pandas.rst
- Added new directive `.. x-comparison-table::` which can be used in "comparison of datatable  to other libraries" documentation pages;
- Reformatted the "comparison_with_pandas" manual page to use the new directive.
Note that this PR does not change "comparison_with_rdatatable" or "comparison_with_sql": these can be modified in separate PRs.
Closes #2625
=> Documentation directive x-comparison-table

src/core/models/dt_linearmodel.cc
Fixed the following compiler warnings:
```
src/core/models/dt_linearmodel.cc:324:39: warning: implicit conversion from 'size_t' (aka 'unsigned long') to 'float' may lose precision [-Wimplicit-int-float-conversion]
eta = eta0_ / (1 + eta_decay_ * iter);
~ ^~~~
src/core/models/dt_linearmodel.cc:643:16: note: in instantiation of member function 'dt::LinearModel<float>::adjust_eta' requested here
template class LinearModel<float>;
^
src/core/models/dt_linearmodel.cc:327:46: warning: implicit conversion from 'unsigned long' to 'float' may lose precision [-Wimplicit-int-float-conversion]
eta = eta0_ * pow(eta_decay_, floor((1 + iter) / eta_drop_rate_));
~~^~~~~~  ~
src/core/models/dt_linearmodel.cc:330:38: warning: implicit conversion from 'size_t' (aka 'unsigned long') to 'float' may lose …
```
=> Fix warnings

src/core/_dt.h, src/core/call_logger.cc, src/core/call_logger.h, src/core/datatablemodule.cc, src/core/datatablemodule.h, src/core/frame/cbind.cc, src/core/frame/py_frame.cc, src/core/frame/py_frame.h, src/core/frame/to_arrow.cc, src/core/frame/to_csv.cc, src/core/frame/to_pandas.cc, src/core/python/xargs.cc, src/core/python/xargs.h, src/core/python/xobject.cc, src/core/python/xobject.h, src/core/utils/macros.h, tests/test-dt.py, tests/test-options.py, tests/test-tocsv.py
At some point, `XArgs` should be able to completely replace `PKArgs`.
This PR makes it possible for `XArgs` to be used in methods, with the help of macros `DECLARE_METHOD` and `DECLARE_METHODv` (the latter is for methods returning `void`). These macros provide automatic registration of methods with their python class, avoiding the need to declare the methods in multiple places.
Some methods of `py::Frame` were converted into the new format.
=> py::XArgs can now be used to declare methods

docs/api/models/linear_model.rst, src/core/models/dt_linearmodel.cc, src/core/models/py_linearmodel.cc
Use `PythonLock` instead of a mutex, when communication with python is involved. Also, minor docs updates.
=> Ensure linear model doesn't crash in the presence of the progress bar

docs/_ext/xfunction.py, docs/_ext/xnodes.py, docs/_static/wren.css, docs/_static/xfunction.css
Follow-up for #2953
Also: fixed an issue where a comma would sometimes start a new line in a function's parameters list.
=> Fix code.literal style spillovers

src/core/models/py_linearmodel.cc
Make docs be consistent with the default parameters in C++.
=> Minor correction to LinearModel docs

src/core/csv/reader.cc, src/core/csv/reader.h, src/core/read/parsers/ptype_iterator.cc, tests/test-options.py, tests/types/test-date32.py
Added option `dt.options.fread.parse_dates` (and similarly `.parse_times`) that will prevent fread from recognizing date columns. This is intended as a temporary option, for the purpose of easing the transition of existing code.
=> Add fread option to prevent parsing date columns

docs/api/frame.rst, docs/api/frame/type.rst, docs/releases/v1.0.0.rst, src/core/frame/py_frame.cc, src/core/frame/py_frame.h, tests/test-dt.py, tests/types/test-date32.py, tests/types/test-time64.py
The new property is equivalent to the current `Frame.stype`, only it returns the common `Type` instead of an `stype`.
=> Added property Frame.type

docs/_static/wren.css
Currently, readthedocs makes all tables centered, which interferes with our api-tables.
=> Fix table alignment in the docs

docs/_ext/xcode.py, docs/_static/wren.css, docs/_static/xcode.css, docs/api/type.rst, docs/api/type/bool8.rst, docs/api/type/date32.rst, docs/api/type/int32.rst, docs/api/type/str32.rst, docs/api/type/time64.rst, docs/api/type/void.rst, src/core/types/py_type.cc
In addition, improved rendering of `dtframe` widget in the documentation: now it can properly align time values.
=> Expand documentation for various types, add examples

docs/start/install.rst
Specifically, mention that we now require [pip 20.3+](https://pip.pypa.io/en/stable/news/#v20-3) for installation (this is the earliest version of pip with support for [PEP-600](https://www.python.org/dev/peps/pep-0600/)).
=> Update install documentation

docs/api/type.rst
So, the problem with documenting `Type` class is that it has static members such as `Type.str32` or `Type.float64`, and also regular properties such as `Type().name` or `Type().max`. These obviously have different usage (although technically static members are accessible on instances too, it's not how they are supposed to be used), and therefore mixing them up in the documentation creates lots of confusion. 
This PR addresses this problem by adding a small star icon next to each static member, to indicate that they are "special".
=> Visually separate Type variables from properties/methods in docs

.gitignore, ci/ext.py, ci/gendoc.py, ci/xbuild/extension.py, ci/xbuild/logger.py, docs/_ext/xfunction.py, docs/api/frame/head.rst, docs/api/frame/tail.rst, docs/develop/create-fexpr.rst, src/core/documentation.h, src/core/frame/py_frame.cc, tests/test-docs.py
This PR changes the way we write documentation: instead of embedding the API docs into the code, the documentation can now be written entirely in `doc/` folder, and it will be brought into C++ through an automatic process.
Specifically, the proposed process is as follows:
- the API documentation is written entirely within the `.rst` files in the `docs/` folder;
- the ``.. xfunction`` (&co) directive now has an additional parameter `:cvar:` which describes where this documentation should be copied in order to be available from C++;
- the auto-generator script, which runs automatically on `make build` (or `make debug`), copies the content of the xfunction directive into the specified variable name. The name must be declared in the "documentation.h" file;
- test `test_documentation_h()` …
=> New mechanism for writing documentation

docs/api/frame.rst, docs/api/frame/sd.rst, docs/api/frame/sd1.rst, docs/api/frame/sum.rst, docs/api/frame/sum1.rst, src/core/frame/stats.cc
Also, add documentation for the corresponding one-column frame methods: `.sd1()` and `.sum1()`.
Closes https://github.com/h2oai/datatable/issues/2968
=> Add documentation for .sd() and .sum() frame's methods

docs/_ext/xfunction.py, docs/_static/xversion.css, docs/releases/v1.0.0.rst, src/core/column.h, src/core/column/range.cc, src/core/column/range.h, src/core/column_from_python.cc, src/core/expr/fexpr_literal_range.cc, src/core/frame/__init__.cc, src/core/frame/__sizeof__.cc, src/core/frame/integrity_check.cc, src/core/frame/py_frame.cc, src/core/frame/py_frame.h, src/core/python/arg.cc, src/core/python/obj.cc, src/core/python/obj.h, src/core/rowindex.cc, src/core/rowindex_slice.cc, src/core/types/type.cc, tests/frame/test-create.py
Two arguments in Frame's constructor were renamed:
- `stypes=` into `types=`, and
- `stype=` into `type=`.
The old arguments are still available and continue to work as before, although they were excluded from the documentation.
The new parameters now support `Type` values, and also pyarrow's types (in addition to all the types that were supported before).
Some of the tests were converted into using the new `types=` argument, while others continue using `stypes=`. This ensures that both the new and the old arguments work.
Closes #2986
=> Renamed "types" arguments in Frame constructor

src/core/column/const.cc, src/core/column/latent.cc, src/core/column/npmasked.cc, src/core/expr/fbinary/fexpr__eq__.cc, src/core/expr/fbinary/fexpr__ge__.cc, src/core/expr/fbinary/fexpr__gt__.cc, src/core/expr/fbinary/fexpr__le__.cc, src/core/expr/fbinary/fexpr__lt__.cc, src/core/expr/fbinary/fexpr__ne__.cc, src/core/expr/head_reduce_unary.cc, src/core/frame/join.cc, src/core/models/aggregate.cc, src/core/models/label_encode.cc, src/core/sort.cc, src/core/sort/sorter.cc, tests/types/test-time64.py
Add tests, and make sure the following operations work with time64 columns:
- `repeat()` function;
- `materialize()`;
- `sort()`;
- relational operators `==`, `>`, etc;
- reeducer functions `min()`, `max()`, `count()`, `first()`, `last()`, and `mean()` -- both with and without a groupby.
=> Miscellaneous time64 functionality

ci/ext.py, docs/api/dt/build_info.rst, docs/api/internal.rst, docs/api/internal/compiler_version.rst, docs/api/internal/in_debug_mode.rst, docs/api/internal/regex_supported.rst, docs/releases/v1.0.0.rst, src/core/datatablemodule.cc, src/core/expr/head_func_other.cc, src/core/utils/macros.h, src/datatable/internal.py, tests/munging/test-str.py, tests/test-dt.py
- Added fields to `dt.build_info`:
- `.build_mode` -- which mode datatable was built in;
- `.compiler` -- version string of the compiler;
- Removed function `dt.internal.in_debug_mode()` (was previously deprecated);
- Removed function `dt.inernal.compiler_version()` (was previously deprecated);
- Removed macro `REGEX_SUPPORTED` and function `dt.internal.regex_supported()` -- we now always support regular expressions; 
Closes #2636
=> Expanded dt.build_info

src/core/column/cast_to_date32.cc, src/core/column/cast_to_time64.cc, src/core/column_from_python.cc, src/core/python/obj.cc, src/core/python/obj.h, tests/types/test-date32.py, tests/types/test-time64.py
The function for converting object type into date32 / time64 now expanded to also recognize ints and strings. This allows us to reimplement frame creation via a simple typecast of an obj column into the target type.
In the future, it might be good to use the same approach for force-creation of columns of all other types.
Closes #2915
Closes #3010
=> Force-create a column into date32 and time64 types

docs/api/fexpr.rst, docs/api/fexpr/__getitem__.rst, docs/api/index-api.rst, docs/api/str.rst, docs/api/str/slice.rst, docs/releases/v1.0.0.rst, src/core/column/string_slice.cc, src/core/column/string_slice.h, src/core/documentation.h, src/core/expr/fexpr.cc, src/core/expr/fexpr.h, src/core/expr/fexpr_column_asslice.cc, src/core/expr/fexpr_slice.cc, src/core/expr/fexpr_slice.h, src/core/python/slice.cc, src/core/python/slice.h, src/core/python/xargs.cc, src/datatable/str.py, tests/expr/str/test-slice.py
This implements string-slicing function `FExpr[a:b:c]`, or alternatively as a regular function `dt.str.slice(col, start=a, stop=b, step=c)`.
The new function supports both constant slices and expression-slices. 
The reason to have both a function and a slice expression `[a:b]` is that a function is much easier to find in the documentation (esp. once we have more string functions in `dt.str` module), whereas `[]`-based slices are easier to write.
Closes #1667
=> String slicing

ci/ext.py, docs/api/dt/as_type.rst, docs/api/dt/corr.rst, docs/api/dt/cov.rst, docs/api/dt/cut.rst, docs/api/dt/ifelse.rst, docs/api/dt/qcut.rst, docs/api/dt/shift.rst, docs/api/math/isclose.rst, docs/api/math/round.rst, src/core/datatablemodule.cc, src/core/datatablemodule.h, src/core/documentation.h, src/core/expr/fexpr_astype.cc, src/core/expr/fexpr_cut.cc, src/core/expr/fexpr_ifelse.cc, src/core/expr/fexpr_qcut.cc, src/core/expr/fexpr_round.cc, src/core/expr/head_func_isclose.cc, src/core/expr/head_func_shift.cc, src/core/expr/head_reduce_binary.cc, src/core/frame/to_arrow.cc, src/core/python/xargs.cc, src/core/python/xargs.h, tests/expr/test-shift.py
- Moved documentation for 9 functions into docs/ folder;
- Two functions (`isclose()` and `shift()`) changed into using XArgs;
- Internal method `compiler_version()` renamed into `_compiler()` and simplified;
- Fixed bug in XArgs where methods were improperly added to main namespace as functions.
WIP for #3029
=> Move some API documentation into docs/

docs/api/frame/ltypes.rst, docs/api/frame/stype.rst, docs/api/frame/stypes.rst, docs/api/ltype.rst, docs/api/stype.rst, src/core/expr/fexpr.h, src/datatable/types.py, tests/munging/test-str.py
- add `ltypes`/`ltype` and `stypes`/`stype` deprecation warnings in documentation;
- move `ltype` and `stype` documentation from python to rst;
- add `dt.split_into_nhot()` deprecation test.
=> Minor documentation and tests changes related to deprecation

docs/_static/wren.css
Certain CSS rules injected by readthedocs break our design. This PR attempts to cancel such rules.
=> Fix readthedocs style errors

docs/api/type.rst, docs/api/type/list32.rst, docs/api/type/list64.rst, src/core/documentation.h, src/core/python/xargs.cc, src/core/python/xargs.h, src/core/python/xobject.cc, src/core/python/xobject.h, src/core/stype.h, src/core/types/py_type.cc, src/core/types/py_type.h, src/core/types/type.cc, src/core/types/type.h, src/core/types/type_list.cc, src/core/types/type_list.h, src/core/types/type_void.cc, src/core/types/typeimpl.cc, src/core/types/typeimpl.h, tests/types/test-list.py
This PR adds 2 new type objects: `list32(T)` and `list64(T)`. They are not yet used anywhere, but we have to have a `Type` before a column can be implemented.
WIP for #1692
=> New types list32 and list64

docs/api/type/bool8.rst, src/core/column/cast_to_bool.cc, src/core/column_from_python.cc, src/core/python/int.cc, src/core/python/obj.cc, src/core/python/obj.h, tests/dt/test-cut.py, tests/frame/test-create.py, tests/munging/test-cast.py, tests/test-dt-expr.py, tests/test-dt-stats.py, tests/types/test-bool8.py, tests/types/test-float.py, tests/types/test-int.py
The infrastructure that we had before was based on stypes, which does not allow us to create columns of non-constant types, such as `List<T>`.
The new approach allows each parser more autonomy in the type of column that it creates.
Certain tests moved into separate files.
Parsing of lists of numpy scalars made stricter: now they cannot be mixed with each other.
WIP for #3054
=> Refactor creating column from list

docs/api/dt/rbind.rst, docs/api/frame/rbind.rst, docs/api/type/list32.rst, docs/api/type/list64.rst, docs/releases/v1.1.0.rst, src/core/column.h, src/core/datatable.h, src/core/datatablemodule.cc, src/core/datatablemodule.h, src/core/frame/py_frame.cc, src/core/frame/py_frame.h, src/core/frame/rbind.cc, src/core/set_funcs.cc, tests/munging/test-rbind.py, tests/test-options.py
Rbind-ing columns of disparate types is now possible with parameter `force=True`.
Closes #3062
=> rbind(force=True) will no longer produce a TypeError

docs/releases/v1.1.0.rst, src/core/write/value_writer.cc, tests/frame/test-tocsv.py
CSV writer will now attempt to cast into str any column that it doesn't know how to write directly. For now, this is just the obj64 column.
Closes #3064
=> obj64 columns can now be saved into CSV

docs/releases/v1.1.0.rst, src/core/csv/reader.cc, src/datatable/xls.py, tests/fread/test-fread-api.py, tests/fread/test-xls.py
- A `ValueError` will now be thrown if you specify `sep='-'`, `sep='+'`, or `sep='.'` in fread;
- Reading columns with mixed types from Excel file will no longer produce an error -- instead the values will be upcast into strings;
- Fread is now able to read date fields in Excel and convert them into `time64` columns.
Closes #3065
=> Forbid sep='-'|'+'|'.' in fread

docs/api/type/void.rst, docs/releases/v1.1.0.rst, src/core/column.h, src/core/column_from_python.cc, src/core/frame/to_pandas.cc, src/core/py_buffers.cc, src/core/python/obj.cc, src/core/python/obj.h, tests/frame/test-create.py
When a pandas `object` column is converted into a datatable Column, we will now pass it through the same converter as used when creating a Frame from python list. This allows for better detection of types that datatable can handle natively while pandas cannot.
In addition, conversion of datatable `void` columns into pandas is now special-cased: the produced result is a pandas Series of dtype `object` consisting of `None`s. Before, when we were converting the column into numpy array first, and then sent that array to pandas, the result was a column filled with 0-size `bytes` objects, which is much harder to work with.
Specifically, round trip [datatable]->[pandas]->[datatable] now works void columns.
Closes #3063
WIP for #1692
=> Better convert pandas object column

docs/releases/v1.1.0.rst, src/core/column/const.h, src/core/column/const_na.cc, src/core/jay/jay.fbs, src/core/jay/jay_generated.h, src/core/jay/open_jay.cc, src/core/jay/save_jay.cc, tests/test-jay.py
Void column is the only column that is both virtual and materialized, therefore special handling was necessary for writing this column into Jay file.
Closes #3074
Closes #3060
=> Fix saving void column to jay

docs/releases/v1.1.0.rst, src/core/column_from_python.cc, src/core/frame/to_numpy.cc, tests/frame/test-create.py, tests/frame/test-to-numpy.py, tests/frame/test-to-pandas.py, tests/ijby/test-rowwise.py, tests/test-reduce.py
- When creating Frame from a list of values, a floating-point `nan` value will now be treated as `None`. In particular, `nan`s can now be safely mixed with values of other types, and a list consisting of only `nan`s will turn into a Column of type void.
- Converting string or object columns to numpy no longer produces a masked array. Instead, we create a regular ``object`` array, filled with `None`s in place of NAs. Similarly, converting a string or object column to pandas creates a Series with `None` values (instead of `nan`s as before) in place of NAs.
Closes #3083
=> fix conversion of nans to/from datatable Frame

docs/releases/v1.1.0.rst, src/core/sort.cc, tests/ijby/test-sort.py
- Allow void columns to be used in `sort()`
- Sorting will be skipped for any constant column (i.e. having `Const_ColumnImpl`).
Closes #3088
=> Sort void column

src/core/csv/reader_fread.cc, src/core/read/fread/fread_thread_context.cc, src/core/read/parsers/parse_string.cc, src/core/read/parsers/ptype_iterator.cc, tests/fread/test-fread-issues.py, tests/fread/test-fread-small.py
The variable `quoteRule` can have values from 0 to 3. However, the current code sometimes would increase quote rule beyond 3, leading to undefined behavior.
With this PR I add an assert on the value of quoteRule parameter (so that the violation can be detected earlier), and swap the order of quote rules 2 and 3, which allows us to parse the test file correctly.
As a result of this change, only 1 test case had to be modified, but even there the new behavior is arguably better.
Closes #3092
=> Fix fread bug with quoteRule becoming too large

docs/releases/v1.1.0.rst, src/core/column/latent.cc, tests/dt/test-qcut.py
Latent column materialization routine was missing logic for setting up the `refcount` property. In this PR we fix it, so that the newly created material column gets the same `refcount` as had the original latent column. In some cases, like for the recently added `qcut` functionality, having wrong `refcount` could result in segfaults.
Closes #3061
=> Fix latent column materialization routine

src/datatable/types.py, tests_random/attacker.py, tests_random/continuous.py, tests_random/metaframe.py, tests_random/utils.py
The random attacker now also tests columns of type `void`.
In addition, added command line parameter `--noforks`, allowing to optionally run the attacker without the "fork_and_run" step (which complicates debugging). This parameter is for manual use only.
=> Add void type columns to random attacker

src/core/rowindex.cc, src/core/set_funcs.cc, tests/types/test-void.py
The issue here was that set functions assumed that the result of a sort/groupby is always a rowindex of type `ARR32`, which is no longer the case since #3111. 
Closes #3126
=> Fix using set functions with void columns

docs/api/internal/frame_column_data_r.rst, docs/api/internal/frame_columns_virtual.rst, docs/api/internal/frame_integrity_check.rst, docs/api/internal/get_thread_ids.rst, docs/api/options/debug/arg_max_size.rst, docs/api/options/debug/enabled.rst, docs/api/options/debug/logger.rst, docs/api/options/debug/report_args.rst, src/core/call_logger.cc, src/core/datatablemodule.cc, src/core/documentation.h, src/core/options.cc, src/core/sort.cc
- Moved documentation for several options & internal functions;
- Refactor `dt.internal` functions to use `XArgs` instead of `PKArgs`.
WIP for #3029
=> Move some of the documentation from C++ into docs/

src/core/column.cc, src/core/column.h, src/core/column/arrow.h, src/core/column/arrow_array.cc, src/core/column/arrow_array.h, src/core/column/column_impl.cc, src/core/column/column_impl.h, src/core/column/view.cc, src/core/column/view.h, src/core/column/virtual.h, src/core/column_from_arrow.cc, src/core/frame/to_arrow.cc, src/core/types/type.cc, src/core/types/type_array.cc, src/core/types/type_array.h, src/core/types/typeimpl.cc, src/core/types/typeimpl.h, src/core/utils/arrow_structs.h, tests/types/test-array.py
- Allow `arr32` / `arr64` columns to be created by converting pyarrow `list` / `large_list` types;
- Array columns can now be converted back into python;
- Internal: added method `Column::get_element(size_t i, Column* out)` in order to accommodate reading data from an array  column.
Closes #3053
Closes #3113
=> Create arr32 column from arrow list / large_list

docs/releases/v1.1.0.rst, src/core/ltype.cc, src/core/ltype.h, src/core/stype.cc, src/datatable/types.py, tests/munging/test-dt-cols.py, tests/test-dt.py, tests/test-f.py, tests/types/test-array.py, tests/types/test-type.py
Handling of array columns was fixed by adding `ltype.invalid` and `stype.arr32`/`stype.arr64`. Also, several relevant tests were adjusted.
Closes #3142
=> Fix a crash when `.ltypes` or `.stypes` were accessed for frames with array columns

docs/api/type.rst, docs/api/type/cat16.rst, docs/api/type/cat32.rst, docs/api/type/cat8.rst, docs/api/type/is_array.rst, docs/api/type/is_categorical.rst, src/core/documentation.h, src/core/stype.h, src/core/types/py_type.cc, src/core/types/py_type.h, src/core/types/type.cc, src/core/types/type.h, src/core/types/type_categorical.cc, src/core/types/type_categorical.h, src/core/types/type_void.cc, src/core/types/type_void.h, src/core/types/typeimpl.cc, src/core/types/typeimpl.h, tests/types/test-array.py, tests/types/test-categorical.py
For the moment, these types are not used anywhere, but we need them in order to implement the `Categorical_ColumnImpl`. This PR also includes minor corrections for array types.
WIP for #1691
=> Add categorical types `cat8`, `cat16` and `cat32`

ci/ext.py
File `gendoc.py` and the accompanying doc files were missing from the source distribution.
Closes #3150
=> Include gendoc file into the source distribution

src/core/column.cc, src/core/column.h, src/core/column/arrow.h, src/core/column/arrow_array.cc, src/core/column/arrow_bool.cc, src/core/column/arrow_bool.h, src/core/column/arrow_fw.cc, src/core/column/arrow_fw.h, src/core/column/arrow_str.cc, src/core/column/arrow_str.h, src/core/column/arrow_void.cc, src/core/column/arrow_void.h, src/core/column/cast.cc, src/core/column/cast.h, src/core/column/cast_to_array.cc, src/core/column/const.h, src/core/column/const_na.cc, src/core/expr/fexpr_literal_type.cc, src/core/frame/to_arrow.cc, src/core/jay/save_jay.cc, src/core/types/type.h, src/core/types/type_array.cc, src/core/types/type_array.h, src/core/types/typeimpl.cc, src/core/types/typeimpl.h, tests/types/test-array.py
- In `Arrow_ColumnImpl` methods `num_buffers()` and `get_buffer()` renamed into `get_num_data_buffers()` and `get_data_buffer()` respectively, which are defined in the base `ColumnImpl` class;
- Added type casts of `void -> arr32<T>`, `obj -> arr32<T>` and `arr32<S> -> arr32<T>`;
- In `DT[...] = type` assignment, the RHS can now be a compound type (before, only types convertible to an stype were supported);
- Common functionality for `arr32` and `arr64` types moved into the `Type_Array` class;
- Added function `TypeImpl::make_type()` for creating a `Type` object out of an existing `TypeImpl`;
=> Allow other columns to be cast into array type

src/core/column/cast.h, src/core/column/cast_to_obj.cc, src/core/frame/to_numpy.cc, src/core/types/type_object.cc, tests/types/test-array.py
- Added type cast from arr32(64) into obj64;
- Implemented conversion of array columns into numpy (as objects), and back;
- Implemented conversion of array columns into pandas (as objects), and back;
Closes #3124
Closes #3121 
Closes #3122
Closes #3119 
Closes #3120
=> Implement casting array columns into obj type

src/core/column.cc, src/core/column/categorical.cc, src/core/column/categorical.h, src/core/column/column_impl.h, src/core/column/range.h, src/core/frame/repr/text_column.cc, src/core/models/dt_ftrl.cc, src/core/stype.cc, src/core/stype.h, src/core/types/type_categorical.cc, src/core/types/type_categorical.h, src/datatable/types.py, tests/test-dt.py, tests/types/test-categorical.py, tests/types/test-type.py
- implemented `CategoricalColumn_Impl`;
- added support for categorical columns in `dt.Frame()`;
- added support for categorical columns in a terminal, also allowing the element access through `[i, j]` selector;
- added and modified some relevant tests.
WIP for #1691
=> Implement `CategoricalColumn_Impl` and support for basic operations

docs/releases/v1.1.0.rst, src/core/frame/__repr__.cc, src/core/frame/repr/html_widget.h
It doesn't seem like `.max_column_width` ever worked in Jupyter, instead, we used a hard-coded value of `50` characters as a limit. In this PR we fix it.
Closes #3160
=> Fix support for `.max_column_width` in Jupyter notebooks

tests/conftest.py, tests/frame/test-create.py, tests/fread/test-fread-large.py
- add a large `create_from_pandas` test, see #3169 
- convert `is_release()` function to `release_only` fixture, otherwise several larger tests were actually running for each build;
- rename `winonly` fixture to `win_only` to make it more consistent and readable.
=> Miscellaneous improvements to tests

ci/appveyor.yml, ci/xbuild/wheel.py, src/core/column/categorical.cc
- add a workaround to generate proper wheel names on macOS Big Sur. We should still properly deprecate the `distutils` module at some point;
- switch to the most recent macOS image on AppVeyor.
Closes #3175
=> Fix wheel generation on macOS Big Sur, switch to `macos-bigsur` image on AppVeyor

src/datatable/types.py
Fix errors when retrieving `df[col_name].stype.dtype` from a `date32` and `time64` columns.
=> Fix `.stype.dtype` for temporal types

ci/Jenkinsfile.groovy
In this PR we adjust Jenkins pipeline by removing python `3.6` (it reaches its end of life in a couple of weeks) and replacing it with the new version of python `3.10`. All the datatable virtual environments for particular versions of python have been moved to `/Users/jenkins/datatable_envs/py*/`.
=> Replace python `3.6` with python `3.10` in Jenkins pipeline

tests/test-dt-stats.py
It seems like there are some changes in the `statistics.stdev()` and it now throws an exception for data containing infinite values, it returned `nan` in the earlier versions. In this PR we modify tests, so that we never pass infinite data to `statistics.stdev()`.
=> Fix failing tests for python `3.10.1`

docs/api/dt/countna.rst, docs/api/dt/nunique.rst, docs/api/dt/prod.rst, docs/api/dt/rowargmax.rst, docs/api/dt/rowargmin.rst, docs/api/fexpr/as_type.rst, docs/api/fexpr/rowargmax.rst, docs/api/fexpr/rowargmin.rst, docs/api/re/match.rst
It seems that we've been missing quite a lot of `x-version-added` on documentation pages for newly developed functions, see #3228. In this PR we fix documentation in this respect.
=> Adjust documentation for newly developed functions

docs/releases/v1.1.0.rst, src/core/models/dt_linearmodel.cc
Gradient calculation in the linear model had a bug that caused cumulative gradient multiplication across all the features. In some cases this resulted in the model coefficients blow-up and totally wrong predictions. In this PR we fix this bug.
=> Fix a bug in the gradient calculation for the linear model

src/core/lib/pythoncapi_compat.h
Adjust `pythoncapi_compat.h` to produce no warnings in C++ compilers.
=> Use `reinterpret_cast` and `nullptr` in `pythoncapi_compat.h`

docs/releases/v1.1.0.rst, src/core/jay/save_jay.cc
Sometimes when doing `fread()` rbound void columns could be produced. In this PR we fix writing this kind of columns to jay.
=> Fix writing void rbound columns to jay

docs/releases/v1.1.0.rst
Use the order `[new]`, `[enh]`, `[fix]` and `[api]` in the current changelog, just like we did for previous releases.
=> Rearrange items in changelog

src/core/models/dt_linearmodel.cc, tests/models/test-linearmodel.py
Normally, data passed to `.predict()` method should have no missing values. However, if a missing value is encountered, we don't throw an error but make prediction for the corresponding row to be missing also.
Closes #3260
=> Predict missing on missing values in linear model

tests/models/test-linearmodel.py
=> Simplify `models.LinearModel` test

docs/develop/create-fexpr.rst, docs/releases/v1.1.0.rst, docs/start/install.rst
- update installation documentation: remove installing from `h2o-release.s3-website-us-east-1.amazonaws.com` that never actually worked;
- cosmetic corrections to "Creating a new FExpr" tutorial;
- correct circular definition of the `dt.prod()` function.
=> Minor corrections to documentation

docs/api/dt/by.rst, docs/api/dt/sort.rst
Otherwise their signatures contain broken links to parameters.
=> Add parameters section to `by()` and `sort()` docs

src/core/column/qcut.h, src/core/expr/fexpr_qcut.cc, src/core/expr/head_func_shift.cc, src/core/expr/workframe.cc, src/core/expr/workframe.h, tests/dt/test-qcut.py
We also allow quantile binning for string columns, just because `dt.qcut()` only depends on group-by that is available for strings.
Closes #3165
=> Make `qcut()` function to be group-aware

docs/releases/v1.1.0.rst
Sometimes adding a new feature or pushing a fix, we forget to update the changelog accordingly. Here we just add some of the missing items.
=> Add several missing items to changelog

docs/api/dt/cumsum.rst, docs/api/dt/prod.rst, docs/api/dt/sum.rst, docs/releases/v1.1.0.rst, src/core/expr/head_reduce_unary.cc, src/datatable/__init__.py, tests/test-f.py, tests/test-reduce.py
WIP for #3284 
Closes #3281 
Closes #3282
=> Make `sum()` and `prod()` reducer be applicable to `void` columns

docs/_static/xversion.css, docs/releases/v1.1.0.rst
When we change a function's API, we usually add a "Changed in version" banner. Here is how this banner looks like, for instance, for [ifelse](https://datatable.readthedocs.io/en/latest/api/dt/ifelse.html#notes) function:
And here is how it looks after the fix:
=> Fix styles for "Changed in version" documentation banner

docs/conf.py
In sphinx config set language to `en` to silence the warning:
```
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid langauge code. Falling back to 'en' (English).
```
=> Fix documentation builds

docs/api/index-api.rst, docs/releases/v1.1.0.rst, src/core/expr/head_reduce_nullary.cc, src/core/expr/head_reduce_unary.cc, tests/test-reduce.py
- reducers now support `void` columns in the both grouped and ungrouped modes;
- fixed a bug in `dt.sd()` when the result is `nan`.
Closes #3295 
Closes #3284
=> Add support for `void` columns to statistical reducers

src/core/expr/fexpr_cumsum.cc, tests/dt/test-cumsum.py
- small simplification in the way we handle voids in `cumsum()`;
- add a test for grouped voids.
=> Minor refactoring and a test for voids in `cumsum()`

src/core/column/column_impl.cc, src/core/column/sentinel_str.cc, src/core/frame/replace.cc, src/core/parallel/api.h, src/core/parallel/job_idle.cc, src/core/parallel/job_shutdown.cc, src/core/parallel/parallel_for_ordered.cc, src/core/parallel/parallel_for_static.h, src/core/parallel/thread_pool.cc, src/core/parallel/thread_pool.h, src/core/parallel/thread_team.cc, src/core/parallel/thread_worker.cc, src/core/str/utils.cc, src/core/str/utils.h, src/core/utils/assert.h
Our thread pool could in principle be used outside of datatable for parallelization of other C++ applications. However, currently it is closely coupled to the rest of the codebase. In this PR we add support for `DT_DISABLE` variable which, when set, will make the thread pool to have no specific datatable dependencies. Another option could be to extract the thread pool as a separate project, but this may have negative consequences for the datatable performance. 
Anyways, something like this should now work:
```bash
g++ -std=c++14 -DDT_DISABLE -I./src/core/ parallel_test.cc ./src/core/parallel/*.cc -o parallel_test
```
where `parallel_test.cc` is 
```C++
#include <iostream>
#include <stdlib.h>
#include "src/core/parallel/api.h"
#include "src/core/parallel/thread_pool.h"
int main(int argc, …
```
=> Add `DT_DISABLE` to control thread pool dependencies

docs/api/dt/first.rst, docs/api/dt/last.rst, src/core/expr/fexpr_frame.cc
It appears as though we had some incorrect directions in documentation for `first()` and `last()`. In this PR we fix them and also make some other minor improvements to the text.
=> Improve documentation for `first()` and `last()`

src/core/expr/fexpr_cumminmax.cc, tests/dt/test-cumminmax.py
In #3288 we seem to miss datetime types. In this PR we add support for `date32` and `time64` types in `cummin()` and `cummax()` functions.
WIP for #3279
=> Add support for `date32` and `time64` types in `cummin()` and `cummax()`

docs/_theme/search.html, requirements_docs.txt
Adjust our custom theme in a way similar to `sphinx_rtd_theme`, see  https://github.com/readthedocs/sphinx_rtd_theme/pull/1021. This fixes the search functionality for sphinx `4.*`. We can take care of sphinx `5.*`, that was recently released later, if needed.
Closes #3299
=> Fix search functionality for sphinx `4.*`

src/core/expr/head_reduce_unary.cc
Remove unused `gby` in the case when `dt.unique()` is called in the group by context.
=> Clean-up `dt.nunique()` internals

src/core/expr/head_reduce_unary.cc, tests/dt/test-nunique.py
When we've been working on #3284, we missed void grouped columns support for `dt.nunique()`. This PR fixes it.
Closes #3284
=> Support void grouped columns in `dt.nunique()`

docs/api/dt/count.rst, docs/api/dt/sum.rst, docs/api/frame/sum.rst, docs/api/type.rst, docs/releases/v1.1.0.rst, src/core/column/rbound.cc, src/core/expr/head_reduce_unary.cc, src/core/rowindex_array.cc, src/core/stats.cc, src/core/stats.h, tests/ijby/test-sort.py, tests/test-dt-stats.py, tests/test-reduce.py
Frame's method `.sum()` now returns the same column types as the corresponding `dt.sum()` reducer.
Closes #2904
=> Make Frame's method `.sum()` and `dt.sum()` reducer to return consistent column types

docs/api/dt/cumcount.rst, docs/api/dt/ngroup.rst
Cosmetic improvements of docs for `cumcount()` and `ngroups()`.
WIP for #3279
=> Improve docs for `cumcount()` and `ngroups()`

src/core/models/label_encode.cc, src/core/rowindex.h
Label ids for both FTRL and LinearModel are stored as `int32` column, so It makes no sense to use `ARR64` rowindex to identify the new labels. In this PR we safely change `RowIndex::ARR64` to `RowIndex::ARR32` when creating new labels for classification problems.
=> Change `RowIndex` from `ARR64` to `ARR32` when creating new labels for classification

ci/appveyor.yml, ci/xbuild/wheel.py
Currently our Jenkins is using macOS Big Sur, and in order to make OS coverage as large as possible we switch AppVeyor to use macOS Monterey. Also, in this PR we replace the deprecated `distutils` module with `sysconfig` in order to get the proper platform tag.
Closes #3322 
Closes #3177
=> Switch to macOS Monterey on AppVeyor and remove dependency on `distutils`

ci/Jenkinsfile.groovy, docs/start/install.rst
Support for `manylinux2010` image that we're using to build datatable on `x86_64` is about to be dropped (https://github.com/pypa/manylinux/issues/1281), so we switch to `manylinux2014` that we're already using on `ppc64le`. 
Also, Python 3.7 will reach its end of life soon, hence we switch to Python 3.8 when generating debug wheels. In principle, we can generate debug wheels for all the supported Python versions, however, this will significantly slow down our building pipeline.
=> Switch to `manylinux2014` image on `x86_64` and to py38 for debug wheels

ci/appveyor.yml, ci/ext.py, src/core/frame/names.cc, src/core/python/obj.h, src/core/read/parsers/parse_bool.cc, src/core/read/parsers/parse_date.cc, src/core/read/parsers/parse_time.cc, src/core/tests/test_atomic.cc, src/core/tests/test_barrier.cc, src/core/tests/test_parallel_for.cc, src/core/tests/test_parallel_for_ordered.cc, src/core/tests/test_progress.cc, src/core/tests/test_shared_mutex.cc, src/core/types/type.h, src/core/utils/terminal/terminal_stream.cc, src/core/utils/terminal/terminal_stream.h, src/core/utils/tests.cc, src/core/utils/tests.h, tests/test-parallel.py
In this PR we adjust AppVeyor builds to 
- enable `pyarrow` tests;
- on Windows, enable C++ tests by testing debug wheels for Python 3.9;
- on Windows, fix builds to properly report failures;
- for consistency, rename `DTTEST` to `DT_TEST` and namespace `dttest` to `dt::tests`.
Note, that, when enabled, the C++ tests [redefine](https://github.com/h2oai/datatable/blob/main/src/core/utils/tests.h#L91-L100) `protected` and `private` keywords to `public`. This is a pretty dangerous approach, that we might need to reconsider, because this redefinition only happens in the files which include `utils/tests.h`. On Windows, for instance, this caused a pile of linking errors due to the fact that some methods were expected to be `public`, but were declared as `protected` or `private`.
=> Improve test coverage on AppVeyor

docs/api/fexpr/count.rst, docs/api/fexpr/countna.rst, docs/api/fexpr/cummax.rst, docs/api/fexpr/cummin.rst, docs/api/fexpr/cumprod.rst, docs/api/fexpr/cumsum.rst, docs/api/fexpr/first.rst, docs/api/fexpr/last.rst, docs/api/fexpr/max.rst, docs/api/fexpr/mean.rst, docs/api/fexpr/median.rst, docs/api/fexpr/min.rst, docs/api/fexpr/nunique.rst, docs/api/fexpr/prod.rst, docs/api/fexpr/rowall.rst, docs/api/fexpr/rowany.rst, docs/api/fexpr/rowargmax.rst, docs/api/fexpr/rowargmin.rst, docs/api/fexpr/rowcount.rst, docs/api/fexpr/rowfirst.rst, docs/api/fexpr/rowlast.rst, docs/api/fexpr/rowmax.rst, docs/api/fexpr/rowmean.rst, docs/api/fexpr/rowmin.rst, docs/api/fexpr/rowsd.rst, docs/api/fexpr/rowsum.rst, docs/api/fexpr/sd.rst, docs/api/fexpr/shift.rst, docs/api/fexpr/sum.rst
- make signatures of the functions referenced in the `FExpr` API section to be consistent with the actual signatures of the `dt.*()` functions;
- couple of other minor fixes.
=> Fix signatures of the `dt` functions referenced in the `FExpr` API

docs/api/dt/corr.rst, docs/api/dt/count.rst, docs/api/dt/countna.rst, docs/api/dt/cov.rst, docs/api/dt/first.rst, docs/api/dt/last.rst, docs/api/dt/max.rst, docs/api/dt/mean.rst, docs/api/dt/median.rst, docs/api/dt/min.rst, docs/api/dt/nunique.rst, docs/api/dt/prod.rst, docs/api/dt/rowlast.rst, docs/api/dt/sd.rst, docs/api/dt/sum.rst
While https://github.com/h2oai/datatable/issues/2562 is still WIP, we need to have proper a documentation for both `Expr` and `FExpr` input/return types. This PR fixes it.
=> `FExpr`/`Expr` adjustments in the docs

src/core/column/cumminmax.h, src/core/column/cumsumprod.h, src/core/column/latent.cc, src/core/column/latent.h, src/core/expr/eval_context.cc, src/core/expr/fexpr_fillna.cc, tests/dt/test-cumminmax.py, tests/dt/test-cumprod.py, tests/dt/test-cumsum.py, tests/dt/test-fillna.py
Cumulative functions acces the column's data in parallel. If the input column appears to be a `Latent_ColumnImpl`, materialization of such a column happens in parallel. However, the `Latent_ColumnImpl::materialize()` is not a thread-safe method and invoking it from multiple threads results in a segfault.
In this PR we `vivify()` the source column, i.e. materialization, if necessary, happens in one thread only, before processing it in parallel.
Closes #3345
=> Fix cumulative functions when invoked on the latent columns

docs/index.rst
As we eliminated Travis from our building pipeline (#3042), its status badge stopped working. In this PR we replace it with the AppVeyor's badge.
=> Fix status badge in documentation

ci/appveyor.yml
As we still support Python `3.7` there is no sense to omit it when building/testing wheels on Windows. In this PR we enable Python `3.7` for PR's and main builds on AppVeyor.
Closes #3356
=> Build and test Python `3.7` wheels on Windows

docs/api/dt/fread.rst
- explicitly mention that `columns` parameter will only work for CSV files;
- add more details on how `s3` buckets are read;
- minor text corrections.
Closes #3360
=> Adjustments to fread documenation

src/core/types/type_categorical.cc, src/core/types/type_categorical.h, tests/types/test-categorical.py
Implement casting of boolean, integer, float, date, time and string columns to categoricals.
WIP for #1691
=> Implement casting of the most column types to categoricals

docs/api/dt/shift.rst, docs/api/str/slice.rst, src/core/expr/fexpr_cumsumprod.cc, src/core/expr/fexpr_fillna.cc, src/core/expr/fexpr_slice.cc, src/core/expr/head_func_shift.cc, src/core/expr/re/fexpr_match.cc, src/core/expr/str/fexpr_len.cc, src/core/types/type_categorical.cc, src/core/types/type_categorical.h
- use `col`/`cols` as a parameter name when dt function supports single/multiple column(s);
- convert `dt.shift()` documentation into standard format;
- cosmetics.
=> Parameter names and docs improvements

docs/api/dt/cbind.rst, docs/api/dt/rbind.rst, docs/api/frame/cbind.rst, docs/api/type/cat16.rst, docs/api/type/cat32.rst, docs/api/type/cat8.rst
- fix "See also" section for categorical types;
- improve `cbind()`/`rbind()` documentation.
Also, we probably need to make the wording "See also"/"See Also" be consistent across documentation, and also move the "See also" sections above "Examples", as examples section in some cases could be very long.
=> Fix "See also" sections for `cat*` types and `cbind()`/`rbind()` docs

src/core/expr/declarations.h, src/core/expr/fexpr_alias.cc, src/core/expr/fexpr_categories.cc, src/core/expr/fexpr_dict.cc, src/core/expr/fexpr_list.cc, src/core/expr/fexpr_slice.cc, src/core/expr/workframe.cc, src/core/expr/workframe.h, tests/types/test-categorical.py
It seems that `dt.categories()` is the first datatable function, that needs to produce `Grouping::GtoFEW` columns. That's because the number of categories in a categorical column could be anything between `0` and `nrows - 1`. Currently, datatable doesn't really support `Grouping::GtoFEW`, but may need it for the cases when `dt.categories()` is combined with other f-expressions, or when `dt.categories()` is applied to columns that have different number of underlying categories.
In this PR we
- add some basic support for `Grouping::GtoFEW` grouping mode;
- adjust `dt.categories()` to produce `Grouping::GtoFEW` columns, that in the case of uneven number of rows are  promoted to `Grouping::GtoALL`;
- do minor refactoring in `dt.alias()` function.
WIP for #1691
=> Add basic support for `Grouping::GtoFEW`

src/core/types/type_array.cc, src/core/types/type_bool.cc, src/core/types/type_date.cc, src/core/types/type_object.cc, src/core/types/type_string.cc, src/core/types/type_time.cc, src/core/types/typeimpl_numeric.cc, tests/frame/test-tocsv.py, tests/types/test-categorical.py
In this PR we 
- implement casts from `dt.cat*(...)` to all of the basic types;
- as a consequence, support for converting categorical columns to CSV has been added.
WIP for #1691
=> Implement casts from categorical columns to other types

src/core/column.cc, src/core/column/column_impl.cc, src/core/column/column_impl.h, src/core/stats.cc, tests/types/test-categorical.py
Implement most of the statistical functions for categorical columns. Once we implement sorting of categorical columns, we could add the missing `dt.mode()`.
WIP for https://github.com/h2oai/datatable/issues/1691
=> Implement statistics for categorical columns

docs/api/frame/to_dict.rst, docs/releases/v1.1.0.rst, docs/start/install.rst
Since python `3.6` reached its end of life, update documentation to `3.7+`.
Closes #3376
=> Update documentation regarding removal of python 3.6

docs/api/dt/cummax.rst, docs/api/dt/cummin.rst, docs/api/dt/cumprod.rst, docs/api/dt/cumsum.rst, src/core/column/cumminmax.h, src/core/column/cumsumprod.h, src/core/expr/fexpr.cc, src/core/expr/fexpr_cumminmax.cc, src/core/expr/fexpr_cumsumprod.cc, tests/dt/test-cumminmax.py, tests/dt/test-cumprod.py, tests/dt/test-cumsum.py, tests/test-f.py
Add `reverse` parameter to control direction of cumulative function's calculations: 
- when `False`, calculation is done from top to bottom (default);
- when `True`, calculation is done from bottom to top.
Сloses #3279
=> [ENH] Add `reverse` parameter to `cumsum()`, `cumprod()`, `cummin()` and `cummax()`

docs/api/dt/sort.rst
It seems that `na_position` parameter was missing in the `dt.sort()` documentation for some reason, though it was referred to in the examples. In this PR we fix this issue.
=> Add a parameter `na_position` to `dt.sort()` documentation

ci/appveyor.yml, docs/releases/v1.1.0.rst, src/core/expr/eval_context.cc
It appears as though we never initialized `na_position_` in the case of `dt.by()`, and this resulted in some random data corruption for columns, that contain missing values. As of this PR, we initialize `na_position_` to `NaPosition::FIRST` to be consistent with what we declare in `dt.by()` [documentation](https://datatable.readthedocs.io/en/latest/api/dt/by.html):
```
The default behavior of groupby is to sort the groups in the ascending order, with NA values appearing before any other values.
```
Also, we switch to python 3.8 for testing debug wheels, so that we keep track of the status of the mentioned groupby tests.
Closes #3331
=> Fix groupby behaviour on columns with missing values

ci/appveyor.yml
Closes https://github.com/h2oai/datatable/issues/3392
=> Enable macOS on AppVeyor for Python `3.11`

docs/api/dt/by.rst, docs/api/dt/f.rst, tests/test-groups.py
- the fix for #3390 has been already pushed as a part of #3388, here we merely add a corresponding test;
- as of #2472, `f[:]` excludes the groupby columns, in this PR we make the corresponding adjustments to the docs. 
Closes #3390
=> Add `dt.prod()` test for a grouped column, `by()` docs adjustment

docs/api/dt/sort.rst, docs/releases/v0.11.0.rst, docs/releases/v1.1.0.rst, src/datatable/expr/reduce.py, tests/munging/test-replace.py, tests/test-dt-stats.py, tests/test-groups.py, tests/test-reduce.py
Fix `dt.sum()`, `dt.min()` and `dt.max()` behavior on iterables, frames and generators.
Closes #3406 
Closes #3409
=> Fix datatable functions that shadow python built-ins

docs/api/dt/median.rst, docs/releases/v1.1.0.rst, src/core/expr/head_reduce_unary.cc, src/core/sort.cc, tests/test-reduce.py
In this PR we fix `dt.median()` 
- when called on `void` columns within a groupby context that has more than one group;
- for frames that are grouped by a `void` column;
- tests that tested `dt.mean()` instead;
- return type in documentation.
Closes #3411
=> Fix `dt.median()` when used on a groupby context for void columns

docs/api/dt/mean.rst, src/core/column/mean.h, src/core/expr/fexpr_mean.cc, src/core/expr/head_reduce_unary.cc, src/datatable/__init__.py, src/datatable/expr/__init__.py, src/datatable/expr/expr.py, src/datatable/expr/reduce.py, tests/test-reduce.py, tests/types/test-date32.py
- refactor `mean()` reducer to use `FExpr`;
- fix `median()` to use `float64` for void columns.
WIP for #2562
=> Refactor `mean()` reducer to use `FExpr`

src/core/column/mean.h, src/core/column/reduce_unary.h, src/core/expr/fexpr_mean.cc, src/core/expr/fexpr_sumprod.cc
- refactor existing unary `FExpr` reducers to inherit from `ReduceUnary_ColumnImpl`;
- make `is_grouped` to be a template parameter.
WIP for https://github.com/h2oai/datatable/issues/2562
=> Refactor unary `FExpr` reducers to use `ReduceUnary_ColumnImpl`

src/core/parallel/api_primitives.h
- add `DT_DEFAULT_CHUNK_SIZE` to control default chunk size for `parallel_for_static`;
- add `DT_DEFAULT_MIN_ITERS_PER_THREAD` to control default minimum number of iterations per thread.
=> Add variables to control thread pool defaults

src/core/parallel/api_primitives.h, src/core/parallel/semaphore.h
Add `DT_SEMAPHORE_SPIN_COUNT` macro to control spin count in `LightweightSemaphore::wait()`. The default value is currently `1000000` and may need to be reduced for optimal performance on systems, where datatable has no exclusive access to resources.
=> Add `DT_SEMAPHORE_SPIN_COUNT` to control spin count in thread pool

docs/api/str/len.rst
=> Fix broken link to source in `dt.str.len()` documentation

docs/releases/v1.1.0.rst, src/core/column/mean.h, src/core/column/minmax.h, src/core/column/sumprod.h, src/core/expr/fexpr.cc, src/core/expr/fexpr_func_unary.h, src/core/expr/fexpr_mean.cc, src/core/expr/fexpr_minmax.cc, src/core/expr/fexpr_reduce_unary.cc, src/core/expr/fexpr_reduce_unary.h, src/core/expr/fexpr_sumprod.cc, src/core/groupby.cc, src/core/groupby.h, tests/test-reduce.py
Chained reducers is a pretty rare use case, because the second reducer gets a scalar (per group) as an input. Some SQL engines don't even allow that. However, we never seems to forbid chaining explicitly, at the same time, we had no tests and didn't think such a use case through. As a result, we either produced wrong results (see #3417) or even segfaulted when chaining was involved. In this PR we fix all the known related issues and add some tests. We also
- refactor `FExpr` reducers to inherit from `FExpr_ReduceUnary`;
- improve reducers logic with respect to grouped/non-grouped frames.
WIP for #3417
=> Fix chained `FExpr` reducers

tests/conftest.py, tests/frame/test-to-pandas.py, tests/types/test-date32.py
Fix datatable when tested with the new [pandas 2.0.0](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html).
=> Fix tests for `pandas >= 2.0.0`

docs/api/dt/fread.rst, src/core/csv/reader_fread.cc, tests/fread/test-fread-api.py
It appears though we already allowed the row names in `fread()` but only in the case of the space separator. In this PR we allow row names for any separator, document this behavior and add a test.
Closes #3453
=> Allow row names when data header is detected by `fread()`

src/core/column.cc, src/core/column.h, src/core/column/qcut.h, src/core/expr/fexpr_fillna.cc, tests/test-dt.py
- rename `get_element_isvalid()` to `get_element_validity()`;
- do not use it to check validity of multiple elements in the same column to slightly improve performance;
- streamline `dt.fillna()` backend.
=> Refactor usage of `Column::get_element_isvalid()`

docs/api/frame/replace.rst
- document strings support for `Frame.replace()`;
- add a simple example.
=> Document strings support for `Frame.replace()`

docs/releases/v1.1.0.rst, src/core/models/py_linearmodel.cc, tests/models/test-linearmodel.py
In this PR we
- fix target column type detection in `LinearModel`;
- remove disabled tests, that the model never supported (were inherited from `Ftrl`).
Closes #3466
=> Fix target column type detection in `LinearModel`

ci/ext.py
With this change datatable builds out-of-the-box with gcc on `arm64`.
Closes #3430
=> Do not use unsupported `-m64` linker flag on `arm64`

ci/ext.py
An improvement to the fix #3469, as it seems that `platform.machine()` could also return `aarch64`.
Closes #3430
=> Fix builds on `aarch64`
