h2oai/datatable

- CHANGELOG.md
- datatable/graph/__init__.py
- datatable/graph/rows_node.py
- tests/test_dt.py
> Add ability to remove rows from view Frames

- Jenkinsfile2
This fixes the following:
- the modified files should be detected correctly
- adds separate checks per stage on GitHub
> [BUILD] Bugfix Jenkins Pipeline

- Makefile
- c/csv/reader.cc
- c/utils/exceptions.cc
- setup.py
Also try adding the asan compilation mode
> Fix compile errors in Py3.7

- CHANGELOG.md
- c/columnset.cc
- datatable/graph/cols_node.py
- tests/munging/test_dt_cols.py
> Fix cols/rows selectors on empty Frames

- CHANGELOG.md
- c/sort.cc
- tests/test_dt_sort.py
> 1-row view Frames are now sorted correctly

- datatable/expr/cast_expr.py
- tests/test_dt_expr.py
> Implement __str__ in CastExpr

- c/csv/fread.cc
- tests/fread/test_fread_issues.py
> Fix sep detection if sep was given explicitly

- CHANGELOG.md
- Makefile
- c/csv/fread.cc
- c/csv/reader.cc
- c/csv/reader.h
- c/csv/reader_fread.cc
- c/csv/reader_fread.h
- c/csv/reader_parsers.cc
- c/csv/reader_parsers.h
- c/csv/reader_utils.cc
- c/utils/shared_mutex.h
> Added ability to read str64 columns in fread

- CHANGELOG.md
- datatable/fread.py
- tests/fread/test_fread_api.py
- tests/fread/test_fread_small.py
> 'columns' parameter in fread can now accept a list of stype

- .travis.yml
Please review the cache section of the travis file and squash. 
Closes #891
> [BUILD] Travis ci

- CHANGELOG.md
- c/csv/reader_fread.cc
- datatable/frame.py
- tests/fread/test_fread_detect.py
- tests/fread/test_fread_large.py
- tests/fread/test_fread_small.py
- tests/test_tocsv.py
Also, fread no longer handles assigning column names -- it is deferred to the main `Frame` class.
Closes #944
> Improved logic for auto-assigning column names

- Makefile
- setup.py
> Properly include header files in the source distribution

- CHANGELOG.md
- c/csv/writer.cc
- c/csv/writer.h
- tests/test_tocsv.py
> Implement writing of str64 columns to CSV

- CHANGELOG.md
- MANIFEST.in
> Create MANIFEST.in file, for source distributions

- Jenkinsfile2
- ci/default.groovy
> New stage to upload to public S3

- CHANGELOG.md
- setup.py
> Llvmlite 0.23.0 support

- CHANGELOG.md
- c/csv/reader_parsers.cc
- c/csv/reader_parsers.h
- tests/fread/test_fread_small.py
> Implement parsing of integers with thousand separator

- datatable/dt_append.py
- datatable/frame.py
> Update documentation for cbind / rbind methods

- Dockerfile-centos7.in
- Jenkinsfile2
Closes https://github.com/h2oai/datatable/issues/982
> Switch from using `conda install` to `pip`

- CHANGELOG.md
- c/csv/reader.cc
- c/datatablemodule.c
- c/utils/omp.h
- setup.py
```
>>> import datatable as dt
>>> dt.lib.core.has_omp_support()
True
```
Closes #1001
> Added ability to check whether datatable was built with OMP support

- CHANGELOG.md
- c/datatable_load.cc
- datatable/nff.py
> Save min/max information for each column in NFF format

- Dockerfile-centos7.in
- Dockerfile-ubuntu.in
- Jenkinsfile2
- ci/default.groovy
#994 Create the /tmp/cores dir inside centos container, and archive the contents of the folder for build.
> Core dump collection

- CHANGELOG.md
- Makefile
- c/column.h
- c/column_bool.cc
- c/column_real.cc
- tests/munging/test_dt_append.py
- tests/test_dt_expr.py
> Cast bools/reals into strings

- CHANGELOG.md
- datatable/expr/column_expr.py
- tests/test_dt_expr.py
> Fix a bug where f.* expressions where sometimes not printable

- c/csv/reader_fread.cc
- tests/fread/test_fread_issues.py
> Fix fread crash due to unsafe use of snprintf

- ci/README.md
This document should give a *detailed* description of the release process. It should be updated whenever the process changes. Ideally it should be sufficiently complete that it can be given to a new hire, and they would be able to make a new release without anyone's help.
The document is still incomplete. Please review and post any updates directly into this branch.
> Added a readme file with the description of the release process

- CHANGELOG.md
- Makefile
- c/column.h
- c/column_fw.cc
- c/column_pyobj.cc
- c/column_string.cc
- c/datatable.cc
- c/datatable.h
- c/py_datatable.cc
- c/py_datatable.h
- c/rowindex.cc
- c/rowindex.h
- c/rowindex_array.cc
- c/rowindex_slice.cc
- datatable/frame.py
- tests/test_dt.py
Added ability to resize a Frame by modifying its number of rows.
Closes #1029
> Resize Frame

- CHANGELOG.md
- c/sort.cc
- c/sort_groups.cc
- tests/test_groups.py
> Fix wrong groupby calculations for a rare set of inputs

- .gitignore
- CHANGELOG.md
- datatable/__init__.py
- setup.py
> Include git-revision number into the built package

- CHANGELOG.md
- datatable/fread.py
- tests/fread/test_fread_api.py
> Add ability to read .bz2 files

- docs/build-instructions.rst
- docs/frame.rst
- docs/index.rst
- docs/install.rst
- docs/using-datatable.rst
This is the initial draft. 
The help system for this branch can be viewed at:
http://datatable.readthedocs.io/en/ang-docs-test/index.html
Closes #1017
> Initial checkin of data-table help system

- CHANGELOG.md
- datatable/frame.py
- datatable/graph/__init__.py
- tests/test_groups.py
> Syntax DT[i,j,by] now works

- CHANGELOG.md
- Makefile
- c/expr/reduceop.cc
- c/groupby.cc
- c/groupby.h
- c/py_column.cc
- c/py_column.h
- datatable/expr/base_expr.py
- datatable/expr/binary_expr.py
- datatable/expr/cast_expr.py
- datatable/expr/column_expr.py
- datatable/expr/consts.py
- datatable/expr/isna_expr.py
- datatable/expr/literal_expr.py
- datatable/expr/mean_expr.py
- datatable/expr/minmax_expr.py
- datatable/expr/relop_expr.py
- datatable/expr/sd_expr.py
- datatable/expr/unary_expr.py
- datatable/graph/cols_node.py
- datatable/graph/context.py
- datatable/graph/groupby_node.py
- tests/test_groups.py
> Allow reduced columns to be used alongside with regular columns in groupby

- CHANGELOG.md
- c/expr/reduceop.cc
- datatable/__init__.py
- datatable/expr/__init__.py
- datatable/expr/consts.py
- datatable/expr/reduce_expr.py
- tests/test_groups.py
> Implement 'sum()' reducer

- CHANGELOG.md
- c/expr/binaryop.cc
- datatable/expr/literal_expr.py
- tests/munging/test_dt_rows.py
> Implement string equality operator

- CHANGELOG.md
- datatable/utils/terminal.py
- datatable/widget.py
> Do not use interactive mode when viewing a Frame in Jupyter notebook

- .gitignore
- microbench/groupby/Makefile
- microbench/groupby/groupby.cc
This does not contain any production code -- simply for assessing the best approach to perform groupby operations.
> Added micro-benchmark for groupby summation

- CHANGELOG.md
- c/expr/py_expr.cc
- tests/test_dt_expr.py
> Fix bug with applying a cast expression to a view column.

- CHANGELOG.md
- datatable/dt_append.py
- tests/munging/test_dt_cbind.py
> Fix a bug in cbind where the first Frame was ignored

- datatable/fread.py
- tests/fread/test_fread_api.py
- tests/fread/test_fread_detect.py
- tests/fread/test_fread_small.py
Also, allow additional syntax for `columns` argument:
* `columns=<type>` will cast all columns into the specified type
* `columns={<type>: [...list of columns]}` will convert the specified list of columns into the `<type>`
> Add some more tests for fread

- CHANGELOG.md
- c/expr/reduceop.cc
- c/py_column.cc
- ci/asan-python.c
This is not a particularly robust solution; a better way is to switch from raw C-style pointers to C++ RAII paradigm for `Column` objects. However that's a rather big refactor job that is not so trivial to do...
Closes #1115
> Fixed memory leak in groupby operations

- CHANGELOG.md
- datatable/frame.py
- tests/munging/test_dt_append.py
- tests/test_dt.py
- tests/test_dt_create.py
* Check that `names` is a list/tuple (a string is allowed too, will be wrapped in a list)
* Check that the length of the list corresponds to the actual number of columns
* Check that all entries in the list are strings.
* Tests added
Closes #1119
> Check that the 'names' parameter in Frame constructor is valid

- CHANGELOG.md
- c/column.h
- c/datatablemodule.cc
- c/py_buffers.cc
- c/py_datatable.h
- c/py_datatable_fromlist.cc
- c/utils/pyobj.h
- datatable/frame.py
- tests/conftest.py
- tests/test_dt.py
- tests/test_dt_create.py
> Add ability to create Frame from list/dict of numpy arrays

- CHANGELOG.md
- c/csv/chunks.cc
- c/csv/reader_fread.cc
- c/utils/exceptions.cc
- c/utils/exceptions.h
- tests/fread/test_fread_small.py
> Fix max_nrows parameter in fread

- datatable/fread.py
- datatable/graph/llvm.py
- tests/test_dt.py
> Further reduce the amount of modules that are loaded at datatable's startup

- CHANGELOG.md
- datatable/graph/groupby_node.py
- tests/test_groups.py
> Allow to use filters with groupby expressions

- c/csv/fread.cc
- c/csv/reader.cc
- c/csv/reader.h
- c/csv/reader_fread.cc
- c/csv/reader_utils.cc
- tests/test_dt.py
Multiple improvements to the structure of classes `GReaderColumn` and `GReaderColumns`. Notably, the `GReaderColumn` class is now properly encapsulated, and ptype changes are performed through an iterator.
> Fread cleanup

- Makefile
- ci/Jenkinsfile2
Includes:
- enables collection of core dumps by using `--privilged` mode for docker runs
- enables all testing in PR via `FORCE_ALL_TESTS_IN_PR` option of Jenkins pipeline
> [BUILD] Changes in Jenkinsfile

- CHANGELOG.md
- c/sort.cc
- ci/llvm-gcov.sh
- tests/test_dt_sort.py
- Check that view frames of any stype can be sorted properly.
- Fixed an assertion error when sorting string columns with NAs.
Closes #1164 
Closes #796
> Added tests for sorting view frames

- CHANGELOG.md
- c/expr/binaryop.cc
- tests/munging/test_dt_rows.py
> Fix crash when a filter is applied to a 0-rows frame

- CHANGELOG.md
- c/jay/jay.fbs
- c/jay/jay_generated.h
- c/jay/open_jay.cc
- c/jay/save_jay.cc
- datatable/frame.py
- tests/test_nff.py
> Allow saving key columns into the Jay file

- CHANGELOG.md
- datatable/frame.py
- tests/test_dt_create.py
> Frame(Frame) constructor now creates a shallow copy

- Makefile
- ci/Dockerfile-centos7.in
- ci/Dockerfile-ubuntu.in
- ci/Jenkinsfile2
The upgrade enables PPC64le tests and avoids segfaults reported by:
- https://github.com/numba/numba/issues/2451 
- https://github.com/numba/numba/issues/2848
Close #980
> [BUILD] Upgrade to LLVM6

- tests/test_dt.py
Right now the test measures loading time of `datatable` compared to the loading time of pure python. However, if the system is under heavy load (e.g. performs lots of disk swapping), then these measures can be wildly off. 
With this PR the loading time of datatable will be compared to the loading time of `smtplib` (a standard library), which is about 2.4 times faster to load compared to datatable in normal conditions. The expectation is that the ratio time(datatable)/time(smptlib) should remain roughly the same even on a system under heavy load.
In addition, the test will now repeat itself up to 3 times before concluding a failure -- this is to mitigate any possible short-term spikes in system load.
Closes #1175
> Measure dt loading time relative to loading time of some default library

- c/extras/aggregator.cc
- c/extras/aggregator.h
- tests/extras/test_aggregate.py
- all the constant continuous columns are now normalized to 0.5 preventing the distance from blowing up;
- refactoring based on comments to #1186;
- cosmetics.
Closes #1189
> Handling the constant columns properly

- CHANGELOG.md
- setup.py
> Upgraded dependencies for py3.7

- c/extras/aggregator.cc
- Ignore or replace `NaN`s with zeros depending on a particular
aggregator function.
- Small adjustment to the radius formula based on the Leland's
suggestions.
Closes #1195.
> Handle `NaN`s in aggregator

- CHANGELOG.md
- Makefile
- c/column.cc
- c/column.h
- c/column_fw.cc
- c/column_string.cc
- c/py_columnset.cc
- c/py_columnset.h
- c/py_datatable.cc
- c/py_datatable.h
- c/py_datatable_fromlist.cc
- c/python/long.cc
- c/rowindex.h
- datatable/__init__.py
- datatable/expr/column_expr.py
- datatable/frame.py
- datatable/graph/__init__.py
- datatable/graph/cols_node.py
- datatable/graph/context.py
- datatable/graph/dtproxy.py
- datatable/graph/groupby_node.py
- datatable/graph/join_node.py
- datatable/graph/rows_node.py
- setup.py
- tests/test_dt_sort.py
- tests/test_join.py
Implement basic joining functionality: a Frame can be joined with another Frame if that other Frame is keyed, and the first frame has a column with the same name as the second Frame's key. The syntax for performing this kind of join is:
```
DT1[:, :, join(DT2)]
```
Closes #1190
> Natural join

- ci/Jenkinsfile.groovy
Fixes the wrong version present in VERSION.txt. Content of this file is also used to determine the bucket in S3.
> [BUILD] Specify CI_VERSION_SUFFIX as global env var.

- ci/Jenkinsfile.groovy
Updates jenkins shared library to v1.6. Adds the stage duration to Stages Overview.
> [BUILD] Update shared jenkins lib to v1.6.

- c/py_datatable.cc
- tests/fread/test_fread_api.py
- tests/munging/test_dt_combo.py
> Fix spurious 'only view can be materialized' error

- c/datatablemodule.cc
- c/frame/py_frame.cc
- c/frame/py_frame.h
- c/frame/py_frame_init.cc
- c/python/arg.cc
- c/python/arg.h
- c/python/args.cc
- c/python/args.h
- c/python/ext_type.h
- c/python/list.cc
- c/python/list.h
- ci/make_fast.py
- setup.py
This PR introduces further improvements towards implementing the new Python-C++ framework. Although it is far from complete, I anticipate that further changes will be done on case-by-case need, and there won't be a point in time when we could definitely say "the framework is ready, now the issue can be closed".
Closes #1220
> Python framework, continued

- CHANGELOG.md
- c/py_buffers.cc
- tests/test_dt_create.py
> Fix crash when converting a string column from pandas

- CHANGELOG.md
- datatable/expr/column_expr.py
- tests/test_dt_expr.py
> Fix problems with stringification of f-expressions

- CHANGELOG.md
- datatable/graph/__init__.py
- tests/test_join.py
> Allow to use join columns within update expressions

- ci/Jenkinsfile.groovy
There is a -/_ mismatch in the name.
> [BUILD] Fix s3up from custom branches.

- CHANGELOG.md
- c/options.cc
- c/options.h
- c/py_datatable.cc
- c/py_datatable.h
- c/python/list.cc
- c/python/list.h
- c/python/obj.cc
- c/python/obj.h
- datatable/dt_append.py
- datatable/extras/aggregate.py
- datatable/frame.py
- datatable/graph/cols_node.py
- tests/fread/test_fread_api.py
- tests/test_dt_create.py
This should improve performance, especially for frames where the number of rows is small, but the number of columns large.
> Perform name deduplication in C++

- ci/Jenkinsfile.groovy
This should fix the GroovyPostBuildAction serialization error.
> Update shared lib to 1.7

- ci/Jenkinsfile.groovy
Fix the Serialization related errors in pipeline.
> [BUILD] Update shared lib.

- CHANGELOG.md
- c/column.h
- c/frame/py_frame_init.cc
- c/py_buffers.cc
- tests/test_dt_create.py
> Allow creating a Frame from datetime64 numpy array

- c/extras/aggregator.cc
- tests/extras/test_aggregate.py
>  Add aggregator tests for tiny datasets and some refactoring

- c/column_string.cc
- tests/munging/test_dt_append.py
> In rbind(), handle the case where string buffer's size is 0

- CHANGELOG.md
- c/column.h
- c/column_pyobj.cc
- c/python/obj.cc
- c/python/obj.h
- c/types.cc
- datatable/frame.py
- datatable/utils/typechecks.py
- setup.py
- tests/munging/test_str.py
- tests/test_dt.py
- tests/test_dt_expr.py
- tests/test_dt_options.py
- tests/test_types.py
> Add cast function from obj column to str

- c/frame/replace.cc
- tests/munging/test_replace.py
* Allow `replace()` to work with boolean columns;
* Improve test coverage
Closes #1320
> Implement replace function for boolean columns

- AUTHORS.md
> Add the AUTHORS file

- c/frame/replace.cc
- tests/munging/test_replace.py
> Fix a bug with replace function

- datatable/xls.py
- tests/fread/test_xls.py
Merged cells (if any) now participate in resolving the data ranges when reading Excel files.
This PR also adds several tests for the range2d-finding functionality.
Closes #1329
> Handle merged cells when processing an Excel file

- datatable/__init__.py
- datatable/graph/__init__.py
- datatable/graph/groupby_node.py
- tests/test_groups.py
This PR adds the long-awaited multi-column grouping, via the `by()` function. The syntax is:
```
DT[..., ..., by(col1, ..., colN)]
```
Closes #1300 
Closes #1082
> Implement multi-column groups

- requirements_optional.txt
> Added requirements_optional.txt

- c/csv/reader_parsers.cc
- Merge int32+int64 fread parsers;
- Add option for handling of leading 0s.
> integer csv parsers

- CHANGELOG.md
- c/py_datawindow.cc
- c/rowindex_array.cc
- datatable/expr/column_expr.py
- datatable/graph/cols_node.py
- tests/test_join.py
> Allow g-columns to be selectable during a join

- tests/test_types.py
> Add tests for stype .min / .max

- datatable/frame.py
> Better error messages if pandas/numpy version is too old

- c/extras/aggregator.cc
- tests/extras/test_aggregate.py
> Replace merge-only scenario with just re-testing

- c/frame/_repr_html_.cc
Better Frame styling in both Light and Dark themes.
We no longer use any hard-coded colors, relying instead on Jupyter CSS variables such as `var(--jp-ui-font-color3)` etc. As the values of these variables change with the theme, hopefully, datatable's Frame will remain reasonably well-looking across all possible themes. 
Closes #1419
> Adjust the styling of Frame's html repr

- c/frame/join.cc
> Multi-threaded multi-column join

- tests/fread/test_fread_small.py
> Fix test_maxnrows_on_large_dataset

- CHANGELOG.md
- c/column.cc
- tests/munging/test_dt_rows.py
> Fix crash with applying a repeated row selector

- c/csv/reader_fread.cc
- c/csv/reader_parsers.cc
- c/datatablemodule.cc
- c/extras/aggregator.cc
- c/frame/py_frame_init.cc
- c/frame/to_python.cc
- c/sort.cc
- c/types.cc
- ci/asan-env.sh
- datatable/fread.py
- datatable/graph/llvm.py
- datatable/types.py
- datatable/utils/terminal.py
- datatable/xls.py
- tests/extras/test_aggregate.py
- tests/munging/test_replace.py
- tests/test_dt.py
- tests/test_reduce.py
- tests/test_types.py
This is an attempt to fix some of the issues reported at https://app.codacy.com/project/st-pasha/datatable/dashboard
> Various code style fixes

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- README.md
- c/jay/README.md
Trying to make code linter happier.
> Clean up some .md files

- c/extras/dt_ftrl.cc
- c/extras/dt_ftrl.h
- c/extras/py_ftrl.cc
- c/extras/py_ftrl.h
- tests/extras/test_ftrl.py
- add feature importance estimation based on the contribution of a particular feature to prediction;
- add feature importance to pickling/unpickling methods;
- add and adjust tests;
- minor refactoring.
Closes #1483
> Estimate feature importance in FTRL model

- c/datatablemodule.cc
- c/expr/base_expr.cc
- c/expr/base_expr.h
- c/expr/i_node.cc
- c/expr/j_node.cc
- c/expr/j_node.h
- c/expr/join_node.cc
- c/expr/join_node.h
- c/expr/workframe.cc
- c/expr/workframe.h
- c/frame/__getitem__.cc
- c/groupby.cc
- c/groupby.h
- c/python/arg.h
- c/python/obj.cc
- c/python/obj.h
- c/python/slice.cc
- datatable/expr/cast_expr.py
- datatable/expr/consts.py
- datatable/expr/reduce_expr.py
- datatable/graph/join_node.py
- support for join nodes
- cast expressions
- unary reduce operators
- nullary reduce operators (such as `count()`)
- create j node from int, string, slice, list, an iterable
- added select/update/delete evaluation mode for a workframe (not fully implemented)
WIP for #1477
> WIP improvements to "j node" in the evaluation graph

- c/expr/base_expr.cc
- c/expr/base_expr.h
- tests/test_dt_expr.py
> Added proper return types for unary ops

- CHANGELOG.md
- c/frame/replace.cc
- tests/munging/test_replace.py
> Fix frame.replace() for the case of +inf

- AUTHORS.md
- c/extras/hash.h
- tests/extras/test_ftrl.py
- add tests to check if the `model` and `fi` returned by the corresponding getters are not changed when FTRL object changes;
- make string hasher be consistent with others, i.e. return `NA` when either `RowIndex` is `NA`, or the string  itself is `NA`;
- fix a typo in `AUTHORS.md` file.
> Add more FTRL tests, some minor adjustments

- CHANGELOG.md
Fix 32 style warnings found by Codacy in the CHANGELOG.
> Fixes in changelog as suggested by codacy

- CHANGELOG.md
- c/frame/replace.cc
- c/utils/parallel.h
- tests/munging/test_replace.py
> Fix replacing in view string column

- CHANGELOG.md
- c/expr/i_node.cc
- c/rowindex_array.cc
- tests/munging/test_dt_rows.py
> Allow 0-row integer column as i in DT[i,j]

- CHANGELOG.md
- c/column_string.cc
- tests/test_join.py
> Fix materialization of a string column resulting from a join

- CHANGELOG.md
- c/column.h
- c/column_fw.cc
- c/expr/j_node.cc
- c/expr/j_node.h
- c/expr/repl_node.cc
- c/expr/repl_node.h
- c/expr/workframe.cc
- c/expr/workframe.h
- c/frame/__getitem__.cc
- c/frame/py_frame.h
- c/frame/repeat.cc
- datatable/frame.py
- datatable/graph/__init__.py
- tests/munging/test_assign.py
This PR implements frame updates (via `DT[i, j] = ...`) in C++. This is the last task necessary to perform evaluation of general `DT[i, j, ...]` expression entirely in C++.
Closes #1477
> Perform frame update in C++

- CHANGELOG.md
- c/csv/writer.cc
- tests/test_tocsv.py
> Fix a crash when writing an empty frame to csv

- CHANGELOG.md
- c/expr/by_node.cc
- tests/test_groups.py
> Fix crash when empty by() was used

- c/groupby.cc
- c/groupby.h
- c/py_column.cc
- c/py_column.h
- c/py_rowindex.cc
- c/py_rowindex.h
- datatable/expr/isna_expr.py
- tests/munging/test_dt_rows.py
> Remove ungroup_ri from class Groupby

- c/extras/dt_ftrl.cc
- c/extras/dt_ftrl.h
- c/extras/py_ftrl.cc
- c/extras/py_ftrl.h
- docs/ftrl.rst
- tests/extras/test_ftrl.py
- rename `d` to `nbins`;
- rename `inter` to `interactions`;
- add a `feature_name` column to `feature_importances` frame, that will reflect on the actual feature name for which we calculated `feature_importance`;
- adjust and add more tests;
- adjust documentation.
> FTRL API adjustments

- CHANGELOG.md
- c/column_fw.cc
- c/column_string.cc
- tests/munging/test_rbind.py
- tests/random_attack.py
- The negative step slice was incorrectly accounted for during frame materialization;
- Improved error printout for data mismatch in random attack script.
Closes #1594
> Fix rbinding frames with negative step slice

- c/column_string.cc
> Remove inaccurate asserts

- tests/munging/test_rbind.py
- tests/random_attack.py
This PR adds several new random attack methods to "tests/random_attack.py" script.
> Added new random attack methods

- CHANGELOG.md
- datatable/dt_append.py
- tests/fread/test_fread_api.py
- tests/munging/test_rbind.py
[See issue #1610 for the discussion of the rationale for this change]
Closes #1610
> Frame.rbind() no longer returns self

- c/extras/py_ftrl.cc
- c/extras/py_ftrl.h
- docs/ftrl.rst
- tests/extras/test_ftrl.py
- adjust `feature_names` when `iterations` parameter changes;
- add a relevant test.
Closes #1606
> Fix an issue when feature_names goes out of sync with the iterations parameter

- c/csv/writer.cc
- tests/test_tocsv.py
> Fix issue with multi-threaded CSV writing

- c/sort.cc
- tests/test_groups.py
> Fix incorrect group level when by() was combined with sort()

- c/extras/py_ftrl.cc
- c/extras/py_ftrl.h
- c/frame/__init__.cc
- c/frame/py_frame.cc
- c/frame/py_frame.h
I verified that with this PR datatable compiles and runs all tests with `gcc 7.4.0`.
Closes #1622
> Fix gcc compilation errors

- ci/Jenkinsfile.groovy
> #952 latest stable artifacts generation

- tests/test_dt_sort.py
see https://github.com/h2oai/h2oai/issues/7014
> Add a test case from issue #h2oai/7014

- c/csv/toa.h
- c/extras/py_validator.h
- c/mmm.h
- c/rowindex_array.cc
- c/types.cc
- c/types.h
- datatable/xls.py
(also some warnings)
Closes #1640
> Fix compilation errors with latest GCC

- CHANGELOG.md
- c/frame/key.cc
- c/rowindex_array.cc
- tests/test_keys.py
> Fix a crash when a key was applied after a groupby

- c/frame/__init__.cc
- c/frame/_repr_html_.cc
- c/frame/cbind.cc
- c/frame/names.cc
- c/frame/py_frame.cc
- c/frame/py_frame.h
- c/frame/replace.cc
- c/frame/to_numpy.cc
- c/frame/to_python.cc
- c/python/args.h
Update functions in `py::Frame` to use new calling convention, introduced in #1655
> Update functions in `py::Frame`

- c/frame/__repr__.cc
- c/frame/py_frame.cc
- c/frame/py_frame.h
- datatable/__init__.py
- datatable/frame.py
- datatable/utils/terminal.py
> All Frame.repr functions moved to C++

- Makefile
- ci/Jenkinsfile-build-docker-images.groovy
- ci/Jenkinsfile.groovy
Existing docker images have been migrated as well.
> [BUILD] Migrate to harbor.h2o.ai.

- c/py_datatable.cc
- c/py_datatable.h
- tests/__init__.py
- tests/munging/test_dt_cols.py
- tests/munging/test_dt_rows.py
- tests/test_dt.py
- tests/test_dt_sort.py
- tests/test_groups.py
- tests/test_keys.py
- tests/test_nff.py
Added a helper function `isview()` in tests with the same purpose.
WIP for #1066
> Eliminate property Frame.internal.isview

- c/expr/sort_node.cc
- c/expr/sort_node.h
- c/frame/py_frame.cc
- c/frame/py_frame.h
- c/sort.cc
- datatable/frame.py
> Moved Frame.sort() into C++

- tests/munging/test_cbind.py
> Renamed test_dt_cbind.py -> test_cbind.py

- c/py_buffers.cc
- tests/test_dt_create.py
> Pandas string column with nans now converts to datatable correctly

- c/models/dt_ftrl_real.cc
- c/models/dt_ftrl_real.h
- c/models/utils.h
Make datatable compile with gcc again.
> Gcc compilation fixes

- CHANGELOG.md
- c/column_fw.cc
- tests/test_dt.py
> Fixed conversion to numpy of a view Frame which contains NAs

- c/datatablemodule.cc
> Do not use #pragma omp critical in TRACK/UNTRACK functions

- c/column_fw.cc
- c/column_string.cc
> Clean up #pragma omp uses in column_*.cc

- c/frame/to_numpy.cc
- c/stats.cc
> Use dt::parallel in stats.cc and to_numpy.cc

- c/str/split_into_nhot.cc
> Replace openmp with dt::parallel in split_into_nhot.cc

- c/parallel/api.h
- c/parallel/parallel_for_dynamic.cc
- c/parallel/parallel_for_test.cc
- c/parallel/thread_scheduler.cc
- c/parallel/thread_scheduler.h
- c/utils/macros.h
- c/ztest.cc
- c/ztest.h
- tests/test_dt.py
Implement parallel_for with dynamic scheduling.
Closes #1772 
WIP for #1736
> Parallel dynamic

- c/sort.cc
Also, `max(len)` reductions were replaced with simple atomic flags.
WIP for #1736
> Remove OMP constructs from sort.cc

- c/csv/writer.cc
> Remove uses of omp from csv writer

- c/csv/reader.cc
- c/parallel/api.h
- c/parallel/parallel_for_ordered.cc
- c/parallel/thread_team.cc
- c/parallel/thread_team.h
- c/read/parallel_reader.cc
- c/read/thread_context.cc
Also added `dt::barrier()` construct.
WIP for #1736
> Replace OMP uses in fread with thread_pool

- CHANGELOG.md
- c/frame/__repr__.cc
- datatable/widget.py
> Fix interactive mode in IPython

- Makefile
- c/parallel/thread_team.cc
- c/parallel/ztest_atomic.cc
- c/parallel/ztest_barrier.cc
- c/ztest.cc
- c/ztest.h
- tests/test_dt.py
Fix `dt::barrier()`, when called multiple times, and add corresponding C++ tests.
> Fix dt::barrier(), add tests

- CHANGELOG.md
- c/column.h
- c/column_pyobj.cc
- c/frame/integrity_check.cc
- tests/test_dt.py
> Fix crash during materialization of an object column

- CHANGELOG.md
- c/frame/__init__.cc
- tests/test_dt_create.py
> Support ingesting pandas DataFrames with duplicate column names

- CHANGELOG.md
- c/models/aggregator.cc
- c/models/aggregator.h
- c/models/utils.cc
- c/models/utils.h
- c/parallel/thread_worker.cc
- c/progress/manager.cc
- tests/models/test_aggregate.py
Aggregator will now use the standard progress bar functionality.
The previous parameter `progress_fn` is now defunct: if present, it will be ignored with a warning.
WIP for #1643
> Replace progress bar in the Aggregator

- c/models/aggregator.cc
- tests/models/test_aggregate.py
Add message checks to progress reporting Aggregator test.
> Minor improvement of Aggregator tests

- CHANGELOG.md
- c/models/kfold.cc
- tests/models/test_kfold.py
> Random assignment in kfold_random() no longer depends on thread count

- c/expr/expr_binaryop.cc
> Fix invalid access to array binop_names

- CHANGELOG.md
- c/sort.cc
- tests/test_dt_sort.py
> Fixed crash in sort() when sorting by multiple columns

- CHANGELOG.md
- c/frame/__repr__.cc
- tests/test_dt.py
> Fix display of NA values in Jupyter notebook

- c/parallel/monitor_thread.cc
This may or may not resolve current problems with PPC tests.
> Attempt to prevent crashes connected with monitor thread and GIL

- c/parallel/api.h
- c/parallel/monitor_thread.h
- c/parallel/thread_pool.cc
- c/parallel/thread_pool.h
- c/parallel/thread_worker.h
- c/read/parallel_reader.cc
> Fix possible crash if columns are resized during fread-ing

- CHANGELOG.md
- c/column_string.cc
- c/expr/repl_node.cc
- c/parallel/string_utils.h
- tests/munging/test_replace.py
>  Fix crash when replacing values in a str64 column

- c/csv/reader.cc
This may help resolve https://github.com/h2oai/h2oai/issues/9911
> Emit delayed messages in fread under the protection of a mutex

- c/sort_insert.cc
I plan to revisit this change in the future, but for now it needs more testing.
> Undoing recent changes to binary insert-sort, possibly unstable

- c/models/dt_ftrl.cc
- c/models/dt_ftrl_base.cc
- c/models/dt_ftrl_base.h
- c/models/label_encode.h
- tests/models/test_ftrl.py
Fix FTRL tests that were failing due to changes introduced in #1899
> Fix failing FTRL tests

- CHANGELOG.md
- c/expr/expr_binaryop.cc
- c/expr/expr_binaryop.h
- tests/munging/test_str.py
> Fix comparison of string columns with None

- c/csv/reader.cc
- c/csv/writer.cc
- c/read/parallel_reader.cc
- tests/fread/test_fread_small.py
This may help resolve DAI's errors  "Assertion PyGIL_Check() failed".
> Ensure python messages are sent under the protection of a mutex

- CHANGELOG.md
- c/column_bool.cc
- c/column_int.cc
- c/column_pyobj.cc
- c/column_real.cc
- c/column_string.cc
- tests/test_join.py
> Fix a crash when selecting elements from a joined Frame

- CHANGELOG.md
- c/csv/writer.cc
- tests/test_tocsv.py
> Fix a crash when writing a joined Frame to csv

- CHANGELOG.md
- datatable/fread.py
- tests/fread/test_fread_issues.py
> Do not ignore errors in fread(cmd=)

- c/column.h
- c/models/column_hasher.cc
- c/models/column_hasher.h
- c/models/dt_ftrl.cc
The number of classes is reduced and API simplified. This class is now future-proof with respect to new virtual column classes that will be added soon.
WIP for #1396
> Hashers now use OColumn's ::get_element() interface

- c/models/dt_ftrl.cc
- c/progress/work.cc
- c/progress/work.h
- do more correct progress reporting for `.fit()` method and account for validation work;
- add `get_done_amount()` method to `work` class.
WIP for #1643
> Improve FTRL progress reporting

- CHANGELOG.md
- c/sort.cc
- tests/test_dt_stats.py
> Fixed crash when computing mode stat on a view frame

- c/column.cc
- c/column.h
- c/column_fw.cc
- c/column_pyobj.cc
- c/column_string.cc
- c/datatable.h
- c/expr/expr_binaryop.cc
- c/expr/expr_reduce.cc
- c/expr/repl_node.cc
- c/expr/workframe.cc
- c/frame/__init__.cc
- c/frame/cast.cc
- c/frame/integrity_check.cc
- c/frame/rbind.cc
- c/frame/repeat.cc
- c/models/label_encode.h
- c/set_funcs.cc
- c/sort.cc
- c/stats.cc
- c/str/split_into_nhot.cc
- tests/test_dt_stats.py
- Properties `nrows` and `_stype` in `Column` are now protected;
- No classes outside of `Column`/`Stats` now use the "raw" Column class.
- Remove unused parameter as_view= in DataTable::group()
WIP for #1396
> Further work on refactoring Column class

- c/expr/by_node.cc
- c/expr/collist.cc
- c/expr/collist.h
- c/expr/expr.cc
- c/expr/expr.h
- c/expr/expr_column.cc
- c/expr/expr_column.h
- c/expr/expr_columnset.cc
- c/expr/expr_columnset.h
- c/expr/j_node.cc
- c/expr/repl_node.cc
- c/expr/sort_node.cc
- tests/munging/test_delete.py
- tests/test_f.py
- tests/test_join.py
> Allow 'removing' non-existing columns from a columnset

- c/datatable.h
- c/expr/j_node.cc
- c/expr/repl_node.cc
- c/expr/repl_node.h
- docs/changelog/v-0-10-0.rst
- tests/munging/test_assign.py
> Fix crash when assignment uses a non-existing column

- c/frame/join.cc
- docs/changelog/v-0-10-0.rst
- tests/test_join.py
Fixes https://github.com/h2oai/h2oai/issues/10995
Closes #1988
> Fix a crash when joining with a 0-row frame

- ci/setup_utils.py
- datatable/__version__.py
> __version__ changed to 0.10.0a

- c/set_funcs.cc
- tests/test_sets.py
> Fix crash when performing a set function with 2 empty frames

- tests/test_dt_stats.py
> Add tests for mode() on an empty frame

- c/frame/names.cc
- tests/munging/test_cbind.py
- tests/random_attack.py
- tests/random_driver.py
> More careful name-deduplication algorithm

- c/frame/names.cc
- docs/_static/code.css
- docs/changelog/definitions.rst
- docs/changelog/v-0-10-0.rst
- tests/fread/test_fread_api.py
- tests/munging/test_assign.py
- tests/munging/test_cbind.py
- tests/munging/test_rbind.py
- tests/random_attack.py
- tests/test_dt_create.py
> Use option frame.name_auto_index when deduplicating column names

- c/column_impl.h
- tests/munging/test_rbind.py
- tests/random_attack.py
Also, this PR improves random_attack script by adding automatic code generation for an MRE.
Closes #2030
> Fix rbinding of string columns after they were resized

- c/column/view.cc
- c/column/view.h
- tests/random_attack.py
- tests/test_dt.py
- tests/test_parallel.py
> Fix bug during copying of resized view columns

- c/buffer.cc
- c/buffer.h
- c/column_impl.h
- c/csv/reader.h
- c/frame/stats.cc
- c/groupby.h
- c/read/column.h
- c/rowindex_array.cc
- c/utils/array.h
- c/writebuf.cc
- c/wstringcol.h
(in the next step, I'm going to rename class `MemoryRange` into `Buffer`)
> memrange.h renamed into buffer.h

- c/progress/ztest_progress.cc
- tests/test_parallel.py
- add more progress tests;
- adjust existing ones for systems having larger number of threads.
> Improve parallel progress tests

- c/parallel/parallel_for_ordered.cc
- c/parallel/string_utils.h
- docs/changelog/v-0-10-0.rst
- tests/munging/test_assign.py
> Fix infinite loop when operating on a 0-rows string column

- ci/Dockerfile-centos7.in
- tests/random_attack.py
- tests/random_driver.py
- tests/test_dt.py
- add a sort method to random attacker;
- add random attack to testing pipeline (for Python 3.6+);
- several minor fixes.
> Add a sort method to random attacker

- tests/random_attack.py
Replace one-column sorting with a multicolumn one in the random attacker.
> Do multicolumn sorting to random attacker

- c/models/aggregator.cc
- c/models/dt_ftrl.cc
- c/models/dt_ftrl.h
- c/models/utils.h
Minor cleaning and improvement of FTRL `update()` method
> Minor cleaning of FTRL and Aggregator

- c/csv/py_csv.cc
- c/csv/reader.cc
- c/csv/reader.h
- c/csv/reader_arff.cc
- c/csv/reader_fread.cc
- c/datatablemodule.cc
- c/datatablemodule.h
- c/frame/__init__.cc
- c/frame/py_frame.h
- c/python/arg.cc
- c/python/arg.h
- c/python/args.cc
- c/python/args.h
- c/python/list.cc
- c/python/list.h
- c/python/obj.cc
- c/python/xobject.h
- c/read/columns.cc
- c/read/columns.h
- c/read/py_read.cc
- c/read/py_read_iterator.h
- c/read/read_source.cc
- c/read/read_source.h
- datatable/fread.py
- tests/fread/test_fread_api.py
- tests/test_tocsv.py
- Code for checking fread inputs was repeated in Python and C++, so removed python part;
- No longer pass property `._columns` from C++ to python and then back again;
- Class FreadReader significantly simplified (to be removed in the future);
- Start working on a new (prototype) fread function, though it's not doing anything yet.
WIP for #2008 
WIP for #1832
> Fread partial refactoring

- c/expr/by_node.cc
- c/expr/eval_context.cc
- c/expr/expr_reduce.cc
- c/groupby.cc
- c/groupby.h
- docs/changelog/v-0-10-0.rst
- setup.cfg
- tests/test-groups.py
> Fix grouping of an empty frame

- c/datatable.cc
- c/expr/eval_context.cc
- docs/changelog/v-0-10-0.rst
- tests/munging/test_delete.py
> Fix crash when key columns are deleted from a Frame

- c/column_from_pylist.cc
- c/frame/__init__.cc
- c/python/obj.cc
- c/python/obj.h
- docs/changelog/v-0-10-0.rst
- tests/test_dt_create.py
- Add ability to create a Frame from a list of numpy integers, or numpy floats;
- Added internal methods `obj::is_numpy_int()` and `obj::is_numpy_float()`;
Closes #2079
> Implement creation of Frames from numpy scalars

- c/frame/repr/terminal_widget.cc
- c/frame/repr/terminal_widget.h
> Fix display issue in IPython terminal

- c/frame/__repr__.cc
- c/frame/repr/repr_options.cc
- c/frame/repr/repr_options.h
- c/frame/repr/terminal_widget.cc
- c/frame/repr/terminal_widget.h
- c/frame/repr/text_column.cc
- c/frame/repr/text_column.h
- c/models/aggregator.cc
- c/options.cc
- c/py_buffers.cc
- c/python/obj.cc
- c/python/obj.h
- c/read/py_read.cc
- c/utils/c+++.h
- c/utils/terminal.cc
- c/utils/terminal.h
- datatable/utils/terminal.py
- tests/frame/test-repr-text.py
In addition, class `TextColumn` was split into `Data_TextColumn` and `VSep_TextColumn`; property `border_right_` removed.
Closes #2108
> C++ terminal now listens to option 'display.use_colors'

- c/utils/terminal.cc
- c/utils/terminal.h
This will allow us better adjust displayed columns to fit the width of the terminal.
> C++ Terminal can now detect its height+width

- Makefile
- c/buffer.cc
- c/write/write_manager.cc
- c/writebuf.cc
- c/writebuf.h
- ci/asan-env.sh
- ci/setup_utils.py
- docs/changelog/v-0-10-0.rst
> Fix leak when writing into csv

- c/rowindex_array.cc
- tests/munging/test_dt_rows.py
> Fix issue 1970

- c/expr/repl_node.cc
- tests/munging/test_assign.py
- tests/random_attack.py
- throw an exception when changing values in a key column;
- add a unit test and adjust random attacker.
WIP for #2098 
Closes #2134
> Throw an exception when changing values in a key column

- c/models/aggregator.cc
- tests/models/test_aggregate.py
In the case of sparse data Aggregator methods to calculate distance and to project a row
didn't take into account a possibility of having zero contributing components. This was causing `delta` to become a `NaN`, and eventual Aggregator hang. This PR fixes the issue.
Closes #2140
> Make aggregator to work correctly on sparse data

- c/expr/eval_context.cc
- tests/ijby/test-assign-frame.py
> Fix invalid stype downcast when assigning to a subframe

- c/writebuf.cc
- fixed a bug with writing data chunks over 1GB in size;
- added retry for writing data if it was interrupted via a system signal.
Hopefully this can resolve https://github.com/h2oai/h2oai/issues/12415
> Improve file-writing function FileWritableBuffer::prep_write()

- c/column/npmasked.cc
- c/column/npmasked.h
- c/frame/__init__.cc
- tests/test_dt_create.py
The error occurred when importing a sliced masked numpy array.
Closes #2170
> Fix "Invalid data access" error

- c/frame/repr/terminal_widget.cc
- c/frame/repr/text_column.cc
- tests/frame/test-repr-text.py
> Fix ellipsis column when displaying frame in a terminal

- c/expr/eval_context.cc
- c/expr/eval_context.h
- c/frame/__getitem__.cc
- c/sort.cc
- remove some dead code;
- improve docs;
- make sure that all member variables end with `_`.
> Minor cleanup of EvalContext object

- tests/test_utils_misc.py
Tiny improvement to code coverage. Tests pass and coverage increases when I ran `make coverage` locally.
> Add humanize_bytes unit tests

- c/buffer.cc
- c/csv/reader.cc
- c/csv/reader.h
- c/jay/open_jay.cc
- datatable/fread.py
- docs/_static/code.css
- docs/changelog/definitions.rst
- docs/changelog/v-0-11-0.rst
- tests/fread/test_fread_large.py
- tests/test_jay.py
Fread will now attempt to detect a Jay file from the file's signature.
> Allow reading Jay files without .jay extension

- c/column/column_impl.cc
- c/column/sentinel_fw.cc
- c/column/sentinel_str.cc
- c/frame/cast.cc
- c/models/label_encode.h
- c/parallel/api_primitives.cc
- c/parallel/api_primitives.h
- docs/changelog/v-0-11-0.rst
- tests/test-groups.py
> Fix 'Unable to created a nested team' error

- ci/xbuild/__init__.py
- ci/xbuild/compiler.py
- ci/xbuild/extension.py
> Various fixes and changes to xbuild to make it run on WIndows

- c/datatable.cc
- c/datatablemodule.cc
- c/datatablemodule.h
- c/expr/fbinary/math.cc
- c/models/dt_ftrl.cc
- c/models/utils.cc
- c/models/utils.h
- c/utils/misc.cc
- fix `std::copysign` on Windows;
- define struct tags, add `extern "C"`, and other minor adjustments to the code.
WIP for #1369
> Fix copysign and other various adjustments for Windows build

- c/write/value_writer.cc
- docs/changelog/v-0-11-0.rst
- tests/test_tocsv.py
> Fix saving to csv a frame with computed boolean column

- c/python/args.cc
This may help avoid (rare) deadlocks on ppc64 machines with old gcc 4.8 compiler.
> Avoid throwing exception in PKArgs::_find_kwd()

- ci/xbuild/logger.py
- ci/xbuild/wheel.py
- ext.py
- pyproject.toml
> [xbuild] Implement building sdists

- ci/xbuild/logger.py
- ci/xbuild/wheel.py
- ext.py
> Implement --audit parameter for ext.py

- c/datatablemodule.cc
- docs/changelog/v-0-11-0.rst
- tests/test_dt.py
> Fix 'Invalid data access' error in frame_column_data_r()

- c/expr/fbinary/relational.cc
- c/types.h
- tests/test_dt_expr.py
This pull request addresses some of the `String operations` tasks in #290.
> Add comparison operators for strings (<, >, <=, >=)

- c/models/aggregator.cc
- c/models/column_convertor.h
- tests/models/test_aggregate.py
- refactor `NA` handling in Aggregator;
- fix a bug in `group_2d_mixed()` for columns consisting of all the missing values;
- improve test coverage.
Closes https://github.com/h2oai/h2oai/issues/13354
> Refactor and fix an edge case bug in Aggregator 

- Makefile
- ext.py
- pyproject.toml
- tests/test_reduce.py
- Fixed installation from the source tree (`pip install .`)
- Fixed installation from an sdist
Closes #2318
> Pip install datatable from the source tree works again

- ci/Jenkinsfile.groovy
(See https://h2oai.github.io/py-repo/)
Closes #2324
> Use custom pip repo for PPC machines

- ci/xbuild/extension.py
- src/core/column/sentinel_fw.cc
- src/core/csv/reader_parsers.h
- src/core/expr/py_by.cc
- src/core/expr/py_join.cc
- src/core/expr/py_sort.cc
- src/core/expr/py_update.cc
- src/core/expr/workframe.h
- src/core/python/args.h
- src/core/python/obj.cc
Fix multiple warnings reported by clang.
> Fix compilation warnings in clang 11.0

- src/core/expr/eval_context.cc
- src/core/frame/integrity_check.cc
- src/core/parallel/monitor_thread.cc
- src/core/utils/terminal/terminal.cc
More warning fixes and minor improvement to frame integrity checks.
> Fix gcc warnings on linux

- docs/_static/changelog.css
- src/core/.readthedocs.yml
- src/datatable/sphinxext/xcontributors.py
> Add .readthedocs.yml config file

- docs/_static/xfunction.css
- docs/api/frame.rst
- docs/api/frame/countna.rst
- docs/api/frame/countna1.rst
- docs/api/frame/export_names.rst
- docs/api/frame/names.rst
- src/core/frame/names.cc
- src/core/frame/py_frame.cc
- src/core/frame/stats.cc
- src/datatable/sphinxext/dt_changelog.py
- src/datatable/sphinxext/xfunction.py
- tests/test_dt.py
- Added documentation for `.countna()`, `.countna1()`, `.export_names()` and `.names`;
- Created sphinx directive `.. xversionadded` which automatically links to the release-notes page;
- Added support for getters/setters/deleters in the `.. xdata` directive.
> Improve Frame's documentation

- docs/releases/v0.11.0.rst
- src/core/parallel/string_utils.cc
- tests/munging/test_cast.py
> Fix casting str32<->str64 for a 0-row column

- src/core/sort.cc
- src/core/sort/common.h
- src/core/sort/radix-sort.h
- src/core/sort/sorter.cc
- src/core/sort/sorter.h
- src/core/sort/sorter_bool.h
- src/core/sort/sorter_int.h
- src/core/sort/sorter_multi.h
- src/core/sort/sorter_raw.h
- src/core/utils/misc.cc
- src/core/utils/misc.h
- tests/ijby/test-sort.py
In this PR I implement sorting for int8 and int16 columns, and fix multiple bugs in the base radix-sort implementation. Also, several sorting tests added.
> Improvements to "newsort" algo

- src/core/sort.cc
- src/core/sort/radix-sort.h
- src/core/sort/sorter.cc
- src/core/sort/sorter_float.h
- src/core/sort/sorter_int.h
- src/core/sort/sorter_raw.h
- tests/ijby/test-sort.py
Implement sorting for int32, int64, float32 and float64 columns.
> Newsort update

- src/core/sort.cc
- src/core/sort/common.h
- src/core/sort/grouper.h
- src/core/sort/insert-sort.h
- src/core/sort/radix-sort.h
- src/core/sort/sorter.cc
- src/core/sort/sorter.h
- src/core/sort/sorter_bool.h
- src/core/sort/sorter_float.h
- src/core/sort/sorter_int.h
- src/core/sort/sorter_multi.h
- src/core/sort/sorter_raw.h
- tests/ijby/test-sort.py
This adds ability to sort by multiple columns, the most important sorter so far, however it still seems to fail in some cases.
The new sorter is still work in progress.
> WIP on new-sort

- src/core/models/aggregator.cc
- src/core/models/aggregator.h
- tests/models/test_aggregate.py
Fix 2D mixed aggregation to never return empty exemplars frame on non-empty data.
Closes #2397
> Fix 2D mixed aggregation

- tests_random/attacker.py
- tests_random/metaframe.py
- tests_random/utils.py
> Implement forks in random attack tests

- docs/releases/v0.11.0.rst
- src/core/frame/cast.cc
- tests/munging/test_cast.py
> Casting a column into its own type is now a no-op

- ci/xbuild/logger.py
- docs/releases/v0.11.0.rst
- src/core/_dt.h
- src/core/csv/reader.cc
- src/core/frame/__repr__.cc
- src/core/frame/names.cc
- src/core/utils/exceptions.cc
- src/core/utils/exceptions.h
- src/core/utils/file.cc
- src/core/utils/fuzzy_match.cc
- src/core/utils/misc.cc
- src/datatable/exceptions.py
- src/datatable/utils/fread.py
- src/datatable/utils/misc.py
- tests/frame/test-colindex.py
- tests/fread/test_fread_api.py
> Escape column names with backticks in error messages

- ci/Jenkinsfile.groovy
Follow-up on https://github.com/h2oai/datatable/pull/2447
> Fix master builds on Jenkins

- README.md
- docs/install.rst
- docs/releases/v0.11.0.rst
With the new release datatable will also be available on Windows. In this PR we update documentation and release notes accordingly.
Closes #1114
> Update docs and release notes wrt Windows support 

- ci/ext.py
Currently the wheels are built in "production" mode. However, occasionally there may be a need to produce a wheel with a "debug" version of the core library. This is now possible via
```
python ci/ext.py debug
python ci/ext.py wheel --nobuild
```
> Enable building debug-mode wheels

- docs/api/api-index.rst
- docs/api/dt/ifelse.rst
- docs/releases/v0.11.0.rst
- src/core/column/ifelse.cc
- src/core/column/ifelse.h
- src/core/datatablemodule.cc
- src/core/datatablemodule.h
- src/core/expr/!readme.md
- src/core/expr/head_func.cc
- src/core/expr/head_func.h
- src/core/expr/head_func_ifelse.cc
- src/core/expr/op.h
- src/datatable/__init__.py
- src/datatable/expr/expr.py
- tests/ijby/test-ifelse.py
- Add function `ifelse(test, yes, no)`;
- Created a brief doc on how new Exprs should be added (see `src/core/expr/!readme.md`).
Closes #2411
> Implement ifelse() function

- README.md
- docs/_static/code.css
- docs/_static/xfunction.css
- docs/api/api-index.rst
- docs/api/dt/by.rst
- docs/api/dt/cbind.rst
- docs/api/dt/fread.rst
- docs/api/dt/ifelse.rst
- docs/api/dt/iread.rst
- docs/api/dt/rbind.rst
- docs/api/dt/repeat.rst
- docs/api/dt/shift.rst
- docs/api/dt/sort.rst
- docs/api/dt/update.rst
- docs/api/math.rst
- src/core/expr/py_by.cc
- src/core/expr/py_sort.cc
- src/core/expr/py_update.cc
- src/core/frame/cbind.cc
- src/core/frame/rbind.cc
- src/core/frame/repeat.cc
- Added documentation for several datatable functions;
- Slightly adjusted style of inline code elements: now missing links are shown in red;
- `:mod:'datatable'` target now works properly.
> Documentation improvements

- docs/_static/code.css
- docs/develop/contrib.rst
Added step-by-step instructions for how to fork the repository, make some changes and then submit a pull request.
> Expanded documentation on contributing

- src/core/expr/fbinary/pyfn.cc
- src/core/expr/fnary/pyfn.cc
- src/core/expr/funary/pyfn.cc
- src/core/models/murmurhash.cc
- src/core/python/ext_module.h
- src/core/stype.h
Templated `_sfr<>` constants needed to be declared static.
Closes #2480
> Fix linking issues on macOS Catalina 10.15.5

- ci/gh.py
- docs/_static/code.css
- docs/api/dt/rbind.rst
- docs/develop/contrib.rst
- docs/develop/documentation.rst
- docs/develop/index-develop.rst
- docs/manual/f-expressions.rst
- docs/releases/v0.10.0.rst
- docs/releases/v0.11.0.rst
- docs/start/install.rst
Added doc page about how to contribute documentation.
Closes #2485
> Documentation about documentation

- ci/gh.py
The message may be surrounded with `_` to indicate italic font.
> Update regex to catch Attribute-To message in github PR text

- .travis.yml
- ci/Jenkinsfile.groovy
- update Jenkins script to properly fetch a branch even if it is in the forked git repository;
- fortify Travis script.
> Fortify Jenkins and Travis build scripts

- .travis.yml
- appveyor.yml
- ci/Jenkinsfile.groovy
- ci/ext.py
- tests/__init__.py
- tests/test_dt.py
- tests/test_parallel.py
> Debug build

- .gitignore
- .vscode/settings.json
- docs/manual/fread_examples.rst
- docs/manual/index-manual.rst
This is a collection of usage examples for `fread`.
> [DOC] Fread usage examples

- src/core/csv/reader_fread.cc
- tests/fread/test_fread_issues.py
> Fix minor issue with fread() on a broken file

- docs/manual/groupby_examples.rst
- docs/manual/index-manual.rst
This is a collection of examples for groupby - it aims to improve the documentation for datatable and show various uses of the `by` function.
Closes #2363
> [DOC]Groupby examples documentation

- docs/_static/code.css
- docs/api/frame.rst
- docs/api/frame/ltypes.rst
- docs/api/frame/materialize.rst
- docs/api/frame/ncols.rst
- docs/api/frame/nrows.rst
- docs/api/frame/shape.rst
- docs/api/frame/stype.rst
- docs/api/frame/stypes.rst
- docs/api/frame/to_dict.rst
- docs/api/frame/to_jay.rst
- docs/api/frame/to_list.rst
- docs/api/frame/to_numpy.rst
- docs/api/frame/to_pandas.rst
- docs/api/frame/to_tuples.rst
- src/core/frame/py_frame.cc
- src/core/frame/to_numpy.cc
- src/core/frame/to_python.cc
- src/core/jay/save_jay.cc
- tests/test_dt.py
- Added documentation for multiple properties/methods in the Frame class.
- Adjusted styles of the side menu:
- lower level sub-menus now have less padding, making them appear more compact;
- the currently active entry in the menu now has consistent style regardless of the level;
- more consistent styling of hover elements.
> Expand documentation of the Frame class

- tests/munging/test_rbind.py
> Added a test for rbinding a frame and then saving to Jay

- docs/manual/index-manual.rst
- docs/manual/row_functions.rst
This is documentation for the available row functions in datatable, with examples.
> Documentation on row functions

- src/core/expr/fexpr_func.cc
- src/core/expr/fexpr_func.h
- src/core/expr/fexpr_ifelse.cc
- src/core/expr/head_func.cc
- src/core/expr/head_func.h
- src/core/expr/op.h
- src/datatable/expr/expr.py
Converted `ifelse()` function into the new `FExpr` format.
WIP for #2562
> Fexpr ifelse

- src/core/expr/declarations.h
- src/core/expr/eval_context.cc
- src/core/expr/expr.cc
- src/core/expr/expr.h
- src/core/expr/fexpr.cc
- src/core/expr/fexpr_dict.cc
- src/core/expr/fexpr_dict.h
- src/core/expr/fexpr_frame.cc
- src/core/expr/fexpr_frame.h
- src/core/expr/fexpr_list.cc
- src/core/expr/fexpr_list.h
- src/core/expr/head.h
- src/core/expr/head_list.cc
> FExprs_Frame, FExpr_List and FExpr_Dict

- docs/_static/code.css
- docs/_static/xfunction.css
- docs/api/frame.rst
- src/core/frame/py_frame.cc
- src/datatable/sphinxext/xfunction.py
- Added ability to create documentation for C++ classes, via the `.. xclass` directive that works similarly to `.. xfunction`.
- Expanded documentation for `Frame` class
WIP for #2586
> ..xclass directive

- src/datatable/sphinxext/xfunction.py
We have many pages in the docs that derive their data from C/C++ sources via the `..xfunction` directive.
After this PR, those pages will be rebuilt automatically after `make html` without having to run `make clean` first; thus improving the speed of documentation development.
> Sphinx: auto-rebuild pages when their sources are modified

- docs/api/math.rst
- docs/api/models.rst
- docs/api/models/Ftrl/alpha.rst
- docs/api/models/Ftrl/beta.rst
- docs/api/models/Ftrl/colname_hashes.rst
- docs/api/models/Ftrl/colnames.rst
- docs/api/models/Ftrl/double_precision.rst
- docs/api/models/Ftrl/feature_importances.rst
- docs/api/models/Ftrl/interactions.rst
- docs/api/models/Ftrl/labels.rst
- docs/api/models/Ftrl/lambda1.rst
- docs/api/models/Ftrl/lambda2.rst
- docs/api/models/Ftrl/mantissa_nbits.rst
- docs/api/models/Ftrl/model.rst
- docs/api/models/Ftrl/model_type.rst
- docs/api/models/Ftrl/model_type_trained.rst
- docs/api/models/Ftrl/nbins.rst
- docs/api/models/Ftrl/negative_class.rst
- docs/api/models/Ftrl/nepochs.rst
- docs/api/models/Ftrl/params.rst
- docs/api/models/ftrl.rst
- docs/releases/v0.10.0.rst
- src/core/models/py_ftrl.cc
Small fixes to FTRL docs to ensure that all links are working properly.
WIP for #2586
> Updates to FTRL docs

- src/core/expr/fbinary/fexpr__truediv__.cc
- tests/expr/fbinary/test-truediv.py
> Dividing by zero gives inf instead of NA

- src/core/expr/fbinary/fexpr__pow__.cc
- tests/expr/fbinary/test-pow.py
> Promote result to float for the power operator

- docs/releases/v0.11.0.rst
- src/core/sort.cc
- tests/ijby/test-sort.py
> Make empty sort API consistent

- docs/manual/groupby_examples.rst
- Used `code-block:: python` for code blocks
- Made minor corrections to spellings
> [DOC] Updates to groupby documentation

- src/core/expr/eval_context.cc
- src/core/expr/eval_context.h
- src/core/expr/fexpr_list.cc
- tests/ijby/test-sort.py
> Fix reverse flag in sort

- src/datatable/sphinxext/xfunction.py
> Fix regexp to parse parameter in xfunction signature

- docs/releases/v0.11.0.rst
- src/core/frame/rbind.cc
- tests/munging/test-rbind.py
> Fix issue with rbinding frames from a generator

- docs/_static/code.css
> Adjust styles for bullet lists in generated docs

- docs/manual/comparison_with_rdatatable.rst
- Added functions in ``data.table`` that currently do not have equivalents in ``data.table`` and are likely to be implemented
Closes #2400
> functions from data.table that are not in datatable

- docs/manual/groupby_examples.rst
- Added examples to simulate R's `which.max`/`which.min` when grouping.
> added more examples simulating for groupby docs

- docs/releases/index-releases.rst
- docs/releases/v0.11.0.rst
- docs/releases/v1.0.0.rst
- docs/start/install.rst
- src/datatable/sphinxext/dt_changelog.py
> Update documentation after the release

- docs/_static/code.css
- docs/index.rst
The new design is more energetic and fun; and it also better resonates with the style of our logo.
> Update style of the documentation front page

- appveyor.yml
Improve AppVeyor building script and convert it to the PowerShell format.
Closes #2653
> Convert appveyor.yml to the PowerShell format

- docs/releases/v0.11.0.rst
Fix several links, plus minor fixes to the format and text.
> Minor fixes to the 0.11.0 release notes

- docs/releases/v1.0.0.rst
- src/core/read/fread/fread_thread_context.cc
- src/core/read/parsers/parse_string.cc
- tests/fread/test-fread-issues.py
> Fix fread bug with windows newlines and uneven number of fields

- docs/_static/wren.css
**Before ..................................................................... After**
> Style ReadTheDocs pop-out menu

- docs/_static/wren.css
> Fix positioning of nav menu on the right

- docs/_static/wren.css
This  just adds a tiny arrow at the end of a link, same as it was in the old theme.
Closes #2732
> Added indicators of external links

- src/core/expr/py_join.cc
> Fix a link to join tutorial in docs

- docs/api/frame/meta.rst
In this PR we just include `meta.rst` file that was missing in #2734.
> Add missing meta.rst file

- .gitignore
- docs/Makefile
- docs/_static/code.css
- docs/_static/wren.css
- docs/conf.py
- docs/index.rst
> Ensure doc website looks good on mobile devices

- ci/xbuild/wheel.py
Same as #2751, but based on main branch.
Closes #2746
> Fix wheel file creation

- docs/releases/v1.0.0.rst
- src/core/column_from_python.cc
- src/core/frame/__init__.cc
- src/core/python/obj.cc
- src/core/python/obj.h
- tests/frame/test-create.py
> Fix creating Frame from a list of numpy booleans

- src/core/expr/head_reduce_unary.cc
WIP #2604 
- Examples for `median()`
> [DOC] Examples for median()

- src/core/expr/head_reduce_unary.cc
WIP #2604 
- Examples for ``dt.max()``
> [DOC] max() examples

- src/core/expr/head_reduce_unary.cc
WIP #2604 
- Examples for the `mean()` function
> [DOC] Examples for mean()

- src/core/expr/head_reduce_unary.cc
WIP for #2604 
Examples for `last()` function
> [DOC] last() examples

- src/core/expr/py_update.cc
WIP #2604 
- Improves #2722
- Added imports to the examples
> [DOC] update() examples

- src/core/expr/head_reduce_unary.cc
WIP #2604 
- Fix wrong value in mean calculation
> [DOC] mean() examples fix

- src/core/expr/fexpr_ifelse.cc
WIP #2604 
- Fixes  #2724
- Complete import and fixed spelling errors
> [DOC] ifelse() examples 

- src/core/expr/head_reduce_unary.cc
WIP #2604 
- Examples for the `sum`  function
> [DOC] sum() examples

- src/core/expr/head_reduce_unary.cc
WIP #2604 
- Examples for the `min()` function
> [DOC] min() function examples

- src/core/set_funcs.cc
WIP #2604 
- Examples for the `union()` function
> [DOC] examples for union() func

- src/core/set_funcs.cc
WIP #2604 
- Examples for the `unique()` function
> [DOC] examples for unique()

- appveyor.yml
- ci/Jenkinsfile.groovy
- tests/conftest.py
- tests/expr/test-qcut.py
- tests/fread/test-fread-large.py
- add large fread Windows tests for the release mode;
- adjust AppVeyor and Jenkins builds.
> Add large fread tests for Windows, adjust build scripts

- appveyor.yml
Fix release branch builds on AppVeyor.
> Fix release branch builds on AppVeyor

- docs/releases/v1.0.0.rst
- src/core/column/view.cc
- src/core/sort.cc
- tests/test-reduce.py
> Fix a crash when using median() on virtual columns

- README.md
- docs/releases/v0.11.1.rst
- docs/start/quick-start.rst
- tests/__init__.py
- tests/conftest.py
- tests/fread/test-fread-large.py
> Release 0.11.1

- docs/api/stype/__call__.rst
WIP #2604 
- Examples for stype.__call__
> [DOC] Examples for stype

- src/core/expr/head_reduce_binary.cc
WIP #2604 
- Example for `dt.cov`
> [DOC] Examples for dt.cov

- src/core/expr/head_reduce_binary.cc
WIP #2604
- Example for `dt.corr()`
> [DOC] Examples for dt.corr()

- src/core/frame/cbind.cc
WIP #2604 
- Examples for `dt.cbind()`
> [DOC] examples for dt.cbind()

- src/core/expr/head_reduce_unary.cc
WIP #2604 
- Examples for `count()`
> [DOC] Examples for count()

- src/core/expr/head_reduce_unary.cc
WIP for #2604 
- fixes wrong column names
> [DOC] median() examples

- appveyor.yml
- ci/ext.py
- docs/releases/index-releases.rst
- docs/releases/v0.11.0.rst
- docs/releases/v0.11.1.rst
- docs/start/quick-start.rst
- src/core/buffer.cc
- src/core/frame/to_csv.cc
- src/core/lib/mman/mman.cc
- src/core/lib/mman/mman.h
- src/core/utils/file.cc
- src/core/utils/file.h
- src/core/utils/macros.h
- src/core/write/write_manager.cc
- src/core/writebuf.cc
- tests/__init__.py
- tests/conftest.py
- tests/expr/test-qcut.py
- tests/fread/test-fread-large.py
> Merge 0.11.1 into main

- ci/Jenkinsfile.groovy
Since `arrow` cannot be reliably built on ppc machines with pip (and binary wheels are not available), we should avoid any attempt to install arrow for the purpose of testing. Currently this causes all main builds to fail on ppc machines.
> On PPC64 machines avoid installing pyarrow

- src/core/expr/fexpr_astype.cc
WIP #2604 
- Examples for `as_type` function
> [DOC] Examples for as_type

- src/core/expr/py_by.cc
WIP #2604
- Examples for the `by()` function
> [DOC] Examples for by()

- docs/_ext/xcode.py
- docs/_static/wren.css
- docs/_static/xcode.css
- docs/develop/test.rst
- docs/manual/comparison_with_pandas.rst
- docs/manual/comparison_with_rdatatable.rst
- docs/manual/comparison_with_sql.rst
- docs/manual/f-expressions.rst
- docs/manual/fread_examples.rst
- docs/manual/ftrl.rst
- docs/manual/groupby_examples.rst
- docs/manual/row_functions.rst
- docs/start/install.rst
- docs/start/quick-start.rst
- Reviewed documentation files in folders `start/` and `manual/`, with particular focus on formatting of code samples.
- Multiple improvements to general formatting style:
- python and non-python code samples now have more distinctive appearance;
- added language tags for non-python code samples;
- better rendering of keyed frames;
- NA values / triple-dots render properly in dtframes;
- added proper styles for `..note` admonitions;
- Added several more documentation tests.
WIP for #2813
> Documentation cleanup

- src/core/frame/names.cc
- tests/test-dt.py
Closes https://github.com/h2oai/datatable/issues/2829
> Fix segfault when renaming untouched columns

- src/core/frame/rbind.cc
WIP #2604 
closes  #2841
- Examples for dt.rbind()
> [DOC] Examples for dt.rbind()

- src/core/expr/head_reduce_unary.cc
WIP #2604 
- Examples for sd()
> [DOC] Examples for sd()

- src/core/set_funcs.cc
WIP #2604 
- Examples for symdiff()
> [DOC] Examples for symdiff()

- src/core/expr/head_func_shift.cc
WIP #2604 
- Examples for dt.shift()
> [DOC] Examples for dt.shift()

- src/core/set_funcs.cc
WIP #2604 
- Example for setdiff()
> [DOC] Examples for setdiff()

- src/core/set_funcs.cc
WIP #2604 
- Example for dt.intersect()
> [DOC] Examples for intersect()

- src/core/call_logger.cc
- src/core/call_logger.h
- src/core/python/xobject.cc
- src/core/python/xobject.h
- src/core/types/py_type.cc
- src/core/types/py_type.h
- src/core/types/type.cc
- src/core/types/type.h
- src/core/types/type_impl.cc
- src/core/types/type_impl.h
- tests/test-types.py
> Make Type objects hashable

- src/core/expr/fnary/rowcount.cc
WIP #2604 
- Example for `dt.rowcount`
> [DOC] Example for `dt.rowcount`

- src/core/expr/fnary/rowminmax.cc
WIP #2604 
- Example for `dt.rowmin`
> [DOC] for `dt.rowmin()`

- src/core/expr/fnary/rowall.cc
WIP #2604 
- Example for `dt.rowall`
> [DOC] Example for `dt.rowall`

- src/core/expr/fnary/rowany.cc
WIP #2604 
- Example for `dt.rowany`
> [DOC] Example for `dt.rowany`

- src/core/expr/fnary/rowfirstlast.cc
- src/core/expr/fnary/rowminmax.cc
WIP #2604 
- Example for `dt.rowmax`
> [DOC] Rowmax

- src/core/expr/fnary/rowfirstlast.cc
WIP #2604 
- Examples for `dt.rowlast`
> [DOC] Example for `dt.rowlast`

- src/core/expr/fnary/rowfirstlast.cc
WIP #2604 
- Examples for `dt.rowfirst`
> Dt rowfirst

- src/core/frame/repeat.cc
WIP #2604 
- Example for `dt.repeat`
> [DOC] Example for `dt.repeat`

- docs/releases/v1.0.0.rst
- src/core/expr/workframe.cc
- tests/test-dt.py
> Fix performance problems when selecting large number of columns

- docs/releases/v1.0.0.rst
- src/core/jay/open_jay.cc
- tests/test-jay.py
> Fix reading frames with >1M columns from Jay

- docs/manual/fread_examples.rst
- src/core/read/py_fread.cc
WIP #2604 
- Link to fread manual for usage examples
> [DOC] Link to Fread Manual for usage examples

- src/core/expr/fnary/rowsum.cc
WIP #2604 
- Examples for `dt.rowsum()`
> [DOC] Examples for dt.rowsum()

- src/core/expr/fnary/rowmean.cc
WIP #2604 
- Examples for `dt.rowmean()`
> [DOC] Examples for dt.rowmean()

- src/core/expr/fnary/rowsd.cc
WIP #2604 
- Examples for `rowsd()`
> [DOC] Examples for  rowsd

- src/core/expr/py_sort.cc
WIP #2604 
- Examples for dt.sort()
> [DOC] Examples for dt.sort()

- ci/ext.py
- ci/xbuild/wheel.py
- docs/releases/v1.0.0.rst
> Fix installation from source

- tests/types/test-date32.py
This already works, so just adding a test.
WIP for #2858
> Convert date32 to pandas

- src/core/sort.cc
- src/core/sort/sorter.cc
- tests/types/test-date32.py
> Implement sorting  for date32 columns

- docs/api/time.rst
- docs/api/time/day_of_week.rst
- docs/releases/v1.0.0.rst
- src/core/expr/time/fexpr_day_of_week.cc
- src/core/lib/hh/date.cc
- src/core/lib/hh/date.h
- src/datatable/time.py
- tests/expr/time/test-day-of-week.py
New function `day_of_week()` that  computes the week-day component of a given date.
WIP for #2858
> Function day_of_week()

- appveyor.yml
- src/core/expr/fbinary/fexpr__eq__.cc
- src/core/expr/fbinary/fexpr__ge__.cc
- src/core/expr/fbinary/fexpr__gt__.cc
- src/core/expr/fbinary/fexpr__le__.cc
- src/core/expr/fbinary/fexpr__lt__.cc
- src/core/expr/fbinary/fexpr__ne__.cc
- src/core/types/type.cc
- src/core/types/type.h
- src/core/types/type_date.h
- src/core/types/type_impl.cc
- src/core/types/type_impl.h
- src/core/types/type_string.h
- tests/types/test-date32.py
In addition, relational operators updated to use the new type promotion mechanism.
WIP for #2858
> date32 relational operators

- src/core/stats.cc
- tests/test-dt-stats.py
Closes https://github.com/h2oai/datatable/issues/2906
> Make integrity check to use both abs and rel tolerances on statistics

- docs/api/frame/to_pandas.rst
- src/core/frame/py_frame.cc
- src/core/frame/py_frame.h
- src/core/frame/to_numpy.cc
- src/core/frame/to_pandas.cc
> Move Frame::to_pandas() into a separate file

- docs/releases/v1.0.0.rst
- src/core/frame/to_pandas.cc
- src/core/python/tuple.cc
- tests/frame/test-to-pandas.py
If a frame has a key, that key will now become the index of the pandas DataFrame.
Closes #2883
WIP for #2098
> Convert keyed frame to pandas

- src/core/models/dt_linearmodel.cc
> Fix warnings in dt_linearmodel.cc

- src/core/read/output_column.cc
> Fix archiving columns of void type

- src/core/read/output_column.cc
- src/core/read/parsers/parse_time.cc
- src/core/read/parsers/parse_void.cc
- src/core/read/parsers/pt.h
- src/core/read/thread_context.cc
- src/core/stats.cc
- src/core/utils/exceptions.h
- src/core/utils/tests.h
- tests/types/test-time64.py
Currently only the ISO format is supported.
Closes #2924
> Read time64 from csv

- docs/api/math/isna.rst
- src/core/expr/funary/floating.cc
- tests/expr/test-isna.py
- tests/ijby/test-math-floating.py
> Function isna() now works with date32 columns

- docs/manual/index-manual.rst
- docs/manual/select_and_filter_data.rst
WIP #2604 
- Selecting data via rows and columns
- Filtering data via rows
- Examples
> [DOC] Select/filter Data in datatable

- docs/api/fexpr.rst
- docs/api/fexpr/sum.rst
- docs/releases/v1.0.0.rst
- src/core/expr/fexpr.cc
- src/core/expr/fexpr.h
- tests/test-f.py
> Method  Fexpr.sum()

- docs/api/models.rst
- docs/api/models/Ftrl/params.rst
- docs/api/models/LinearModel/__init__.rst
- docs/api/models/LinearModel/double_precision.rst
- docs/api/models/LinearModel/eta0.rst
- docs/api/models/LinearModel/eta_decay.rst
- docs/api/models/LinearModel/eta_drop_rate.rst
- docs/api/models/LinearModel/eta_schedule.rst
- docs/api/models/LinearModel/fit.rst
- docs/api/models/LinearModel/is_fitted.rst
- docs/api/models/LinearModel/labels.rst
- docs/api/models/LinearModel/lambda1.rst
- docs/api/models/LinearModel/lambda2.rst
- docs/api/models/LinearModel/model.rst
- docs/api/models/LinearModel/model_type.rst
- docs/api/models/LinearModel/negative_class.rst
- docs/api/models/LinearModel/nepochs.rst
- docs/api/models/LinearModel/params.rst
- docs/api/models/LinearModel/predict.rst
- docs/api/models/LinearModel/reset.rst
- docs/api/models/LinearModel/seed.rst
- docs/api/models/ftrl.rst
- docs/api/models/linear_model.rst
- src/core/models/py_ftrl.cc
- src/core/models/py_linearmodel.cc
- src/core/models/py_linearmodel.h
Also, minor fixes to `Ftrl` docs.
WIP for #2358
> Add linear model documentation

- src/core/utils/terminal/terminal.cc
> Prevent duplicate Frame display in google.colab notebook

- docs/_static/wren.css
Apparently, some changes to the RTD platform caused certain styles in docs to be broken. This PR fixes those issues.
> Fix style deterioration in docs

- src/core/jay/jay.fbs
- src/core/jay/jay_generated.h
- src/core/jay/open_jay.cc
- src/core/jay/save_jay.cc
- src/core/stats.cc
- tests/types/test-time64.py
> Save time64 column to Jay / open from Jay

- src/core/frame/to_numpy.cc
- src/core/stats.cc
- tests/types/test-time64.py
> Convert time64 column to numpy/pandas

- src/core/column/time_scaled.cc
- src/core/column/time_scaled.h
- src/core/py_buffers.cc
- tests/frame/test-create.py
- tests/types/test-time64.py
> Convert datetime64 numpy/pandas columns into datatable

- src/core/column_from_arrow.cc
- src/core/frame/to_arrow.cc
- tests/types/test-time64.py
> Convert time64 columns to/from arrow

- docs/api/time.rst
- docs/api/time/hour.rst
- docs/api/time/minute.rst
- docs/api/time/nanosecond.rst
- docs/api/time/second.rst
- src/core/expr/eval_context.cc
- src/core/expr/time/fexpr_hour_min_sec.cc
- src/core/expr/time/fexpr_year_month_day.cc
- src/datatable/time.py
- tests/expr/time/test-hour-min-sec.py
> Implement functions hour(), minute(), second(), and nanosecond()

- docs/api/fexpr.rst
- docs/api/fexpr/count.rst
- docs/api/fexpr/first.rst
- docs/api/fexpr/last.rst
- docs/api/fexpr/sd.rst
- docs/api/fexpr/shift.rst
- docs/releases/v1.0.0.rst
- src/core/expr/fexpr.cc
- src/core/expr/fexpr.h
- tests/test-f.py
WIP #2946 
- Add methods for shift, first, last, sd, count.
> [ENH] methods for shift, first, last, sd, count

- src/core/frame/__getbuffer__.cc
- tests/types/test-time64.py
> Fixed conversion of virtual time64 arrays to numpy

- docs/api/frame.rst
- docs/api/frame/countna.rst
- docs/api/frame/countna1.rst
- docs/api/frame/max.rst
- docs/api/frame/max1.rst
- docs/api/frame/mean.rst
- docs/api/frame/mean1.rst
- docs/api/frame/min.rst
- docs/api/frame/min1.rst
- docs/api/frame/mode.rst
- docs/api/frame/mode1.rst
- docs/api/frame/nmodal.rst
- docs/api/frame/nmodal1.rst
- docs/api/frame/nunique.rst
- docs/api/frame/nunique1.rst
- src/core/frame/stats.cc
Also, add documentation for the corresponding one-column frame methods. Some other minor improvements and rearrangements.
> Add documentation for .countna(), .max(), .min(), .mean(), .mode(), .nmodal() and .nunique() frame methods

- src/core/csv/reader.cc
- tests/fread/test-fread-issues.py
Closes #2943 
This is a partial solution that fixes misaligned columns. It doesn't solve creation of an unnamed columns of NA.
> Align columns that are offset by single/multiple tabs

- src/core/column/cast.h
- src/core/column/cast_to_date32.cc
- src/core/types/type_date.cc
- tests/types/test-date32.py
> Convert string+object columns to date32

- docs/releases/v1.0.0.rst
- src/core/expr/declarations.h
- src/core/expr/eval_context.cc
- src/core/expr/eval_context.h
- src/core/expr/fexpr_list.cc
- src/core/expr/fexpr_list.h
- tests/test-groups.py
Closes #2838 
Groupby columns are sorted in reverse order only when negated
> Decouple reverse flag from groupby columns

- src/core/frame/to_numpy.cc
- src/core/stats.cc
- src/core/stats.h
- src/core/types/type.cc
- src/core/types/type.h
- src/core/types/type_date.cc
- src/core/types/type_date.h
- src/core/types/type_time.cc
- src/core/types/type_time.h
- src/core/types/typeimpl.cc
- src/core/types/typeimpl.h
- tests/expr/test-qcut.py
- tests/models/test-ftrl.py
- tests/models/test-linearmodel.py
- tests/test-reduce.py
- tests/types/test-date32.py
- tests/types/test-time64.py
- tests/types/test-type.py
Also, add and improve the relevant tests.
Closes #2988
> Fix `sd()`, `sum()` and `mean()` Frame methods when called on date and time columns 

- tests/types/test-date32.py
- tests/types/test-time64.py
Closes https://github.com/h2oai/datatable/issues/2987
> Add missing tests for statistical frame methods for date and time columns

- docs/releases/v1.0.0.rst
- src/datatable/__init__.py
- tests/test-import-all.py
- tests/test-jay.py
> Remove function dt.open()

- docs/manual/ftrl.rst
- docs/releases/v1.0.0.rst
- src/core/models/dt_ftrl.cc
- src/core/models/label_encode.cc
- src/core/models/py_ftrl.cc
- tests/models/test-ftrl.py
This PR adds support for temporal features in FTRL. It doesn't add support for temporal targets though, since it is not clear how useful it is for real applications.
Closes https://github.com/h2oai/datatable/issues/3007
> Support temporal features in FTRL

- docs/releases/v1.0.0.rst
- src/core/expr/fexpr.cc
- src/core/expr/fexpr_literal_bool.cc
- src/core/python/obj.cc
- tests/test-dt-expr.py
> Use numpy scalars in expressions

- docs/_ext/xcode.py
- docs/develop/create-fexpr.rst
- added missing `#include`s;
- added missing `override` flags in code;
- added "final" code file for reference;
- added new section on debugging.
Closes #3034
> Updated documentation on creating FExprs, 

- docs/releases/v1.1.0.rst
- src/core/read/fread/fread_parallel_reader.cc
- tests/fread/test-fread-issues.py
> fread almost empty file

- docs/api/type/void.rst
- src/core/frame/to_numpy.cc
- tests/frame/test-to-numpy.py
> void column now converts to float64 in .to_numpy()

- docs/api/type/void.rst
- docs/releases/v1.1.0.rst
- src/core/frame/join.cc
- src/core/types/type_void.cc
- src/core/types/type_void.h
- tests/frame/test-create.py
- tests/types/test-void.py
> Void columns now work correctly in joins

- docs/releases/v1.1.0.rst
- src/core/column/column_impl.cc
- tests/types/test-void.py
> Fix infinite recursion when saving view void column to jay

- docs/releases/v1.1.0.rst
- src/core/sort.cc
- tests/types/test-void.py
> Fix multi-sort with void columns

- docs/releases/v1.1.0.rst
- src/core/column.cc
- src/core/sort.cc
- tests/types/test-void.py
> Fix group by operation on void columns

- docs/manual/select_and_filter_data.rst
WIP - #2604 
Update the `select and filter data` doc to use the `Type` class
> [DOCS] Update docs with `Type`

- docs/releases/v1.1.0.rst
- src/core/expr/head_reduce_unary.cc
- tests/test-groups.py
> Fix `dt.sum()` when applied to the same column as `dt.by()`

- src/core/frame/repr/text_column.cc
- src/core/frame/repr/text_column.h
- tests/types/test-array.py
> Arr32 column can now be displayed in a terminal

- src/core/sort.cc
- tests/ijby/test-sort.py
> Fix multi-column sort with const string column

- docs/releases/v1.1.0.rst
- src/core/frame/replace.cc
- tests/munging/test-replace.py
> Support numpy scalars in `Frame.replace()`

- docs/api/dt/sort.rst
- docs/releases/v1.1.0.rst
- src/core/expr/eval_context.cc
- src/core/expr/eval_context.h
- src/core/expr/fexpr_list.cc
- src/core/expr/py_sort.cc
- src/core/expr/py_sort.h
- tests/ijby/test-sort.py
> Sort columns using all booleans in the reverse list

- ci/appveyor.yml
- docs/releases/v1.1.0.rst
- src/core/python/obj.cc
> Add support for python `3.10`

- docs/releases/v1.1.0.rst
- src/datatable/utils/fread.py
- src/datatable/xls.py
- tests/fread/test-xls.py
> Support forward slash, backslash and their mix when reading Excel files

- docs/releases/v1.1.0.rst
- src/core/expr/fexpr.cc
- src/core/expr/re/fexpr_match.cc
- src/core/expr/re/fexpr_match.h
- tests/re/test-match.py
> Add case insensitive support to `dt.re.match()`

- src/core/frame/to_pandas.cc
> Fix `to_pandas()` for keyed frames

- docs/api/re/match.rst
- docs/releases/v1.1.0.rst
Docs adjustments for #3225 and #3223.
> Docs adjustments for `.to_pandas()` and `re.match()` improvements

- tests/models/test-linearmodel.py
This test had to be a part of #3234 as it fails before that PR and should pass now.
> Add a multicolumn test for linear model

- src/core/buffer.cc
- src/core/column/const_na.cc
Cast size_t reference count to Py_ssize_t.
> Fix compiler warnings on Py_SET_REFCNT()

- src/core/column/categorical.cc
- src/core/column/categorical.h
- src/core/types/type_categorical.cc
Some internal preparations to use validity buffer for categorical columns.
> Internals for validity buffer for categorical columns

- src/core/expr/eval_context.cc
- tests/types/test-categorical.py
WIP for https://github.com/h2oai/datatable/issues/1691
> Allow using column selector on categorical columns

- src/core/expr/eval_context.cc
- tests/types/test-array.py
> Allow using column selector on array columns

- docs/api/options/display/max_column_width.rst
> Adjust `max_column_width` docs

- docs/api/dt/cut.rst
- docs/api/dt/qcut.rst
> Improve documentation for `dt.cut()` and `dt.qcut()`

- docs/releases/v1.1.0.rst
- src/core/expr/fexpr_literal_type.cc
- tests/types/test-date32.py
- tests/types/test-time64.py
> Fix selection of `time64` columns

- docs/releases/v1.1.0.rst
- src/core/csv/reader.cc
- src/core/csv/reader.h
- src/core/read/preframe.cc
- src/core/utils/temporary_file.cc
- src/core/utils/temporary_file.h
> Make `tempdir` parameter be honored for memory limited `fread()` operation

- docs/api/fexpr.rst
- docs/api/fexpr/countna.rst
- docs/api/fexpr/nunique.rst
- docs/releases/v1.1.0.rst
- src/core/documentation.h
- src/core/expr/fexpr.cc
- src/core/expr/fexpr.h
- tests/test-f.py
- tests/test-reduce.py
> Add `.nunique()` and `.countna()` methods to `FExpr`

- docs/releases/v1.0.0.rst
- docs/releases/v1.1.0.rst
- src/core/expr/head_func_shift.cc
- tests/dt/test-shift.py
> Fix shifting grouped columns when `n=0`

- src/core/column/const.cc
- src/core/column/repeated.cc
- tests/dt/test-shift.py
> Allow conversion of one-row `SType::VOID` columns to `ConstNa_ColumnImpl`

- docs/api/frame/to_numpy.rst
- docs/releases/v1.1.0.rst
- src/core/frame/to_numpy.cc
- tests/frame/test-to-numpy.py
> Add `c_contiguous` option to `.to_numpy()`

- tests/fread/test-fread-random.py
> Fix `test_fread_omnibus` when only string missings are encountered

- docs/api/dt/rowall.rst
- docs/api/dt/rowany.rst
- src/core/expr/fnary/rowall.cc
- src/core/expr/fnary/rowany.cc
- src/core/types/type.cc
- src/core/types/type.h
- tests/ijby/test-rowwise.py
> Support void columns in `rowall()` and `rowany()`

- src/core/expr/fnary/rowfirstlast.cc
- tests/ijby/test-rowwise.py
> Support void columns in `rowfirst()` and `rowlast()`

- docs/_ext/xfunction.py
- docs/releases/v1.1.0.rst
- src/core/expr/fnary/fnary.cc
- src/core/expr/fnary/fnary.h
- src/core/expr/fnary/rowall.cc
- src/core/expr/fnary/rowany.cc
- src/core/expr/fnary/rowcount.cc
- src/core/expr/fnary/rowfirstlast.cc
- src/core/expr/fnary/rowmean.cc
- src/core/expr/fnary/rowminmax.cc
- src/core/expr/fnary/rowsd.cc
- src/core/expr/fnary/rowsum.cc
- tests/ijby/test-rowwise.py
> Add support for void columns for all the row-functions

- src/core/column/qcut.h
- src/core/expr/fexpr_qcut.cc
- tests/dt/test-qcut.py
- change `is_grouped` to `is_const`;
- add one more test for void columns.
> Minor refactoring and a test for `qcut()` 

- docs/api/frame.rst
- docs/start/using-datatable.rst
Improve "Using datatable" section by adding more consistency to the code and fixing the text. In future, we may also want to add a sample "in.csv" file , so that all the code examples could really be copy-pasted to python for execution.
> Improve documentation on "Using datatable" 

- docs/api/dt/fread.rst
- docs/releases/v1.1.0.rst
- src/core/read/multisource.cc
- src/core/read/source.cc
- tests/fread/test-fread-api.py
- tests/fread/test-fread-large.py
> Support freading from public S3 buckets

- src/core/expr/fexpr_cumminmax.cc
- src/core/expr/fexpr_cumsumprod.cc
- src/core/expr/fexpr_fillna.cc
> Add shortcuts for grouped columns in `cummin()` and `cummax()`

- docs/api/frame/to_csv.rst
- docs/releases/v1.1.0.rst
- src/core/frame/to_csv.cc
- src/core/write/csv_writer.cc
- src/core/write/output_options.h
- src/core/write/value_writer.cc
- src/core/write/write_manager.cc
- src/core/write/write_manager.h
- src/core/write/writing_context.cc
- src/core/write/writing_context.h
- src/core/writebuf.h
- tests/frame/test-tocsv.py
> Support custom separators in `Frame.to_csv()`

- docs/api/frame/to_csv.rst
- docs/releases/v1.1.0.rst
- src/core/write/value_writer.cc
- tests/frame/test-tocsv.py
> Quote missing values in `.to_csv()` when `quoting="all"`

- docs/api/fexpr.rst
- docs/api/index-api.rst
> Minor docs adjustments to `cumcount()` and `ngroup()`

- src/core/column.cc
- src/core/column.h
- src/core/column/latent.h
- src/core/frame/repr/text_column.cc
- src/core/types/type_categorical.cc
- tests/types/test-categorical.py
Fix casting `void` columns to categoricals and add corresponding tests.
WIP for #1691
> Fix casting `void` columns to categoricals

- docs/api/dt/categories.rst
- docs/api/fexpr.rst
- docs/api/fexpr/categories.rst
- docs/api/index-api.rst
- src/core/documentation.h
- src/core/expr/fexpr.cc
- src/core/expr/fexpr.h
- src/core/expr/fexpr_categories.cc
- src/core/types/type_categorical.cc
- src/datatable/__init__.py
- tests/types/test-categorical.py
Implement `dt.categories()` to get categories for categorical columns.
WIP for #1691
> Implement `dt.categories()`

- docs/api/dt/cbind.rst
- docs/api/frame/cbind.rst
- docs/api/frame/export_names.rst
- docs/releases/v0.10.0.rst
WIP for https://github.com/h2oai/datatable/issues/3408
> Improve `cbind` documentation

- docs/releases/v1.1.0.rst
- src/core/py_buffers.cc
- tests/frame/test-create.py
> Fix crash when creating frames from numpy arrays of unicode strings

- docs/_ext/xfunction.py
- docs/api/frame/__getitem__.rst
> Fix rendering documentation for functions with optional parameters

- docs/releases/v1.1.0.rst
- src/core/frame/to_numpy.cc
- tests/frame/test-to-numpy.py
> Make `.to_numpy()` to honor number of rows for zero-column frames

- src/core/parallel/job_idle.cc
- src/core/parallel/thread_team.cc
- throw runtime exception for nested thread pools in the case of `DT_DISABLE`;
- remove unnecessary include.
> Minor improvements to thread pool

- ci/Jenkinsfile.groovy
- ci/appveyor.yml
- ci/ext.py
- ci/xbuild/extension.py
- docs/releases/v1.1.0.rst
- docs/start/install.rst
> Drop python `3.7` support

- docs/api/dt/max.rst
- docs/api/dt/min.rst
- src/core/column/minmax.h
- src/core/expr/fexpr_minmax.cc
- src/core/expr/head_reduce_unary.cc
- src/datatable/expr/expr.py
- src/datatable/expr/reduce.py
- tests/test-reduce.py
> Refactor `min()` and `max()` reducers to use `FExpr`

- src/core/column.h
- src/core/column/column_impl.cc
- src/core/column/column_impl.h
> Minor refactoring of methods to get the underlying column type

- src/core/expr/op.h
- src/datatable/expr/expr.py
> Remove obsolete reducer ops
